### ISSUE TITLE
Document new asyncronousSoftwareUpdate and enforceMinorUpdates

### ISSUE THREAD

**Issue by erikng** [macadmins/nudge#100]
as titled

**Comment by rorymurdock** [comment]
Updated https://github.com/macadmins/nudge/wiki/optionalFeatures

Pending feedback on https://github.com/macadmins/nudge/pull/96/files#r576746693

**Comment by erikng** [comment]
This looks good but closing since we now have: https://github.com/macadmins/nudge/issues/101
