### ISSUE TITLE
optionalFeature: delayInitialNudgeBy

### ISSUE THREAD

**Issue by erikng** [macadmins/nudge#105]
Use case: New machine ships with 11.1 and Nudge is enforced to 11.2.1. During enrollment, Nudge launches over enrollment.

Some things that come to mind
1. The admin could not load the launchagent during enrollment and then logout the user. Upon re-login, they would then get nudged. This would not need any new logic written for Nudge

2. If this feature is created, we will need to log when the first `osVersionRequirement` is met, datestamp it and then compare by x amount of seconds/minutes/hours/days to when to trigger it. This will vastly increase the launch logic and point 1 may be a much more useful workflow.

> Is there any way in Nudge to not do a force install date but to have it force after a certain number of days? It would be rad to see something like this in Nudge.  My main use case for this would currently be for newly deployed devices being shipped with 11.1 or any case where a device is not shipped with the current version of the OS.  I would like to have nudge installed during enrollment and run when the user first logs in.  I’m just unsure how that would work properly including the force install date as these devices will be enrolled on different dates

**Comment by iJake** [comment]
I haven't checked my code in some time but it was fairly easy to pull the date out of the XML for a cached update so that could be read to key off of for Nudge to launch after X days from Update Y being released. My stuff is all Bash based but would be happy to share it if you wanted to rewrite in swift to grab that date.

**Comment by erikng** [comment]
This is done with the latest beta release.
