### ISSUE TITLE
jamf JSON Schema

### ISSUE THREAD

**Issue by erikng** [macadmins/nudge#106]
> Can we have a JSON Schema that we can add to Jamf to build a mobileconfig Profile so all config can be done directly in Jamf, that would be ideal for those who don want to edit the local or remote JSON.

https://docs.jamf.com/technical-papers/jamf-pro/json-schema/10.26.0/Understanding_the_Structure_of_a_JSON_Schema_Manifest.html

https://www.jamf.com/jamf-nation/discussions/34839/custom-schemas-for-application-configuration-profiles

**Comment by fridomac** [comment]
I am working on a Jamf JSON Schema, will do a PR when I am finished (will be a couple of days)

**Comment by fridomac** [comment]
Ok, hit a roadblock: 
Apparently, custom Schema can not include "date" as a field in the Config Profile. 
I cannot find any documentation at Jamf that says otherwise, if anybody knows more about that, let me know!

**Comment by erikng** [comment]
Oh that's an interesting problem to have. JSON doesn't support date fields, so if you look at the json it's a string. The underlying Swift code converts it to a date. 

However the MDM config is a date since plists do support dates. 

That reminds me. I should document this in the wiki.

**Comment by talkingmoose** [comment]
Glad to see someone working on a Jamf manifest for this! The project Jamf has incorporated to add this functionality to Jamf Pro is this one, I believe.

https://github.com/json-editor/json-editor

And that endeavors to follow the JSON Schema spec as much as possible. As @erikng mentioned, JSON itself doesn't support a date/time datatype. The general consensus is to store those values as strings.

https://json-schema.org/specification.html

**Comment by fridomac** [comment]
Will try it out and report back!

**Comment by erikng** [comment]
Strings do not work as currently coded. I played around with this and came up with: https://github.com/macadmins/nudge/commit/0781b54986efc99b3a2e2ec9e0c70dc8b00b7944 however I will be very honest here in that I'm torn.

Nudge supports JSON format to manage it and it is already being coerced into a Date format, but this is a built in feature of Swift

```
let decoder = JSONDecoder()
decoder.dateDecodingStrategy = .iso8601
```

The format we _should_ expect for a plist(mobileconfig) should be a `<date>`. The jamf team should fix this, but I'm sure it will be a while. Given that this is a "good to have" and not a requirement for managing Nudge with jamf, and that no other MDMs would have this issue, I think we should keep this issue/branch open.

If more jamf users want support for this, then we can discuss it.

**Comment by erikng** [comment]
I've decided to merge https://github.com/macadmins/nudge/pull/144. 

I would love @talkingmoose to help spearhead how to support the entire MDM spec within jamf's JSON schema, but I think the only way I can potentially get movement on that is to help make it easier for jamf admins to use my tool.

**Comment by fridomac** [comment]
Ok, will take it up again...

**Comment by erikng** [comment]
https://github.com/macadmins/nudge/wiki/osVersionRequirements#requiredinstallationdate---type-string-for-json-or-date-for-profile-default-value--required-yes is now updated to reflect this change

**Comment by fjprz** [comment]
@fridomac or whomever; I started this but it may need some tweaking...
https://github.com/fjprz/nudge-jamf-json-schema/blob/main/nudge-jamf-schema.json

**Comment by fridomac** [comment]
@fjprz Thank you! I sent you a first pull request, am trying to structure it a little more (with headers for "OS Version Requirements" and "User Experience" and "User Interface".
But maybe I am thinking too complicated and the easier approach would be to just put everything in one hierarchy.
(it is my first Jamf Schema, so be patient with me :-)

**Comment by fridomac** [comment]
I tried generating the profile that is generated by Jamf, but Nudge does not seem to pick up the Configuration.
Guess I am being a bit stupid today, maybe someone can see what is wrong?
https://github.com/fridomac/nudge-jamf-json-schema/blob/main/nudge-jamf-schema.json generated Profile is at https://github.com/fridomac/nudge-jamf-json-schema/blob/main/Nudge%20Preferences-Unsigned.mobileconfig

**Comment by talkingmoose** [comment]
> I've decided to merge #144.
> 
> I would love @talkingmoose to help spearhead how to support the entire MDM spec within jamf's JSON schema, but I think the only way I can potentially get movement on that is to help make it easier for jamf admins to use my tool.

So, [JSON Schema](https://json-schema.org/understanding-json-schema/reference/type.html) is unlikely to support a `date` type, which limits what Jamf can do with it.

However, would an effective workaround be something like this?

_If an [ISO 8601 compliant date/time string](https://en.wikipedia.org/wiki/ISO_8601) is detected, then replace `<string></string>` tags with `<date></date>` tags in the resulting plist used to generate the configuration profile._

It might be beneficial to add Nudge to the [Jamf Marketplace](https://www.jamf.com/community/marketplace/) where it can get additional exposure and generate more awareness of it at Jamf. There's a specific section for "Configuration" where I think it may fit best.

**Comment by erikng** [comment]
> https://github.com/fridomac/nudge-jamf-json-schema/blob/main/Nudge%20Preferences-Unsigned.mobileconfig

@fridomac https://github.com/fridomac/nudge-jamf-json-schema/blob/main/Nudge%20Preferences-Unsigned.mobileconfig#L48-L53 these lines should be under the `optionalFeatures` key and https://github.com/fridomac/nudge-jamf-json-schema/blob/main/Nudge%20Preferences-Unsigned.mobileconfig#L54-L70 should be under the `osVersionRequirements` key. It also looks like there's a few more preferences missing, but that may be that you didn't generate those keys in your test.

**Comment by erikng** [comment]
> > I've decided to merge #144.
> > I would love @talkingmoose to help spearhead how to support the entire MDM spec within jamf's JSON schema, but I think the only way I can potentially get movement on that is to help make it easier for jamf admins to use my tool.
> 
> So, [JSON Schema](https://json-schema.org/understanding-json-schema/reference/type.html) is unlikely to support a `date` type, which limits what Jamf can do with it.
> 
> However, would an effective workaround be something like this?
> 
> _If an [ISO 8601 compliant date/time string](https://en.wikipedia.org/wiki/ISO_8601) is detected, then replace `<string></string>` tags with `<date></date>` tags in the resulting plist used to generate the configuration profile._
> 
> It might be beneficial to add Nudge to the [Jamf Marketplace](https://www.jamf.com/community/marketplace/) where it can get additional exposure and generate more awareness of it at Jamf. There's a specific section for "Configuration" where I think it may fit best.

I like the idea around ISO compliant strings as I believe that's _exactly_ what apple does with JSON strings within Swift. I'll try and work on getting into Jamf Marketplace.

**Comment by fridomac** [comment]
> @fridomac https://github.com/fridomac/nudge-jamf-json-schema/blob/main/Nudge%20Preferences-Unsigned.mobileconfig#L48-L53 these lines should be under the `optionalFeatures` key and https://github.com/fridomac/nudge-jamf-json-schema/blob/main/Nudge%20Preferences-Unsigned.mobileconfig#L54-L70 should be under the `osVersionRequirements` key. It also looks like there's a few more preferences missing, but that may be that you didn't generate those keys in your test.

Yes, there are not all keys there yet. I reworked the Schema to put the preferences in the right keys, and updated the Repo.
Is there a possibility to see every key that Nudge is pulling from the Profile? (already tried Console.app with DEBUG and INFO), which results in the following:
![Bildschirmfoto 2021-03-12 um 13 47 50](https://user-images.githubusercontent.com/6088818/110942421-16469b80-833a-11eb-834b-0e7573818641.png)

I suspect that Nudge does not like it when the keys are wrapped into an <array> before the <dict>, therefore it thinks the "optionalFeatures" and "userInterface" keys are empty.

Will do more testing around this and report back, have a nice weekend!

**Comment by erikng** [comment]
There is not a way to see every key in debug or info mode but it does say in that screenshot that keys are empty so that's a key indicator that profile is not configured correctly. 

It's interesting that the resulting profile is MCX Forced. That's actually the old style of profiles. The style of profile I create is essentially the same and backwards compatible. That might be a great enhancement for Jamf to resolve but for now makes it incredibly hard for you to compare my profile to yours. :/

**Comment by fridomac** [comment]
Ok, thank you Erik. I noticed that the profiles generated by the JSON Schema are always "MCX Forced". (always reminds me of Profile Manager and the "golden Triangle" with AD and OD).
Will do some more testing and try to compare it as good as I can. The upper part of the Profile with "osVersionRequirements" seems to work.
Bye, Fridolin.

**Comment by talkingmoose** [comment]
> > > I've decided to merge #144.
> > > I would love @talkingmoose to help spearhead how to support the entire MDM spec within jamf's JSON schema, but I think the only way I can potentially get movement on that is to help make it easier for jamf admins to use my tool.
> > 
> > 
> > So, [JSON Schema](https://json-schema.org/understanding-json-schema/reference/type.html) is unlikely to support a `date` type, which limits what Jamf can do with it.
> > However, would an effective workaround be something like this?
> > _If an [ISO 8601 compliant date/time string](https://en.wikipedia.org/wiki/ISO_8601) is detected, then replace `<string></string>` tags with `<date></date>` tags in the resulting plist used to generate the configuration profile._
> > It might be beneficial to add Nudge to the [Jamf Marketplace](https://www.jamf.com/community/marketplace/) where it can get additional exposure and generate more awareness of it at Jamf. There's a specific section for "Configuration" where I think it may fit best.
> 
> I like the idea around ISO compliant strings as I believe that's _exactly_ what apple does with JSON strings within Swift. I'll try and work on getting into Jamf Marketplace.

Following up on this.

While JSON Schema doesn't support the "date" datatype, it does support [a "date" **_format_** option](https://json-schema.org/understanding-json-schema/reference/string.html#built-in-formats) that can be added to a property. Its intended use is to validate an ISO 8601 compliant "string" datatype. In the JSON Schema, it would look something like this:

```
"dateInstalled": {
   "title": "Date Installed",
   "description": "Date Installed.",
   "default": "2018-11-13",
   "format": "date",
   "property_order": 14,
   "type": "string"
},
```

I've proposed a change internally at Jamf that if this `"format": "date"` option appears, we convert `<string></string>` tags to `<date></date>` tags for the resulting plist and profile. I think that would satisfy everyone's requirements without making implementation very difficult. (I'm not a developer, though, and will never say, "It should be quick and easy to do.")

Development decisions for implementing a new feature or change to an existing feature aren't always made on the basis of completeness or "that's a good idea". _(Time, money, quality: pick any two._) I don't currently see a [feature request on Jamf Nation](https://www.jamf.com/jamf-nation/feature-requests/latest) for anything like this. Someone from the community should create one and then recruit others to vote it up. Feel free to use the suggestion I've proposed here, if you think it's the best way to implement the feature.

**Comment by erikng** [comment]
Jamf users on this thread. Please do what @talkingmoose is suggesting. I think his idea is great.

**Comment by fridomac** [comment]
I created a Feature Request on Jamf Nation for this:
https://www.jamf.com/jamf-nation/feature-requests/10232/suppport-date-key-in-jamf-custom-json-schema

Please vote it up, if you care about this!

**Comment by fridomac** [comment]
(crossposted from Slack #nudge):
I did some more work on the Schema, but no key apart from "osVersionRequirements" is honoured.
My current guess is that “osVersionRequirements” is an array and is working, because it is also an array in the examples. The Jamf JSON Schema implementation wraps everything in an array if you do a Key with Sub-Keys. Nudge expects the other Keys with just a <dict> after that, which the Schema does not deliver, therefore it sees them as empty.
Did some more testing, if I remove the enclosing `<array>` Tags, it is working.
@talkingmoose Is there a possibility to make JAMF Pro leave out these tags?

**Comment by erikng** [comment]
@fridomac @fjprz I have created my own initial version of the jamf json schema for Nudge. Before I go into setting defaults and adding more items, I'd like someone else to check it. It looks good on my end.

https://github.com/macadmins/nudge/commit/53255ee12042ee7b4ac81d1a0b8218d6a220a179

**Comment by fridomac** [comment]
Will do so first thing tomorrow morning!

Bye, Frido.

**Comment by fjprz** [comment]
Looks good so far; the osVersionRequirements are coming up empty at the moment, but I assume that's because you are still adding stuff.

**Comment by erikng** [comment]
Try now. :)

**Comment by erikng** [comment]
Confirmed with a few users that it's working as expected and I'm also happy with it looking at my jamf instance. If any other have issues come up, please file a new github ticket.

**Comment by dan-snelson** [comment]
@erikng Does your latest update workaround @fridomac's Jamf Feature Request [Suppport "Date" Key in Jamf Custom JSON Schema](https://www.jamf.com/jamf-nation/feature-requests/10232/) ?

**Comment by erikng** [comment]
Indeed it does, but as soon as Jamf works on that, I'm reverting that code.

**Comment by fridomac** [comment]
Thank you @erikng, works here, too. Now I just have to find out what I did wrong in my Version!
