### ISSUE TITLE
Add a warning if Nudge is out of date

### ISSUE THREAD

**Issue by erikng** [macadmins/nudge#112]
This may not be needed, but perhaps buying a domain and letting machines hit it for JSON with the latest official version. We could then warn that Nudge is out of date.

This could help with user support issues.

I'm curious what others think.

**Comment by rorymurdock** [comment]
Sounds harder than it should be, Why not use the GitHub API and match the tags? - https://api.github.com/repos/macadmins/nudge/releases

> "tag_name": "v.1.0.0.02182021025303"

**Comment by erikng** [comment]
I figure at scale GitHub would block us.

**Comment by rorymurdock** [comment]
Good call: "For unauthenticated requests, the rate limit allows for up to 60 requests per hour. Unauthenticated requests are associated with the originating IP address, and not the user making requests."

**Comment by rorymurdock** [comment]
GitHub pages has 100gb limit, that'd be enough

**Comment by erikng** [comment]
Hah! That's a great idea.

**Comment by bradtchapman** [comment]
Is this still something you wanted to do, @erikng, or was this considered and abandoned as part of the telemetry effort?
