### ISSUE TITLE
JSON Schema for Jamf to create Profile to configure Nudge

### ISSUE THREAD

**Issue by MatGriffin** [macadmins/nudge#119]
Feature suggestion for when Nudge can be configured via MDM delivered Profile.
A JSON schema that can be used in Jamf Applications & Custom settings payload so the config of the Profile for nudge is directly in Jamf UI.

**Comment by erikng** [comment]
Jamf does not follow the MDM profile spec so this will not be possible. Please submit a ticket to Jamf asking them to follow the spec. 

This is a dupe of another ticket. Closing.

**Comment by erikng** [comment]
https://github.com/macadmins/nudge/issues/106
