### ISSUE TITLE
Nudge app appears off center when it's opened on an external monitor, then the user disconnects from monitor

### ISSUE THREAD

**Issue by macbm** [macadmins/nudge#121]
When an update is past due, Nudge cannot be dismissed by the "Later" or "I understand" buttons (expected). However, if the user is working off an external monitor, when they unplug and work on the main laptop screen, Nudge does not recenter itself. This prevents the user from fully see and interact with Nudge.

Possible fix: https://developer.apple.com/documentation/appkit/nswindow/1419090-center

<img width="600" alt="Screen Shot 2021-02-19 at 12 31 38 PM" src="https://user-images.githubusercontent.com/38539306/108572448-27663480-72c7-11eb-9305-dd0dc995c452.png">

**Comment by erikng** [comment]
I _think_ I have fixed it: https://github.com/macadmins/nudge/commit/ce198c101ff2e2758eed6e1c38be1d6d5a8fe87e

Please try this version: https://github.com/macadmins/nudge/releases/tag/v.1.0.0.02202021001333

**Comment by erikng** [comment]
It took two commits, but confirmed with @macbm that this fixes it. It will take Nudge 60 seconds to fix this as it's tied to the `nudgeRefreshCycle` key that defaults to 60 seconds, but that's the best I can do without increasing CPU usage and polling this constantly (which I don't think is worth the effort).
