### ISSUE TITLE
Add PrefsManager Class for all prefs related actions

### ISSUE THREAD

**Issue by natewalck** [macadmins/nudge#141]
This class would handle all actions related to reading and writing preferences.

Overview:

- Init would accept optional path to json
- load settings from config profile
- load settings from json if passed
- reconcile settings (prefs > json?)
- Move all pref reads to this new Class
- Add ability to write out prefs around user actions (ToDo - figure out what is needed here)

**Comment by bradtchapman** [comment]
@natewalck  @erikng : is this still needed?  The FR is almost 3 years old.

**Comment by natewalck** [comment]
You are welcome to work on implementing this if you'd like 😀 

It's still a good idea, but time will tell if it gets done before MDM pushed software updates become reliable.

**Comment by erikng** [comment]
It's likely not needed anymore with the refactor
