### ISSUE TITLE
Ability to edit left sidebar text strings

### ISSUE THREAD

**Issue by dstranathan** [macadmins/nudge#145]
Any chance we will see the ability to edit the (currently hard-coded) left sidebar text strings?

Examples:

1 I'd like to replace the word "Ignored" with "Deferred".  'Ignore' is not the right choice of verbiage at my institution.

2 The left sidebar isn't consistent with upper-case and lower-case words. Look carefully you will see what I mean.

(This seems like nitpicky stuff, I know, but I work with people who take language/spelling/grammar seriously and I want Nudge to look as professional and consistent as possible.)

**Comment by erikng** [comment]
I can fix point 2 but it is 99% chance I will not change the left hand and make it user definable. The code is already too complex, especially when you add customizable localization.

**Comment by erikng** [comment]
Sorry I meant point 1/2 but not your initial question

**Comment by dstranathan** [comment]
Thanks Erik. Much appreciated.

Keep up the good work. Looking for to rolling Nudge into production this spring.

**Comment by erikng** [comment]
@dstranathan should be good to go soon. I've merged this into the development branch and will be cutting a pre-release later today with some changes. After I test it all, I'll make a new official version of Nudge.
