### ISSUE TITLE
Add jamf support on wiki

### ISSUE THREAD

**Issue by erikng** [macadmins/nudge#151]
https://github.com/macadmins/nudge/wiki/Jamf-Guide

**Comment by dan-snelson** [comment]
I'd be happy to help, @erikng.

**Comment by erikng** [comment]
@dan-snelson now that jamf JSON Schema is available and tested by a few people to confirm it is working as intended, I would love to take you up on that offer.

**Comment by erikng** [comment]
Nudge [v.1.0.0.03242021182514](https://github.com/macadmins/nudge/releases/tag/v.1.0.0.03242021182514) and higher will be recommended for tested compatibility with jamf JSON Schema.

**Comment by dan-snelson** [comment]
> @dan-snelson now that jamf JSON Schema is available and tested by a few people to confirm it is working as intended, I would love to take you up on that offer.

The least I can do, @erikng; I presume the need for my post-install script has largely been negated.

**Comment by fridomac** [comment]
Let me know if I can help with some part(s). 

Bye, Frido.

**Comment by dan-snelson** [comment]
@fridomac I've posted my initial thoughts; headed into meetings for the rest o' the day.

**Comment by dan-snelson** [comment]
https://github.com/macadmins/nudge/wiki/Jamf-Pro-Guide

**Comment by fridomac** [comment]
> The least I can do, @erikng; I presume the need for my post-install script has largely been negated.

The post install could still be used to deploy the Launch- and Logger-Agents... could be easier to put in an AutoPkg workflow than multiple packages.

**Comment by dan-snelson** [comment]
@erikng Please review the following and confirm if this issue can be closed:
https://github.com/macadmins/nudge/wiki/Jamf-Pro-Guide

Thanks.

**Comment by natewalck** [comment]
Added this to the index on the wiki to make it more discoverable.
