### ISSUE TITLE
gracefully handle Nudge upgrades during active Nudge event

### ISSUE THREAD

**Issue by erikng** [macadmins/nudge#153]
we had internal report of an interesting issue that impacts Nudge upgrades and while I've solved it internally, I'm not sure how to solve it externally.

My munki autopkg recipe has a `blocking_applications` of Nudge, so if someone is actively being Nudge'd, munki cannot update the application safely. What we have done in our autopkg override is put a `postinstall_script` that looks for our launch agent and unloads it, kills Nudge in case someone manually opened nudge and reloads the agent. We've also made a blank array in `blocking_applications`.

While I know not everyone uses munki, what worries me is people blindly installing Nudge updates during an active Nudge event. That might cause Nudge in memory to behave differently.

Some thoughts come to mind like offering a one package of nudge with the agent and one without it, putting more logic in the default postinstall script, but that won't help people who customize the launchagent unless they build their own custom package.

**Comment by erikng** [comment]
I'm concerned about undefined behavior with Swift code being rewritten live on an application. I know MSC from time to time has also had weird quirks like this that got in the way.

On my Apple Silicon mac, I saw one event where I actually rewrote Nudge and Nudge crashed in a way that required a hard reboot, which is what spurred my aggressive postinstall script in the first place. (edited)

**Comment by erikng** [comment]
from @rickheil

> Could you potentially solve the autopkg script by making the launch agent identifier an input variable that folks need to define in their override?

That's not a bad idea about the input variable, though that would mean the package would need to be unpacked/re-packaged for non-munki peeps and break the pkg signing cert :confused:

**Comment by rickheil** [comment]
@erikng just occurred to me - if folks are changing the launch agent name, then they're breaking the pkg signing cert as it is

**Comment by kris-enervee** [comment]
@erikng You have some of this logic for unloading and loading in the postinstall script for the LaunchAgent already.

What if you added the unload bits to a preinstall script of the Nudge application, along with a command like:
```
pgrep -i Nudge | xargs sudo kill
```

That ensures that if you're installing nudge, it unloads the LaunchAgent (as long as you didn't change the default name) and kills the application before the application is installed.

Then in the postinstall script for Nudge you load the LaunchAgent (as long as you didn't change the default name). Except when you load or unload the LaunchAgent, you do a check (like you already do) to verify if the default LaunchAgent path already exists. 

If someone wants to customize their LaunchAgent name, then it's up to them to unload and load it. But as long as you keep the name the same, you can still customize the contents of the LaunchAgent, and then the Nudge.pkg will properly unload and load the LaunchAgent when you update the application.

That should work for both new installs and upgrades with the same package.

**Comment by kris-anderson** [comment]
@erikng You have some of this logic for unloading and loading in the postinstall script for the LaunchAgent already.

What if you added the unload bits to a preinstall script of the Nudge application, along with a command like:
```
pgrep -i Nudge | xargs sudo kill
```

That ensures that if you're installing nudge, it unloads the LaunchAgent (as long as you didn't change the default name) and kills the application before the application is installed.

Then in the postinstall script for Nudge you load the LaunchAgent (as long as you didn't change the default name). Except when you load or unload the LaunchAgent, you do a check (like you already do) to verify if the default LaunchAgent path already exists. 

If someone wants to customize their LaunchAgent name, then it's up to them to unload and load it. But as long as you keep the name the same, you can still customize the contents of the LaunchAgent, and then the Nudge.pkg will properly unload and load the LaunchAgent when you update the application.

That should work for both new installs and upgrades with the same package.

**Comment by erikng** [comment]
After thinking about this, I'm going to take half of @kris-anderson 's suggestion. I'm going to do the `preinstall` portion and kill nudge, but I'm going to leave all of the logic out of LaunchAgent work.

Given that the LaunchAgent will just kick off Nudge at the next time event, the only issue here is Nudge would close during upgrades. Now that Nudge saves how many user deferrals have occurred per Nudge Event, it doesn't feel like a huge issue now.

**Comment by erikng** [comment]
Confirmed https://github.com/macadmins/nudge/commit/1f315bc915774aba4013828a52bea305c3c86453 works as desired.

Closing
