### ISSUE TITLE
Nudge crashing when "Deferral Count" exceeds "allowedDeferrals"

### ISSUE THREAD

**Issue by kennyb-222** [macadmins/nudge#156]
Running into the condition when the "**Deferral Count**" exceeds `allowedDeferrals`, it causes Nudge (Swift) to crash with `Illegal instruction: 4`. My understanding from the [Wiki](https://github.com/macadmins/nudge/wiki/userExperience#alloweddeferrals---type-integer-default-value-1000000) is that this is where the "aggressive user experience" is supposed to get enabled but crashes instead. This occurs on both Intel and M1.

Nudge is called with the following option:
`/Applications/Utilities/Nudge.app/Contents/MacOS/Nudge -json-url file:///Library/nudge/Resources/config.json`

[config.json.zip](https://github.com/macadmins/nudge/files/6145355/config.json.zip)
[nudgeDebugLogStream.log](https://github.com/macadmins/nudge/files/6145343/nudgeDebugLogStream.log)

**Comment by erikng** [comment]
What version of nudge are you on? It's not clear from the logs as it only shows a potential error.

**Comment by kennyb-222** [comment]
Hey @erikng, this is on build[ 1.0.0.03122021152801 ](https://github.com/macadmins/nudge/releases/tag/v.1.0.0.03122021152801). If you need a full log dump let me know, in the initial comment I had only provided the tail of the log just before nudge would refresh and exceed the `allowedDeferrals` integer.

**Comment by erikng** [comment]
@kennyb-222 by any chance are you not passing the `majorUpgradeAppPath` in the `osVersionRequirements` hash? I just think I recreated the issue.

**Comment by kennyb-222** [comment]
@erikng, that works, keeping `majorUpgradeAppPath` in the JSON config no longer crashes Nudge and the "aggressive user experience" is enabled accordingly. Thank you!

**Comment by erikng** [comment]
Awesome. Confirmed with @kennyb-222 that https://github.com/macadmins/nudge/commit/881ef1a010f7887ff135e22830ccaaea0a2db842 also fixes the core issue
