### ISSUE TITLE
Nudge causing reboots when running /usr/sbin/softwareupdate --download --all

### ISSUE THREAD

**Issue by erikng** [macadmins/nudge#159]
I was playing around with Nudge on my personal computer and just saw it try to force log me out.

I've confirmed the same behavior within a terminal (no sudo)

```
/usr/sbin/softwareupdate --download --all
Software Update Tool
Finding available software
Downloading macOS Big Sur 11.2.3
Downloaded: macOS Big Sur 11.2.3
Attempting to quit apps: (
    "com.apple.Compressor"
)
Waiting for user to quit any relevant apps
Successfully quit all apps
Downloaded Pro Video Formats
Done.
```

what's strange is I thought `/usr/sbin/softwareupdate --install --all --force` was the trigger for this, which Nudge does not do.

**Comment by erikng** [comment]
It appears that the bug is caused by having an update that requires applications to quit. After manually installing Pro Video Formats, Nudge and `/usr/sbin/softwareupdate --download --all` no longer cause logout/reboots.

This is most certainly an Apple bug

```
Erik@eriks-macbook-pro ~ % /usr/sbin/softwareupdate --download --all
Software Update Tool
Finding available software
Downloading macOS Big Sur 11.2.3
Downloaded: macOS Big Sur 11.2.3
Attempting to quit apps: (
    "com.apple.Compressor"
)
Waiting for user to quit any relevant apps
Successfully quit all apps
Downloaded Pro Video Formats
Done.

Erik@eriks-macbook-pro ~ % /usr/sbin/softwareupdate --list --all    
Software Update Tool
Finding available software
Software Update found the following new or updated software:
* Label: ProVideoFormats-2.2.1
	Title: Pro Video Formats, Version: 2.2.1, Size: 8175K, Recommended: YES, 
* Label: macOS Big Sur 11.2.3-20D91
	Title: macOS Big Sur 11.2.3, Version: 11.2.3, Size: 2383629K, Recommended: YES, Action: restart, 

Erik@eriks-macbook-pro ~ % softwareupdate --install ProVideoFormats-2.2.1
Software Update Tool
Finding available software
Attempting to quit apps: (
    "com.apple.Compressor"
)
Waiting for user to quit any relevant apps
Successfully quit all apps
Downloaded Pro Video Formats
Installing Pro Video Formats
Done with Pro Video Formats
Done.

Erik@eriks-macbook-pro ~ % /usr/sbin/softwareupdate --list --all         
Software Update Tool
Finding available software
Software Update found the following new or updated software:
* Label: macOS Big Sur 11.2.3-20D91
	Title: macOS Big Sur 11.2.3, Version: 11.2.3, Size: 2383629K, Recommended: YES, Action: restart, 

Erik@eriks-macbook-pro ~ % /usr/sbin/softwareupdate --download --all
Software Update Tool
Finding available software
Downloading macOS Big Sur 11.2.3
Downloaded: macOS Big Sur 11.2.3
```

**Comment by erikng** [comment]
https://openradar.appspot.com/radar?id=4987491098558464

How to replicate.
1. Spin up a VM running 11.0 -> 11.2.2
2. Install https://support.apple.com/kb/DL2020?viewlocale=en_US&locale=en_US
3. Open Terminal and run `softwareupdate --list` and confirm you have a Pro Video Format update and Big Sur update available
4. Open another terminal window and run `man softwareupdate`
5. Open Safari
6. Run `softwareupdate --download --all`

Once softwareupdate has finished downloading the updates, safari will be closed but your vi (man softwareupdate) session has prevented the force reboot

You can re-open Safari and rerun `softwareupdate --download --all` to reliably recreate the attempted force reboot

If you'd like to see the forced reboot, do not perform step 4

**Comment by erikng** [comment]
Nudge will no longer use `softwareupdate` until Apple fixes this: https://github.com/macadmins/nudge/commit/8ab838ca3b4975961cc10fc16858d18b128c1566

**Comment by erikng** [comment]
`/usr/sbin/softwareupdate --download --all --background` could work if nudge had an ability to run as root.

**Comment by kennyb-222** [comment]
Hi @erikng, could we get this back into Nudge? This was fixed in macOS 11.4 beta 3 and is now in the GA release.

> (Beta 3) Resolves an issue where softwareupdate -da would automatically install updates.

**Comment by erikng** [comment]
Yeah I'll get it back but currently on paternity leave. If someone wants to PR it I'll merge it.

**Comment by kennyb-222** [comment]
Thanks @erikng! Hope you're enjoyed the time with family.

**Comment by erikng** [comment]
merged into `development` branch https://github.com/macadmins/nudge/commit/8b5c024cdd9b3a705834366aee9cf7796b89e4b6
