### ISSUE TITLE
CMD + W closes Nudge window and essentially breaks Nudge

### ISSUE THREAD

**Issue by erikng** [macadmins/nudge#163]
@ChefAustin discovered today that he can close the window when running Nudge. In my testing, Nudge cannot recover from this state.

Research will need to be done to see if you can prevent this behavior within the `class AppDelegate` but I feel like it may not be possible and instead Nudge will need to re-open its primary window.

**Comment by natewalck** [comment]
How was command W disabled on nudge-python? I didn't think that worked there.

**Comment by ChefAustin** [comment]
Fwiw `CMD + Q` didn't do anything.

**Comment by erikng** [comment]
Because I had already blocked CMD + Q. I hate you @ChefAustin for discovering this. :)

**Comment by erikng** [comment]
Fixed with: https://github.com/macadmins/nudge/commit/89285bb5d1634cf044a22a9a16b21b9d94c7a1cc

**Comment by erikng** [comment]
> How was command W disabled on nudge-python? I didn't think that worked there.

It wasn't a real app 😆
