### ISSUE TITLE
Feature Request: Send banner or alert notifications

### ISSUE THREAD

**Issue by kennyb-222** [macadmins/nudge#164]
Request to add a feature to allow Nudge to send banner or alert notifications for a predetermined window of time (via Nudge config) before the Nudge app window is scheduled to appear. Users could simply click the notification to bring up the Nudge window. After a preset date/time (or number of days) is determined (from the Nudge config), banner/alert notifications will no longer be displayed and the Nudge app would begin to appear. This would allow for more subtle notifications (and not take away user focus) when initially informing users when updates are required, as well as honoring the [Do Not Disturb](https://support.apple.com/guide/mac-help/use-do-not-disturb-mchl999b7c1a/mac) feature of macOS (#98). This would require adoption of the [UserNotifications Framework](https://developer.apple.com/documentation/usernotifications).

**Comment by erikng** [comment]
My gut reaction to this is it's not something I want to write. While I think it's a great idea, I'm personally a fan of the UI being the only interaction a user has with it.

I'm more interested in the "user deferral UI" than using user notifications. That said, I will keep this issue open in case others chime in and disagree.

**Comment by kennyb-222** [comment]
Thanks @erikng, I'll also share that I'm planning to use Nudge along with [Notifier](https://github.com/dataJAR/Notifier) to achieve a similar end result. We've had complaints about the Nudge UI appearing during "important" meetings while users were sharing their screen across various teams. My thought here is that Notifier has most if not all the Swift code needed for implementation.

**Comment by erikng** [comment]
Tell them to update sooner next time :) I understand those complaints heh.

**Comment by redshirtdave** [comment]
This would be an amazing addition, but understand this is a time investment into another component for the app. In the meantime i'm going with same approach @kennyb-222 is - utilising something like Notifier to launch Nudge.

**Comment by erikng** [comment]
I am going to close this. Now with the new user-quit-deferrals feature, Nudge is less likely to be annoyingly aggressive and users can defer via one hour, one day or their own custom deferral up until the `approachingWindow`.
