### ISSUE TITLE
Nudge left side german translation for Days remaining to update does not work

### ISSUE THREAD

**Issue by colorenz** [macadmins/nudge#166]
Hi the german translation for Days remaining to update does not work on the left side. Everything else is correct in german.

Version: Nudge 1.0.0.03182021190836

In de.lproj/Localizable.strings everything looks fine.

// Days remaining to update
"Days remaining to update:" = "Verbleibende Tage Zur Aktualisierung:";

![image](https://user-images.githubusercontent.com/16665557/111886493-26134f00-89ce-11eb-83eb-8f54d23afd9b.png)

**Comment by erikng** [comment]
Should be fixed with: https://github.com/macadmins/nudge/commit/59654b90bc5ba43fb63b35b241e8318236acfdbd 

Please try https://github.com/macadmins/nudge/releases/tag/v.1.0.0.03202021232852 and report back if it fixes the issue.

**Comment by colorenz** [comment]
Fixed Thank You.

![image](https://user-images.githubusercontent.com/16665557/111888470-26ffad00-89dd-11eb-8b5a-f318d361d1c9.png)

**Comment by erikng** [comment]
Great!
