### ISSUE TITLE
Typo: imminentRefeshCycle missing an 'r'

### ISSUE THREAD

**Issue by MrCoBalt** [macadmins/nudge#171]
Hi there, this is by no means critical and will likely ripple out from the code into the example JSON, mobileconfigs, JAMF & ProfileCreator templates, etc but I'd imagine this key should be `imminentRefreshCycle`?

Cheers!

**Comment by erikng** [comment]
Hopefully this is a typo in the mobilconfigs/JSON and not the actual code. Thanks for the report.

**Comment by erikng** [comment]
There was a typo in the code and the configs/jsons/schema. Thanks for the report. It will be fixed in the next release of Nudge.

**Comment by erikng** [comment]
https://github.com/macadmins/nudge/commit/39f56f4120b9b5f89ec154d33ed8ea603186a4b3
