### ISSUE TITLE
Enable Hardened Runtime for Nudge

### ISSUE THREAD

**Issue by smithjw** [macadmins/nudge#178]
By enabling [Hardened Runtime](https://help.apple.com/xcode/mac/current/#/devf87a2ac8f), Nudge is able to be Notarized (even if you don't plan to add that into your automated build workflow). 

I've cloned the repo locally, added the Hardened Runtime capability, built, and run the app and can't see any change in functionality by enabling this 😄 .

**Comment by erikng** [comment]
Thanks for the report. I plan to add this to Nudge 1.0.1.

**Comment by erikng** [comment]
I did this and forgot to close it. Was added https://github.com/macadmins/nudge/commit/68efaec3909c758ec4809628d0c553027443ceaa on https://github.com/macadmins/nudge/pull/193
