### ISSUE TITLE
Feature Request: Display a negative value for "Days Remaining To Update"

### ISSUE THREAD

**Issue by dan-snelson** [macadmins/nudge#179]
Our `mainContentText` includes the deadline date (so users are less surprised at their inability to click the `primaryQuitButtonText`; see attached).
<img width="1012" alt="Screen Shot 2021-05-18 at 10 33 24 AM" src="https://user-images.githubusercontent.com/24623109/118691455-560c8200-b7c6-11eb-9e91-0c0b465a5c31.png">

Please consider displaying a negative value for "Days Remaining To Update" — potentially in a customizable color — so our support representatives can easily see how many days past the deadline when a user opens a ticket.

Thanks for all your efforts.

**Comment by erikng** [comment]
This has now been fixed. Please see screenshot in merged PR.

**Comment by dan-snelson** [comment]
Works like a champ, @erikng!
