### ISSUE TITLE
Feature Request: Don't Require JSON/MobileProfile updates for each OS update

### ISSUE THREAD

**Issue by eduder** [macadmins/nudge#181]
I love the idea of Nudge, but it would be great to have an option to have it auto query against softwareupdate and detect when a new minor version is available - For example, if a user is on 11.3.0, and 11.3.1 comes out, nudge would automatically detect this release and start nagging the user to upgrade based on whatever settings are configured. Having to deploy a new JSON or MobileProfile for every minor OS release just isn't practical for our situation.

**Comment by n0brainer** [comment]
+1 - this would make more sense for automation of updates, a set and forget.

**Comment by erikng** [comment]
I'm never going to do this. Sorry.
