### ISSUE TITLE
UpdateDevice Button did not work in macOS 11.3.1 with German Lang

### ISSUE THREAD

**Issue by colorenz** [macadmins/nudge#182]
Moin, 

when I click on UpdateDevice Button nothing happens. It does not open the system settings window. If I press Enter, the system settings opens. The PrimaryQuitButton works with the mouse click without problems. If i use English as Device language it works without a Problem. In macOS 11.2.3 it works with German System language without a Problem.

Video 

macOS 11.3.1
Nudge 1.0.0.03242021182514

**Comment by colorenz** [comment]
I have tested a bit again. If I leave the button text empty it works. Then the button works :(

**Comment by colorenz** [comment]
Okay it was a problem in my config. I had to much \n\n\n in my config.

**Comment by erikng** [comment]
Glad you figured it out because I can't touch nudge for a bit longer.
