### ISSUE TITLE
Implement https://gdmf.apple.com/v2/pmv with a cache

### ISSUE THREAD

**Issue by erikng** [macadmins/nudge#190]
https://gdmf.apple.com/v2/pmv is a JSON API that we might be able to leverage to understand when new updates are available, without having to sift through `softwareupdate` cli. We could then perhaps use this for a new key and enforce updates per that.

This could possibly address https://github.com/macadmins/nudge/issues/181 as this comes up often.

**Comment by kennyb-222** [comment]
In addition to https://gdmf.apple.com/v2/pmv, or as an alternative to sifting through the `softwareupdate` CLI, you could reference `/Library/Preferences/com.apple.SoftwareUpdate.plist`. For example the `RecommendedUpdates` key has what you're looking for without any of the overhead of determining hardware compatibility.

**Comment by erikng** [comment]
Closing because of https://github.com/macadmins/nudge/issues/572
