### ISSUE TITLE
Update Device button un-clickable

### ISSUE THREAD

**Issue by delyts** [macadmins/nudge#195]
Using Nudge version 1.0.0.06072021142546. "Update Device" button became unresponsive when clicking on it with the mouse. Hitting the Return key worked and opened System Preferences > Software Update pane. 

This is the mainContentText content where the Update Device button didn't work:
\n\n\n A fully up-to-date device is required to ensure _school name hereAB_ devices are secured and protected\n\n Please connect the power adapter to the computer and click Update Device at your earliest convenience. Make sure your data is always backed up frequently to OneDrive or an external hard drive.**\n\n Click on the 'Update Device' button to open the Software Update window and click “Install Now” or “Restart Now” to start installing the Big Sur updates.**The update can be deferred by clicking “Later” until the deadline date is reached. Once the date is reached, this window will remain open and minimize app windows frequently until the updates are completed.

I removed the Text in BOLD above and used this content to get the Update Device button to work:
\n\n\n A fully up-to-date device is required to ensure _school name hereAB_ devices are secured and protected\n\n Please connect the power adapter to the computer and click Update Device at your earliest convenience. Make sure your data is always backed up frequently to OneDrive or an external hard drive.\n\nThe update can be deferred by clicking “Later” until the deadline date is reached. Once the date is reached, this window will remain open and minimize app windows frequently until the updates are completed.

**Comment by erikng** [comment]
That has been fixed as of https://github.com/macadmins/nudge/commit/a40c52150db3747f82674bf68d06d2252a8bcb83 and will be in the next release of Nudge v1.1.0.

Moving forward, if you need additional text for `mainContentText` that takes over 125 pixels in height, a scroll bar will appear and the user can scroll up/down to read the additional context. The button no longer fails to trigger as well.
