### ISSUE TITLE
Allow "majorUpgradeAppPath" to accept URIs

### ISSUE THREAD

**Issue by willsmithcc** [macadmins/nudge#198]
Please add "local_url_for_upgrade" support like in Nudge Python. Our fleet of users are standard users, so they can't update through Software Update without admin credentials.

We'd love to have our users upgrade via Self Service, but even having the ability to run the installer via script would be a MAJOR help.

**Comment by mac-n-cheese-uk** [comment]
I'll add a +1 for this - we've got got a fleet of 1000 devices and an Infosec team that insist on individual approval tickets for every single admin elevation...the lack of the local URL option is basically what is going to be (reluctantly) keeping us on nudge-python right now

**Comment by erikng** [comment]
This is slightly similar to https://github.com/macadmins/nudge/issues/52, but also different in that you want something like 

`selfservice://blah` or `munki://blah` to open up via the built-in URI options. I will try and implement this in v1.1 of Nudge.

**Comment by erikng** [comment]
This will be available in the next pre-release build of Nudge.

**Comment by willsmithcc** [comment]
Thanks so much, erikng! This is going to make macOS upgrades so much easier for us.
