### ISSUE TITLE
Grey out or color change dates beyond the required install date

### ISSUE THREAD

**Issue by mwmatter** [macadmins/nudge#211]
When selecting a custom defer date users are prevented from selecting dates beyond the deadline date but the dates themselves in the picker look selectable which could lead to user confusion on why the dates cannot be chosen. If it was possible to grey out the dates or change the test color that would help guide users to selecting an appropriate date.

In the example below the 27th is my deadline but the date appears to be selectable.
![calendar-selector](https://user-images.githubusercontent.com/8136042/129805653-79135e4c-6338-4115-addc-979cba978cb8.png)

**Comment by erikng** [comment]
Unfortunately this is not possible due to a limitation with SwiftUI. Please see https://www.robkerr.com/swiftui-datepicker-styling-visual-reference/ for more information.
