### ISSUE TITLE
Nudge doesn't launch if past installation date where requiredMinimumOSVersion is the same

### ISSUE THREAD

**Issue by smithjw** [macadmins/nudge#218]
Found a "bug" with the new deferrals. I say "bug" as it's based on my use case and having two LaunchAgents

Running Standard Config
```
"Device pastRequiredInstallationDate: false"
"User has selected a deferral date (2021-08-20 02:14:39 +0000) that is greater than the launch date (2021-08-20 01:15:33 +0000)"
"Nudge is terminating due to condition met"
```
☝️ This is expected as I've deferred for an hour and not past the deadline

Running Critical Config
```
"Device pastRequiredInstallationDate: true"
"User has selected a deferral date (2021-08-20 02:14:39 +0000) that is greater than the launch date (2021-08-20 01:15:36 +0000)"
"Nudge is terminating due to condition met"
```
☝️ Not expected as I'm past the install deadline

If I run `defaults delete ~/Library/Preferences/com.github.macadmins.Nudge.plist deferRunUntil`, the Critical Nudge session launches as expected not showing any way to dismiss the window as I'm passed the install date.

I don't expect this to be addressed as it's a real edge-case, just highlighting

_Originally posted by @smithjw in https://github.com/macadmins/nudge/issues/157#issuecomment-902360012_

**Comment by smithjw** [comment]
I have also tested updating the `requiredMinimumOSVersion` to trigger Nudge to clear out the deferral but it didn't work as expected. This is the output from the logs

```
requiredMinimumOSVersion
"Device pastRequiredInstallationDate: true"
"New Nudge event detected - resetting deferrals"
"User has selected a deferral date (2021-08-20 02:30:00 +0000) that is greater than the launch date (2021-08-20 01:37:06 +0000)"
"Nudge is terminating due to condition met"
```

**Comment by erikng** [comment]
This is fixed with https://github.com/macadmins/nudge/commit/ed49ab51bd933a4f32b32f80438d307436dac187

If `pastRequiredInstallationDate` is true, all user launch deferrals will be ignored.
