### ISSUE TITLE
User/Session Deferrals are not updating/resetting as expected

### ISSUE THREAD

**Issue by smithjw** [macadmins/nudge#219]
Looking at ~/Library/Preferences/com.github.macadmins.Nudge.plist, while the `deferRunUntil` key accurately shows when I’ve deferred the next Nudge session to run, both `userSessionDeferrals` & `userQuitDeferrals`  show as 0

Nudge UI will show the correct Session Deferral count
![nudge_ui](https://user-images.githubusercontent.com/916389/130167737-63e17b1d-bea0-42f3-8c27-677c06b91e20.png)

But it doesn't reflect in the preferences
![nudge_prefs](https://user-images.githubusercontent.com/916389/130167733-72bbfc01-dd1d-4faf-be51-ed240c809fbd.png)

**Comment by erikng** [comment]
I have completely re-thought out the design logic https://github.com/macadmins/nudge/commit/68e14f0cd24d78789e5069643303f57d3bd8bcd9 and https://github.com/macadmins/nudge/commit/1b4e50b7d69482b82c32ceea2bc04949c14d8adc

It is working for me. I will cut a new release and ask others to test.

**Comment by erikng** [comment]
Also, I have added a new `userDeferrals` key to track the total of quit/session deferrals and this is now what's use to count the deferrals.

**Comment by erikng** [comment]
It's working. If for some reason you disagree, please comment.
