### ISSUE TITLE
If no screenShot icon wanted free up space for text

### ISSUE THREAD

**Issue by CodeBotFly** [macadmins/nudge#229]
I was having trouble in my setup for the UI for the mainContentText always seeming to only fill half the text area. Until I started looking at the userInterface section looking for a way to edit the text area. If we prefer not to have a screenShot icon can there be `hideScreenShot` or some such boolean flag to clear that space to give to the mainContentText area?

**Comment by erikng** [comment]
With v1.1.0, `mainContextText` will now have a scrollable view. Please try that first.

**Comment by CodeBotFly** [comment]
I did take a look at that. I was hoping that `forceScreenShotIcon` set to false would also remove the space but with no icon the scrollable text area appears to cut off randomly halfway in the middle of the text block showing half a line of text. For me that would indicate a scroll area but my users are not so saavy. Thank you for all the hard work on this project already so if thats too much of a hassle to work around I can trim my text down to fit in the visible area. At least the `mainContentNote` isnt being clipped over anymore in the scroll area.

**Comment by erikng** [comment]
Fixed with https://github.com/macadmins/nudge/commit/d3511d1a215f96b9621376a919c0ca89c6e49cf6

`forceScreenShotIcon` defaults already to false. If it is false **and** the screenshots do not exist (you don't pass the key or they simply do not exist) `mainContentText` will now take the full space of the content area.

**Comment by CodeBotFly** [comment]
Thank you!
