### ISSUE TITLE
Create a setup of lookup values for mainContentText

### ISSUE THREAD

**Issue by erikng** [macadmins/nudge#237]
It might be cool to interject items into the `mainContentText` field.

Some ideas that come to mind:
- requiredInstallationDate
- majorUpgradeAppPath
- allowedDeferrals

**Comment by bradtchapman** [comment]
@erikng : probably not needed anymore, if clever people like @dan-snelson figured out a better way?  Or did you want to make this available via Configuration Profile or Jamf JSON?
