### ISSUE TITLE
Don't launch Nudge if apps listed in `acceptableApplicationBundleIDs` are the `frontmostApplication`

### ISSUE THREAD

**Issue by smithjw** [macadmins/nudge#239]
This feature as implemented in https://github.com/macadmins/nudge/pull/208 currently only works on subsequent launches and not if Nudge had been dismissed in the past.

It would be ideal if the admin could define a preference so that if Nudge attempted to launch and the apps defined in `acceptableApplicationBundleIDs` were foremost (On a video call, presenting a Keynote, etc), Nudge would log this and not launch. 

In order to not impede the security of your fleet, it would make sense to only apply this when a device has not yet passed the `requiredInstallationDate`.

I do not know what the correct behaviour should be if a user has exceeded their deferrals, but it is still before the install date. Should Nudge respect the `acceptableApplicationBundleIDs` dict because it's before the required install date, or launch because they have exceeded their deferral limit?

**Comment by erikng** [comment]
One thing I said on Slack but will say here. With Nudge v1.1, it is very likely that the amount of nudge launches/re-activations will **significantly decrease** per nudge event compared to v1.0.

If say you have a required install for 10/01/2021 and the nudge event starts 09/01/2021, the user could actually defer until 09/28/2021. At this point, the user only has 3 days remaining to install the update and it's highly likely you want as many launches/activations as possible at that point.

I can understand wanting this behavior in v1.0, but I think you should deploy v1.1 and see how things are. I'm pretty confident you will close this ticket once you see less of an occurrence it actually is.

**Comment by bradtchapman** [comment]
@smithjw : this is an old issue.  Is it still a problem with any Nudge v1.1 branch, or is it working to your satisfaction and can be closed?
