### ISSUE TITLE
adjusting position of (?) and (X) buttons 

### ISSUE THREAD

**Issue by xirianlight** [macadmins/nudge#246]
Per conversation in Slack on September 3, low-priority item to look at possibly readjusting the positioning of the (?) button in the main view and the (X) button in the custom deferral view (tested here in Monterey beta 6): 
<img width="1012" alt="Screen Shot 2021-09-03 at 8 44 49 AM" src="https://user-images.githubusercontent.com/3473651/132055899-5ae90661-43dd-485a-9b09-342204fc5c74.png">

<img width="1012" alt="Screen Shot 2021-09-03 at 8 43 59 AM" src="https://user-images.githubusercontent.com/3473651/132055905-dba74bba-3212-46a2-adc0-b2e2e5f106a3.png">

The (?) icon would ideally have a slight margin (up and left) to make it not sit quite so close to the edge of the window.

The (X) icon in the custom deferral view would ideally have identical margins to the (X) icon in the "Additional Device Information" view:
![Screen Shot 2021-09-03 at 2 19 12 PM](https://user-images.githubusercontent.com/3473651/132056099-f23a5df7-a224-4df4-a6fe-de43efd86a45.png)

You can see in the above screenshot that the margins are equal on the top and left, unlike the calendar popup modal.

These are all low-priority, QoL fixes to make nudge look more Apple-native and build end-user trust in the notifications.

**Comment by erikng** [comment]
Half of this has been fixed.

**Comment by erikng** [comment]
Closing since it's now fixed.
