### ISSUE TITLE
Nudge Releases have extra .

### ISSUE THREAD

**Issue by rustymyers** [macadmins/nudge#252]
Running the Nudge.download recipe with AutoPkg, it uses GitHubReleasesInfoProvider processor to scrape the releases. It seems to expect the version to be in the format of v1.1.* instead of the current v.1.1.* This causes the version to output from the processor as .1.1.*, which doesn't match the apps bundle version. 

Would it be possible to update the version tags to not include the extra leading v.1.1* and instead format it as v1.1.*?

Thanks
Rusty

**Comment by erikng** [comment]
The versioning has always been 4 digits. Sounds like I need to look at the autopkg recipe.

**Comment by rustymyers** [comment]
Sorry, it's not the four digits... It's the prefix of '.' between the "v" and "1.1.1.*". Does that make sense?

**Comment by erikng** [comment]
I see it now. Thanks for reporting this!

**Comment by rustymyers** [comment]
I think this should be closed. It looks like I'm using an outdated GitHubReleasesInfoProvider which doesn't properly remove the "v." and instead just returns the [1:] from the tag string.
Please feel free to close this now.
Thanks!

**Comment by erikng** [comment]
I actually think this is a bug. I've fixed it with https://github.com/macadmins/nudge/pull/253

**Comment by rustymyers** [comment]
Here's the AutoPkg discussion on it: https://github.com/autopkg/autopkg/issues/746

**Comment by erikng** [comment]
So it was my fault :) I've fixed it anyway.

**Comment by rustymyers** [comment]
I didn't even notice that until you mentioned it :) Thank you so much! It's working perfectly for me now.

**Comment by erikng** [comment]
I went backwards in time and re-issued all the old github tags as well. Looks like this issue has existed since the very first nudge release.
