### ISSUE TITLE
Nudge will not open from terminal or finder on 11.6

### ISSUE THREAD

**Issue by gitgitrequest** [macadmins/nudge#254]
Hello,
Mac M1 8GB RAM 2020
Just tried updated to 11.6 then  installed Nudge for the first time.

Nudge will not open from terminal or finder on 11.6

Ran
 % /Applications/Utilities/Nudge.app/Contents/MacOS/Nudge -version
1.1.1.09082021120759

Deployed Config Profile via jamf

com.github.macadmins.nudge

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>osVersionRequirements</key>
    <array>
      <dict>
        <key>aboutUpdateURL</key>
        <string>https://support.apple.com/en-us/HT212804</string>
        <key>requiredInstallationDate</key>
        <string>2021-09-20T00:00:00Z</string>
        <key>requiredMinimumOSVersion</key>
        <string>11.6</string>
        <key>targetedOSVersionsRule</key>
        <string>11</string>
      </dict>
    </array>
    <key>userExperience</key>
    <dict>
      <key>allowUserQuitDeferrals</key>
      <false/>
    </dict>
    <key>userInterface</key>
    <dict>
      <key>simpleMode</key>
      <true/>
    </dict>
  </dict>
</plist>

**Comment by erikng** [comment]
For support please join the macadmin slack #nudge channel. 

This is likely a configuration issue on your end. There are wiki entries for how to install the logging components as well as debug the issue.
