### ISSUE TITLE
requiredMinimumOSVersion is not Normalizing 11.6.0 on macOS 11.6

### ISSUE THREAD

**Issue by daphatty** [macadmins/nudge#257]
![image](https://user-images.githubusercontent.com/28716334/133632715-5ff5342f-ae92-41c5-b035-2a4514d0b2cc.png)

As you can see from the screenshot, with requiredMinimumOSVersion set to 11.6.0, Nudge will still launch despite the current OS technically matching the Required OS setting. This is particularly an issue in instances where deadlines have expired as Nudge will remain onscreen indefinitely without IT intervention.

**Comment by erikng** [comment]
That's non ideal but for now I recommend fixing your configuration. Normalizing should always be considered best effort, but 11.6.0 is not the correct OS version.

Depending on your tool that deploys nudge, you could also reload the launch agent to fix this behavior.

**Comment by erikng** [comment]
Should be fixed with https://github.com/macadmins/nudge/releases/tag/v1.1.3.11232021144641

If it's not please report back
