### ISSUE TITLE
Where is the "deferral" date stored?

### ISSUE THREAD

**Issue by hohomouse** [macadmins/nudge#258]
Hi Team,

When I click on "Defer 1 hour", and then I run it again but the log says:

`2021-09-16 22:51:07.578023+0800  localhost Nudge[75966]: [com.github.macadmins.Nudge:user-interface] User has selected a deferral date (2021-09-16 15:50:44 +0000) that is greater than the launch date (2021-09-16 14:51:07 +0000)
2021-09-16 22:51:07.578040+0800  localhost Nudge[75966]: [com.github.macadmins.Nudge:user-interface] Nudge is terminating due to condition met`

So I think the "deferred" date must be stored somewhere, but I could not find it.
I want to clear it so that I can run it again and again to test.

Thanks.

**Comment by erikng** [comment]
It is documented here: https://github.com/macadmins/nudge/wiki/User-Deferrals
