### ISSUE TITLE
Log every button click, every action, every state that nudge detects

### ISSUE THREAD

**Issue by erikng** [macadmins/nudge#26]
we need an entire logging pipeline for this. It will need to write to some path nudge can have access to.

Note: We will not be sandboxing the app, so don't have to worry about logs being in the container.

**Comment by rorymurdock** [comment]
For console logging I like the Apple Logger - https://github.com/apple/swift-log (Not to be confused with os.Logger)
But it doesn't write to file. I was thinking of just writing our own where in you'd just
Logger = logger("path/to/file.log") and adding error, warning, debug, info so you'd just go logger.info("OK was pushed")

Was thinking could have a core log and an interface log file separately, what are your thoughts?

**Comment by rorymurdock** [comment]
Have got the code for logging, let me know if you're ok with the above and I'll attach it to all events and commit

**Comment by forvitinn** [comment]
Following up from Slack, the idea I had for this was setting the logging to be optional by adding something like 
`var verboseLogging: Bool?` in the OptionalFeatures struct. 

It would make sense for major actions to be logged be default (nudge presented, nudge ignored, software update initiated) but depending on the amount of verbosity chosen, this might generate a significant amount of information. Its not necessary but it may be a nice feature to implement to reduce the logs generated if you don't want all that information.

**Comment by erikng** [comment]
@rorymurdock when you PR this make sure it's an option in optionalFeatures AND a flag (look at -json-url for guidance) for the log level

**Comment by erikng** [comment]
the optionalFeatures/flag is no longer necessary now that Nudge is using Apple's unified logging + separate (optional) daemon for logs.

https://github.com/macadmins/nudge/pull/95
