### ISSUE TITLE
Feat: Nudge for any required action, not just OS updates

### ISSUE THREAD

**Issue by w0de** [macadmins/nudge#262]
Nudge is looking fairly nice these days.

## 🥧 / ☁️ feature request

It would be neat if Nudge could be adapted to prompt users towards an action that's not an OS update. For instance: enable SIP, logout for Filevault, fill out a form in Workday. 

Nudge would need to support executing user-defined scripts for conditions and actions. It would also need to handle and alert for multiple simultaneous configs.

Anyways, just an idea.

**Comment by smithjw** [comment]
@w0de I think you're better using a tool like [Dialog](https://github.com/bartreardon/Dialog-public) for user-facing notifications. You would then just have multiple scripts that would call Dialog based on your criteria.

**Comment by erikng** [comment]
It's definitely something I've discussed with a few interested parties but would take a ton of effort to accomplish. 

Maybe one day if someone pays me in some capacity ;)

**Comment by bradtchapman** [comment]
If this is `unlike-to-implement`, can it be closed?  @erikng .
