### ISSUE TITLE
Show how to reset Nudge's deferrals for people who use MDM

### ISSUE THREAD

**Issue by perfectly-preserved-pie** [macadmins/nudge#263]
This section: https://github.com/macadmins/nudge/wiki/User-Deferrals#testing-and-resetting-nudge

Explains how to do it for people who _don't_ push out the Nudge config via JAMF or another MDM. That command doesn't work for the MDM people.

Could we add a line underneath that that says:

> If you've deployed Nudge's settings via Configuration Profile or JAMF's JSON Schema feature, the above file path won't exist. Preferences that are pushed via MDM are stored in a different directory, so please use this command instead:
> 
> `defaults delete /Library/Managed\ Preferences/com.github.macadmins.Nudge.plist`
>

**Comment by erikng** [comment]
Those are incorrect instructions. Those are the managed preferences coming from MDM. Nudge, whether it's managed via MDM or the json will contain user preference plist.

doing that command won't do anything.
