### ISSUE TITLE
Feature Request - Ability to add URL to MainText

### ISSUE THREAD

**Issue by Eltord** [macadmins/nudge#267]
It would be useful to be able to add an embedded link to the MainText body of the Nudge app. The use cases for this are primarily in the realm of helping users understand more about what is happening to their device, adding in help desk links, internally shared documentation, etc, and having more embedded links than just the "More Info" text to the bottom right is becoming more necessary now to make sure users have all the info they need from the techs and such.

Thank you

Discussion thread in Slack referencing this FR:
https://macadmins.slack.com/archives/CDUU7DJQ2/p1633540020136200

**Comment by sfc-gh-nkalister** [comment]
+1 on this from our org, we'd like to have this

**Comment by erikng** [comment]
@bartreardon I want to implement something like https://gist.github.com/davidsteppenbeck/a51a55605cc93e696b3cf25066626173 and this might be a good way to also hook into this FR. What do you think given what you've done with your tool?

**Comment by bartreardon** [comment]
I use the [MarkdownUI framework](https://github.com/gonzalezreal/MarkdownUI) which might not be something you want to attach. 

macOS 12 attributed strings can use some limited markdown (cmark standard, although only partial, e.g. no headings AFAIK) so you can support in-text links already with
```swift
if #available(macOS 12.0, *) {
    Text("This is [a link](https://some.url.com)")
}
```

which will look something like:

![image](https://user-images.githubusercontent.com/3598965/168932088-930f76db-c2dc-443c-888b-7fb785e0fb92.png)

If you want to support macos 11 for that type of stuff then you're looking at including a markdown framework though.

**Comment by itsbradwhite** [comment]
+1 would be nice to include a link to our solutions article for Nudge in mainContentText.

Would also be nice to bold portions of mainContentText.

**Comment by ehlersmj4814** [comment]
+1 for enhanced markdown, ability to add bold text, bulleted lists, text colors would be huge

**Comment by rx7raven** [comment]
+1 for markdown.  Would be create to create more dynamic messages for the end user.
