### ISSUE TITLE
attempt to download updates for user prior to launching nudge via softwareupdate

### ISSUE THREAD

**Issue by erikng** [macadmins/nudge#27]
do not do this for M1 macs

**Comment by erikng** [comment]
@rorymurdock you will likely need run this prior to triggering the dispatch queue like I did here: https://github.com/erikng/NudgeSwift/commit/53fb95b89ab72b6403ed6c59e6a5cbb52109de1f

This way you can delay the UI from triggering while still doing the background tasks we want. This will make it similar to Python Nudge.

**Comment by erikng** [comment]
https://github.com/erikng/NudgeSwift/issues/7 dependency

**Comment by rorymurdock** [comment]
Will list and then download so that details are better logged, for example contrast the output of these two commands
![image](https://user-images.githubusercontent.com/9400108/107959678-8f7bea00-6f58-11eb-956a-94ff0a71d043.png)

**Comment by erikng** [comment]
For v1.1 we should add the fetch command to download the entire app. Not necessary for now since that's primarily intended for major upgrades and we won't have to deal with that until September/October.

I've noted in the wiki that the preference does nothing at the moment.

**Comment by erikng** [comment]
done with merge: https://github.com/macadmins/nudge/pull/96
