### ISSUE TITLE
mainContentText view gets cut (scroll)

### ISSUE THREAD

**Issue by mikaellofgren** [macadmins/nudge#273]
When the “understand” button appears (72h default) it seems to cut a row in the mainContentText if you are using like max 9 lines of text. Both on BigSur and Monterey beta. But views before and after that understand button works.

<img width="583" alt="understand" src="https://user-images.githubusercontent.com/6194908/137168823-0dd2050c-be01-483f-afde-7d22b8ddb880.png">
<img width="604" alt="due" src="https://user-images.githubusercontent.com/6194908/137168832-c3874f1b-6139-4dda-a13a-1d15a93a6967.png">

**Comment by erikng** [comment]
Should be fixed with https://github.com/macadmins/nudge/releases/tag/v1.1.3.11232021144641

If it's not please report back
