### ISSUE TITLE
attemptToFetchMajorUpgrade is unused

### ISSUE THREAD

**Issue by tomkins** [macadmins/nudge#278]
Now that Monterey is a reality, I'm testing/tweaking configs, but one thing I can't seem to disable is major upgrades being downloaded automatically.

Sample config file:

```
{
  "osVersionRequirements": [
    {
      "aboutUpdateURL": "https://support.apple.com/en-us/HT211896",
      "requiredInstallationDate": "2021-09-24T00:00:00Z",
      "requiredMinimumOSVersion": "11.6",
      "targetedOSVersionsRule": "default"
    },
    {
      "aboutUpdateURL": "https://support.apple.com/en-us/HT201222",
      "requiredInstallationDate": "2021-10-27T00:00:00Z",
      "requiredMinimumOSVersion": "12.0.1",
      "targetedOSVersionsRule": "11"
    }
  ],
  "userExperience": {
    "allowUserQuitDeferrals": true,
    "allowedDeferrals": 20,
    "allowedDeferralsUntilForcedSecondaryQuitButton": 14,
    "initialRefreshCycle": 28800,
    "approachingRefreshCycle": 6000,
    "approachingWindowTime": 72,
    "imminentRefreshCycle": 600,
    "imminentWindowTime": 24,
    "elapsedRefreshCycle": 300,
    "maxRandomDelayInSeconds": 2,
    "randomDelay": true
  },
  "optionalFeatures": {
    "attemptToFetchMajorUpgrade": false
  }
}
```

(Yes, versioning looks a bit weird - I was just testing a few things!)

Yet, I'm seeing:

```
2021-10-25 23:33:09.431984+0100  localhost Nudge[69780]: [com.github.macadmins.Nudge:softwareupdate-download] enforceMinorUpdates: true
2021-10-25 23:33:09.432130+0100  localhost Nudge[69780]: [com.github.macadmins.Nudge:softwareupdate-list] device requires major upgrade - attempting download
```

Regardless of true or false for `attemptToFetchMajorUpgrade`.

A quick look through the wiki/code suggests this is documented as an option, but I can't see it being actively used (unless I've missed something!).

**Comment by dan-snelson** [comment]
With `attemptToFetchMajorUpgrade` **removed** from the local JSON, "/Applications/Install macOS Monterey.app" still launches each time a user is nudged when prompting to upgrade to `12.0.1` from `11`.

**Comment by erikng** [comment]
Should be fixed with https://github.com/macadmins/nudge/releases/tag/v1.1.3.11232021144641

If it's not please report back
