### ISSUE TITLE
Issues Modifying UI Text Using Configuration Profiles

### ISSUE THREAD

**Issue by rs1278** [macadmins/nudge#280]
Been using Nudge in my environment and loving it so far. However, we are not ready for Monterey and Apple's own "nudge" to get people to update to Monterey hides Big Sur updates to less than obvious tiny "More Info..." link. My plan is to put some text in the mainContentText area so end-users know what to do.

I am using Configuration Profiles to manage Nudge via JAMF Pro and have no issues with the OS version and the required installation date. It seems that the user interface elements don't really take for some reason. I have copied and pasted the JSON Schema.

Could be the case that I've overlooked something simple here, or there's just a bug that's preventing this. Screenshots attached, hope they help. Thanks!!

<img width="1757" alt="Screen Shot 2021-11-10 at 3 35 34 PM" src="https://user-images.githubusercontent.com/92549755/141205713-022aa8a4-5293-4c85-8b6b-fc61fc60dd03.png">
<img width="456" alt="Screen Shot 2021-11-10 at 2 36 16 PM" src="https://user-images.githubusercontent.com/92549755/141205739-f63d5aa6-3d31-4f14-8e15-af1e941547a1.png">
<img width="892" alt="Screen Shot 2021-11-10 at 2 37 45 PM" src="https://user-images.githubusercontent.com/92549755/141205741-d92bd055-e320-4d57-8e52-0955b579524e.png">
<img width="577" alt="Screen Shot 2021-11-10 at 2 37 54 PM" src="https://user-images.githubusercontent.com/92549755/141205742-e4908342-facc-4ba5-aacc-225f6bf23e78.png">

**Comment by dan-snelson** [comment]
Does the following apply, @rs1278?

https://github.com/macadmins/nudge/wiki/Common-Issues

**Comment by erikng** [comment]
https://github.com/macadmins/nudge/wiki/Common-Issues#help-my-paragraph-and-text-changes-are-not-showing-up-in-the-ui

Please see this wiki article.

**Comment by rs1278** [comment]
Thanks for all the quick replies!

Adding the _Language option did the trick. Figured it was something simple like that.
