### ISSUE TITLE
Launching available installers, despite deferral.

### ISSUE THREAD

**Issue by lazymutt** [macadmins/nudge#281]
In the following situation:

- Nudge 1.1.2.10212021172015
- Default 30 minute launchagent
- Monterey installer has been downloaded to /Applications
- Nudge has been deferred to a future date (beyond 30 minutes)

At the next :00/:30 minute mark, the Monterey installer will launch. Is this a Nudge issue?

**Comment by lazymutt** [comment]
It seems any time that Nudge launches, even by hand, so will Monterey.

**Comment by erikng** [comment]
For now please set https://github.com/macadmins/nudge/wiki/osVersionRequirements#majorupgradeapppath---type-string-default-value--required-no

This should stop that behavior (Apple is launching it with the command nudge uses)

**Comment by erikng** [comment]
Should be fixed with https://github.com/macadmins/nudge/releases/tag/v1.1.3.11232021144641

If it's not please report back
