### ISSUE TITLE
Install Configuration Issue

### ISSUE THREAD

**Issue by dgguimaraes** [macadmins/nudge#289]
I'm a junior sys admin testing Nudge for potential deployment, but after running the demo configuration file and approving via Profiles, nothing shows up in Applications. Tried running `log stream --predicate 'subsystem == "com.github.macadmins.Nudge"' --style syslog --color none` but it stalls after spitting output "Filtering the log data using "subsystem == "com.github.macadmins.Nudge""".

I'm running v11.6.1, so input min OS version as 11.99.1, and tried it with multiple different install dates.

This is the com.github.macadmins.Nudge.mobileconfig file after my modifications:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>PayloadContent</key>
    <array>
      <dict>
        <key>PayloadDescription</key>
        <string>Configures all Nudge preferences</string>
        <key>PayloadDisplayName</key>
        <string>Nudge Preferences</string>
        <key>PayloadIdentifier</key>
        <string>com.github.macadmins.Nudge.preferences.example</string>
        <key>PayloadOrganization</key>
        <string></string>
        <key>PayloadType</key>
        <string>com.github.macadmins.Nudge</string>
        <key>PayloadUUID</key>
        <string>CA02957C-7472-446B-9F77-3E0414405556</string>
        <key>PayloadVersion</key>
        <integer>1</integer>
        <key>osVersionRequirements</key>
        <array>
          <dict>
            <key>requiredInstallationDate</key>
            <date>2021-08-28T00:00:00Z</date>
            <key>requiredMinimumOSVersion</key>
            <string>11.99.1</string>
          </dict>
        </array>
      </dict>
    </array>
    <key>PayloadDescription</key>
    <string>Configures Nudge application</string>
    <key>PayloadDisplayName</key>
    <string>Nudge (v1.1.0) Example</string>
    <key>PayloadIdentifier</key>
    <string>com.github.macadmins.Nudge.example</string>
    <key>PayloadOrganization</key>
    <string>Nudge</string>
    <key>PayloadScope</key>
    <string>System</string>
    <key>PayloadType</key>
    <string>Configuration</string>
    <key>PayloadUUID</key>
    <string>2F54F734-132D-4539-B583-F1DCF23DB5EB</string>
    <key>PayloadVersion</key>
    <integer>1</integer>
  </dict>
</plist>
```

Advice appreciated, thanks in advance!

**Comment by engin-cutters** [comment]
Have you tried running Nudge.app? I believe it's just tailing system logs and so far there is nothing to report.

**Comment by elliotnev27** [comment]
Have you tried running Nudge.app? I believe right now it's just tailing the system logs and there is nothing to report.

Once I run Nudge.app you should see something like this.
`2021-12-06 13:56:46.062173-0600  localhost Nudge[2697]: [com.github.macadmins.Nudge:softwareupdate-download] enforceMinorUpdates: true
2021-12-06 13:56:46.207322-0600  localhost Nudge[2697]: [com.github.macadmins.Nudge:utilities] Current operating system (11.6.1) is greater than or equal to required operating system (0.0)
2021-12-06 13:56:46.207374-0600  localhost Nudge[2697]: [com.github.macadmins.Nudge:user-interface] Device is fully updated
2021-12-06 13:56:46.207384-0600  localhost Nudge[2697]: [com.github.macadmins.Nudge:user-interface] Nudge is terminating due to condition met`

**Comment by dgguimaraes** [comment]
Not sure where Nudge.app is located - if it's what is supposed to show up in my Applications folder, it's not there. That would explain why my logging isn't working, but not why Nudge.app is not installing in the first place.

**Comment by engin-cutters** [comment]
`/Applications/Utilities/Nudge.app`

**Comment by elliotnev27** [comment]
Check here: `/Applications/UtilitiesNudge.app`

**Comment by dgguimaraes** [comment]
Nothing like that there either

**Comment by elliotnev27** [comment]
Did you install `Nudge-1.1.3.11292021162608.pkg` in releases? Maybe you did the logger or the LaunchAgent pkg.

**Comment by dgguimaraes** [comment]
There it goes, now showing up in the Utilities folder. Much appreciated!
