### ISSUE TITLE
Close Applications and Install prompt when Nudge launches

### ISSUE THREAD

**Issue by brodjieski** [macadmins/nudge#291]
While testing Nudge to update from 11.6.1 to 11.6.2, my system currently also has a Safari update available. The action to call `softwareupdate --download --all` is causing a prompt to have the user quit Safari and SafariQuickLookPreview (Spotlight).  Even though it is only the download action.  This ends up causing a prompt every time Nudge launches.

This prompt can be recreated by just calling `softwareupdate --download --all` from Terminal.

Is there a way to configure Nudge to not attempt the `softwareupdate --download` in this case?

If there currently is no option to disable the download function, then perhaps a feature request to add it would be appropriate.

**Comment by erikng** [comment]
It sounds like there is a really bad bug Apple introduced that sounds very similar to something I discovered earlier this year in Big Sur. 

Guess it's back :/.

**Comment by erikng** [comment]
https://openradar.appspot.com/radar?id=4987491098558464

**Comment by erikng** [comment]
I think I've fixed it and hopefully "permanently" until Apple screws this up yet again.
