### ISSUE TITLE
Nudge LaunchAgent and Logger packages are not notarized

### ISSUE THREAD

**Issue by fleish** [macadmins/nudge#296]
I'm able to install the main Nudge application pkg without issue, but the Nudge LaunchAgent package fails to install. macOS rejects the pkg file claiming Developer ID is Unnotarized. This can be seen by running `spctl -a -vv -t install Nudge_LaunchAgent-1.0.0.pkg`
```Nudge_LaunchAgent-1.0.0.pkg: rejected
source=Unnotarized Developer ID
origin=Developer ID Installer: Clever DevOps Co. (9GQZ7KUFR6)
```

By comparison, the main Nudge pkg passes `spctl -a -vv -t install Nudge-1.1.3.11292021162608.pkg`
```Nudge-1.1.3.11292021162608.pkg: accepted
source=Notarized Developer ID
origin=Developer ID Installer: Clever DevOps Co. (9GQZ7KUFR6)```

**Comment by erikng** [comment]
I don't currently notarize the launchagent package as many people either do not use it or customize it. 

I may do this in the future, but only if more people want it notarized. All deployment tools shouldn't have any issue deploying non-notarized packages.

**Comment by fleish** [comment]
I'm not particularly invested in the idea as I can repackage & notarize one for my own use. I just thought I'd point it out since it is signed.

**Comment by erikng** [comment]
Now that there is a nudge suite that is signed and notarized, this is not needed in my opinion.
