### ISSUE TITLE
PKG for "Nudge 1.1.4.81280" not notarized

### ISSUE THREAD

**Issue by adibue** [macadmins/nudge#298]
Just found out that the latest version of Nudge fails to install.
It appears that the PKG is not notarized:

For Nudge-1.1.4.81280.pkg
```
$ spctl -a -vv -t install Nudge-1.1.4.81280.pkg
source=Unnotarized Developer ID
origin=Developer ID Installer: Clever DevOps Co. (9GQZ7KUFR6)
```

For the older Nudge-1.1.3.11292021162608.pkg
```
$ spctl -a -vv -t install Nudge-1.1.3.11292021162608.pkg
source=Notarized Developer ID
origin=Developer ID Installer: Clever DevOps Co. (9GQZ7KUFR6)
```

**Comment by erikng** [comment]
I've re-issued Nudge 1.1.4.8120

https://github.com/macadmins/nudge/releases/tag/v1.1.4.81280

I've confirmed both the application and package are notarized and stapled as expected. Thanks for reporting this. It was due to us not signing the new apple EULA developer agreement

**Comment by m1lkman** [comment]
Would it be possible to re-release this with a minor point revision? In my case, I already deployed (Intune) it and it would be much easier to send it out as a new version number. Thanks.
