### ISSUE TITLE
Add MDM profile (NSUserDefaults) support

### ISSUE THREAD

**Issue by erikng** [macadmins/nudge#3]
This giant PR on nudge python added support for mobileconfigs: https://github.com/macadmins/nudge-python/pull/49

We need to add this support as well, so things can be managed via MDM.

**Comment by rorymurdock** [comment]
Did some research from this mornings chat, looks like we could do something like 
`let asyncronousSoftwareUpdate = UserDefaults.standard.value(forKey: "asyncronousSoftwareUpdate") as? Bool ?? nudgePreferences?.optionalFeatures?.asyncronousSoftwareUpdate ?? true` as we can indeed chain the nil coalescing. 

Not sure how it will react when reading in the config as it would default to false not nil if the key is there but with no value. Could end up with some unexpected behaviour.

![image](https://user-images.githubusercontent.com/9400108/108063733-83536380-7010-11eb-9bde-3b992b93cee5.png)

**Comment by erikng** [comment]
It took me two days of banging my head against the wall but it's now all implemented. I need testers though to try if keys are missing not passed, etc etc.
