### ISSUE TITLE
trigger updates info directly from MDM

### ISSUE THREAD

**Issue by erikng** [macadmins/nudge#30]
for @groob - I have no idea how this will work, but it would likely need to be some kind of custom plugin system.

I'm hesitant to support micromdm/ws1/etc within the app due me having to then support it.

Maybe there is a way to read files outside of the app bundle

**Comment by groob** [comment]
I’m going to close this for now, as I think I found an acceptable solution. 

1. Pick a time you’re going to do the force reboot (ex: 1pm local time for all your clients)
2. Update the “important notes” section warning about when the reboot will happen. 
3. Do the reboot on the agreed upon time. 

I was worried about Nudge not being interactive enough for this purpose. The reality even a year after we had this discussion is that MDM ScheduleOSUpdate is a best effort kind of thing, where you can only tell the user that an action _might_ happen at some point in the future.
