### ISSUE TITLE
FR: Provide a way to opt out of `softwareupdate` checks.

### ISSUE THREAD

**Issue by groob** [macadmins/nudge#300]
I discovered there isn't a way to opt out of calls to `softwareupdate` (list or download), so I'm requesting this feature. 

In my experience, running `softwareupdate` with any automation can interfere with OS updates. It would be good to add a configuration parameter that ensured the `runSoftwareUpdate` helper never executes. 

If this sounds okay, I can send a pull request.

**Comment by erikng** [comment]
happy to accept that, but with this not being the default behavior as it will break the core functionality I wrote for major upgrades `--fetch-full-installer`

**Comment by smithjw** [comment]
Great suggestion @groob, I'd also enable this in our environment because of Proxy and internal network issues. 

@erikng +1 to it not being the default behaviour but that can be set by a single preference key.

**Comment by erikng** [comment]
fixed with merged PR
