### ISSUE TITLE
launchagent custom json-url

### ISSUE THREAD

**Issue by alexmateescu** [macadmins/nudge#301]
Hi. how can i rebuild the PKG for the launchagent to include my custom json url?. cheers

**Comment by dan-snelson** [comment]
Happy Tuesday, @alexmateescu!

The following may prove helpful:
[Nudge Post-install](https://github.com/dan-snelson/Nudge-Post-install/wiki)

**Comment by erikng** [comment]
Nudge uses https://github.com/munki/munki-pkg to build its packages. You can create a new pkg by following the readme on that github.
