### ISSUE TITLE
Default targetedOSVersionRule not working as expected

### ISSUE THREAD

**Issue by groob** [macadmins/nudge#306]
(caveat: as expected by me)

I have the following config:

requirements: [ {
minimum: 11.6.4
rule: default } , {
minimum: 12.2.1
rule: default
} ]

What I see: 
macOS 11 hosts are not alerted to upgrade (it tries to nag them about macOS 12 but I have the full installer workflow disabled, so it quits.)

What I expect to see: 

The behavior for Big Sur hosts should be that by default we alert them to upgrade to 11.6.4 instead of targeting the macOS 12 rule.

**Comment by colorenz** [comment]
Look at that example:

https://github.com/macadmins/nudge/wiki/targetedOSVersionsRule#json-1

**Comment by erikng** [comment]
You can't have two default rules. You'd want to do exactly what @colorenz suggests

**Comment by groob** [comment]
It's not two default rules. It's the default behavior overall. IMO it should already be doing what the example does silently -- pick the next closest supported version as the default rule. 

1. if there's a rule for 11 and 12, then pick the 11 rule. 
2. If there's a rule for 12 only, then pick the 12 rule. 
There's very little reason for the host to default to 12 when the 11 rule is there.

**Comment by erikng** [comment]
Devils advocate but what if someone doesn't want that behavior? What if they deploy nudge company wide but only want it triggering for a specific OS family at first?

I'm not sure if I can make everyone happy here, but I will say that I prefer being explicit over implied behavior.

**Comment by groob** [comment]
A shared config will have the same exact behavior across all hosts. If you omit the target rule with 11 and 12 like I show, then only 12 shows up and the dict for 11 is essentially useless. 
What I’m proposing is that if two versions are present, without any extra modifiers, pick the closest (minor releases). And if you want to direct people towards the next major release, then just remove the now obsolete dict. 

I’m moving to a targeted server generated profile for each host, so I’m not as bothered by this behavior anymore. But I wanted to open the issue because in my opinion, my proposal has the most useful behavior for a fleetwide profile targeting all OS versions. 

Feel free to close this issue if there’s nobody else supporting my opinion :)

**Comment by erikng** [comment]
Could you give a full example here? I'm having trouble fully understanding what the config would look like.

**Comment by groob** [comment]
It would look exactly like this:

```
{
  "osVersionRequirements": [
    {
      "requiredInstallationDate": "2021-08-31T00:00:00Z",
      "requiredMinimumOSVersion": "11.5.2",
    },
    {
      "requiredInstallationDate": "2021-10-30T00:00:00Z",
      "requiredMinimumOSVersion": "12.0.1",
    }
  ]
}
```

A system running 11.x would get nudged for 11.5.2 while a system already running 12 would get nudged to 12.0.1
To nudge everyone to 12.x, you just remove the 11 rule.

**Comment by colorenz** [comment]
> It would look exactly like this:
> 
> ```
> {
>   "osVersionRequirements": [
>     {
>       "requiredInstallationDate": "2021-08-31T00:00:00Z",
>       "requiredMinimumOSVersion": "11.5.2",
>     },
>     {
>       "requiredInstallationDate": "2021-10-30T00:00:00Z",
>       "requiredMinimumOSVersion": "12.0.1",
>     }
>   ]
> }
> ```
> 
> A system running 11.x would get nudged for 11.5.2 while a system already running 12 would get nudged to 12.0.1 To nudge everyone to 12.x, you just remove the 11 rule.

You can archive that exactly with this example Configuration.

https://github.com/macadmins/nudge/wiki/targetedOSVersionsRule#json-1

**Comment by groob** [comment]
@colorenz I can’t, because the example configuration you’re linking is explicit about `targetedOSVersionsRule`. I’m making an argument that the key is superfluous.

**Comment by erikng** [comment]
I disagree that it's superfluous.

Let's say you are on 12.2.1 and apple releases 12.3. You push a bunch of people to 12.3 and then immediately apple realizes they fucked up something or releases some 0day patch and pushes 12.3.1 a day later (this happened during big sur)

For the users who installed 12.3 already, you may want to have one install date, but for the people who never installed 12.3, you want them to have their original required installation date

```json
{
  "osVersionRequirements": [
    {
      "requiredInstallationDate": "2022-02-28T00:00:00Z",
      "requiredMinimumOSVersion": "11.6.4",
      "targetedOSVersionsRule": "11"
    },
    {
      "requiredInstallationDate": "2022-02-28T00:00:00Z",
      "requiredMinimumOSVersion": "12.3.1",
      "targetedOSVersionsRule": "12"
    },
    {
      "requiredInstallationDate": "2022-03-14T00:00:00Z",
      "requiredMinimumOSVersion": "12.3.1",
      "targetedOSVersionsRule": "12.3"
    }
  ]
}
```

- 11.x machines get forced to 11.6.4 by 02/28
- 12.x machines get forced to 12.3.1 by 02/28
- 12.3 machines get forced to 12.3.1 by 03/14 giving those good users some more time.

**Comment by erikng** [comment]
I'm going to close this, but if you want to send a PR that can support both your method and maintain current behaviors, I would entertain it.
