### ISSUE TITLE
Minimum Operating System showing (0.0) even thought it is set to 12.2.1?

### ISSUE THREAD

**Issue by adonboli** [macadmins/nudge#310]
So I set the requiredMinimumOSVersion t0 12.2.1 but I still get (0.0) in the log. 

I have tried setting it to 12.2, 12.3, setting targetedOSVersionsRule to default, to 12, anything you can thing of at this point. 

I am not sure what I am doing wrong, I am running the latest Nudge version. 
![NudgeJSONScreenshotJamf](https://user-images.githubusercontent.com/91553350/154162399-1e8cdda0-756c-4a0b-9b45-679dd6a58892.png)

I uploaded the JSON to Jamf and modified as instructed by the Wiki. I can see it showing up on the target device too, but every time it runs I get the information below.

2022-02-15 17:39:04.418882-0500  localhost Nudge[8293]: [com.github.macadmins.Nudge:softwareupdate-download] enforceMinorUpdates: true
2022-02-15 17:39:04.514749-0500  localhost Nudge[8293]: [com.github.macadmins.Nudge:utilities] Current operating system (12.2) is greater than or equal to required operating system (0.0)
2022-02-15 17:39:04.514809-0500  localhost Nudge[8293]: [com.github.macadmins.Nudge:user-interface] Device is fully updated
2022-02-15 17:39:04.514823-0500  localhost Nudge[8293]: [com.github.macadmins.Nudge:user-interface] Nudge is terminating due to condition met

**Comment by erikng** [comment]
It looks good, but I would need to see what's ultimately deployed to the device to see why it's not working

look in `/Library/Managed Preferences` for the nudge.plist

**Comment by adonboli** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>optionalFeatures</key>
	<dict>
		<key>aggressiveUserExperience</key>
		<true/>
		<key>asynchronousSoftwareUpdate</key>
		<true/>
		<key>attemptToFetchMajorUpgrade</key>
		<false/>
		<key>disableSoftwareUpdateWorkflow</key>
		<false/>
		<key>enforceMinorUpdates</key>
		<true/>
	</dict>
	<key>osVersionRequirements</key>
	<array>
		<dict>
			<key>aboutUpdateURL</key>
			<string>https://ithelp.niaid.nih.gov/sp</string>
			<key>requiredInstallationDate</key>
			<string>2021-02-17T00:00:00Z</string>
			<key>requiredMinimumOSVersion</key>
			<string>12.2.1</string>
			<key>targetedOSVersionsRule</key>
			<string>12</string>
		</dict>
	</array>
	<key>userExperience</key>
	<dict>
		<key>allowUserQuitDeferrals</key>
		<false/>
		<key>allowedDeferrals</key>
		<integer>1000000</integer>
		<key>allowedDeferralsUntilForcedSecondaryQuitButton</key>
		<integer>14</integer>
		<key>approachingRefreshCycle</key>
		<integer>6000</integer>
		<key>approachingWindowTime</key>
		<integer>72</integer>
		<key>elapsedRefreshCycle</key>
		<integer>300</integer>
		<key>imminentRefreshCycle</key>
		<integer>600</integer>
		<key>imminentWindowTime</key>
		<integer>24</integer>
		<key>initialRefreshCycle</key>
		<integer>18000</integer>
	</dict>
	<key>userInterface</key>
	<dict>
		<key>iconDarkPath</key>
		<string>/usr/local/NIH/NIAID/jss-logo.png</string>
		<key>iconLightPath</key>
		<string>/usr/local/NIH/NIAID/jss-logo.png</string>
		<key>showDeferralCount</key>
		<true/>
		<key>simpleMode</key>
		<false/>
		<key>singleQuitButton</key>
		<false/>
		<key>updateElements</key>
		<array>
			<dict>
				<key>mainContentNote</key>
				<string>Important Notice:</string>
				<key>mainContentText</key>
				<string>Your Mac needs to install security udpates.\n\nThese updates are mandatory and must be installed by the set deadline.\n\nTo begin the update now, simply click on the button below and follow the provided steps.\n\nIf now is not a good time, you may defer this update until the deferral deadline.\n\nThis process will take approximately 30 minutes and your computer screen might go blank a few times during this process\n\n\n\nFor issues, contact the NIAID Central Service Desk:\n\n\ithelp@niaid.nih.gov - 301-402-2502 - 1-866-740-3642 (toll free)n\n\For RML, contact the RML IT Service Desk:n\n\niaidrmllansupport@niaid.nih.gov - 406-802-6100</string>
				<key>subHeader</key>
				<string>A friendly reminder from NIAID IT</string>
			</dict>
		</array>
	</dict>
</dict>
</plist>

**Comment by adonboli** [comment]
![Nudge Managed PLIST](https://user-images.githubusercontent.com/91553350/154315473-49271220-fac3-4e2c-b825-972363e2da1c.png)

When I paste it, it becomes a big paragraph -- loses its formatting so here is a screenshot?

**Comment by adonboli** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>optionalFeatures</key>
	<dict>
		<key>aggressiveUserExperience</key>
		<true/>
		<key>asynchronousSoftwareUpdate</key>
		<true/>
		<key>attemptToFetchMajorUpgrade</key>
		<false/>
		<key>disableSoftwareUpdateWorkflow</key>
		<false/>
		<key>enforceMinorUpdates</key>
		<true/>
	</dict>
	<key>osVersionRequirements</key>
	<array>
		<dict>
			<key>aboutUpdateURL</key>
			<string>https://ithelp.niaid.nih.gov/sp</string>
			<key>requiredInstallationDate</key>
			<string>2021-02-17T00:00:00Z</string>
			<key>requiredMinimumOSVersion</key>
			<string>12.2.1</string>
			<key>targetedOSVersionsRule</key>
			<string>12</string>
		</dict>
	</array>
	<key>userExperience</key>
	<dict>
		<key>allowUserQuitDeferrals</key>
		<false/>
		<key>allowedDeferrals</key>
		<integer>1000000</integer>
		<key>allowedDeferralsUntilForcedSecondaryQuitButton</key>
		<integer>14</integer>
		<key>approachingRefreshCycle</key>
		<integer>6000</integer>
		<key>approachingWindowTime</key>
		<integer>72</integer>
		<key>elapsedRefreshCycle</key>
		<integer>300</integer>
		<key>imminentRefreshCycle</key>
		<integer>600</integer>
		<key>imminentWindowTime</key>
		<integer>24</integer>
		<key>initialRefreshCycle</key>
		<integer>18000</integer>
	</dict>
	<key>userInterface</key>
	<dict>
		<key>iconDarkPath</key>
		<string>/usr/local/NIH/NIAID/jss-logo.png</string>
		<key>iconLightPath</key>
		<string>/usr/local/NIH/NIAID/jss-logo.png</string>
		<key>showDeferralCount</key>
		<true/>
		<key>simpleMode</key>
		<false/>
		<key>singleQuitButton</key>
		<false/>
		<key>updateElements</key>
		<array>
			<dict>
				<key>mainContentNote</key>
				<string>Important Notice:</string>
				<key>mainContentText</key>
				<string>Your Mac needs to install security udpates.\n\nThese updates are mandatory and must be installed by the set deadline.\n\nTo begin the update now, simply click on the button below and follow the provided steps.\n\nIf now is not a good time, you may defer this update until the deferral deadline.\n\nThis process will take approximately 30 minutes and your computer screen might go blank a few times during this process\n\n\n\nFor issues, contact the NIAID Central Service Desk:\n\n\ithelp@niaid.nih.gov - 301-402-2502 - 1-866-740-3642 (toll free)n\n\For RML, contact the RML IT Service Desk:n\n\niaidrmllansupport@niaid.nih.gov - 406-802-6100</string>
				<key>subHeader</key>
				<string>A friendly reminder from NIAID IT</string>
			</dict>
		</array>
	</dict>
</dict>
</plist>

```

**Comment by rbarlowtapestry** [comment]
I'm also working on a new deployment and seeing similar issue:
Nudge - Nudge-1.1.5.81284.pkg
Default 1.0 Launch Agent.

Testing on 2021 16' MBP M1Pro macOS 12.2.1 already installed.  
Application, LaunchAgent, and Config Profile delivered via Jamf
Json is in /Library/Managed Preferences/com.github.macadmis.Nudge.json.plist (delivered via config file from jamf) - I've also tested renaming it with dropping the .plist that jamf added. 
I've adjusted the required os version as 12.2.2 or 13 or 15 with no luck.  Also adjusted the enforced day both before and after todays date. 

I can only launch demo mode which shows the same 0.0 version and none of the branding listed in the .json

**Comment by rbarlowtapestry** [comment]
Also seeing an issue testing on my daily driver. 2018 MBP Intel on 11.6.4.

**Comment by erikng** [comment]
I'm pretty sure I see the issue.

1. you can't drop plists to that path. That's just what ends up being created by Apple when you deploy a mobileconfig file
2. Even if that did work, the file name is wrong. You have .json.plist. Take the .json out

**Comment by erikng** [comment]
For the original authors issue, are you testing on Big Sur or Monterey with that config?

**Comment by adonboli** [comment]
@erikng Ah that was it... I had to remove .json as you said. I don't know how I missed it. 

Now that it is up and running, I don't see my custom texts that I had put in for the main text, and the sub header and etc. Any thoughts?

**Comment by adonboli** [comment]
> For the original authors issue, are you testing on Big Sur or Monterey with that config?

Monterey for now

**Comment by rbarlowtapestry** [comment]
Was able to resolve, removed the .json part of it; installed the logger and that provided enough direction to see why Nudge wasn't opening (random delay set, asynchronous download etc).

**Comment by adonboli** [comment]
> > @erikng Ah that was it... I had to remove .json as you said. I don't know how I missed it.
> > Now that it is up and running, I don't see my custom texts that I had put in for the main text, and the sub header and etc. Any thoughts?
> > Essentially "updateElements" doesn't seem to apply.
> 
> https://github.com/macadmins/nudge/wiki/Common-Issues

Ah! Fixed it!!
