### ISSUE TITLE
Nudge not honouring active window settings

### ISSUE THREAD

**Issue by TheRealID** [macadmins/nudge#312]
I am currently configuring nudge for the first time within my org.

However it seems like the settings to set nudge as the active window are not being honoured.

This is the Json for the user experience I am using which is stored in /Library/Managed Preferences/com.github.macadmins.nudge.plist (pushed out via JAMF):
```
    userExperience =     {
        allowUserQuitDeferrals = 1;
        allowedDeferrals = 3;
        allowedDeferralsUntilForcedSecondaryQuitButton = 14;
        approachingRefreshCycle = 6000;
        approachingWindowTime = 72;
        elapsedRefreshCycle = 300;
        imminentRefreshCycle = 600;
        imminentWindowTime = 24;
        initialRefreshCycle = 18000;
        maxRandomDelayInSeconds = 1200;
        noTimers = 0;
        nudgeRefreshCycle = 60;
        randomDelay = 0;
    }; 
```
Im assuming that this is the expected behaviour - https://github.com/macadmins/nudge/wiki/userExperience

**Comment by erikng** [comment]
I'm not sure I understand the issue you are describing. What exactly is nudge not doing that you want it to do?

**Comment by erikng** [comment]
In this case no. That key is for when the nudge event has passed. In your case you have 9 days remaining before that key is triggered.

**Comment by erikng** [comment]
It's very likely it's the initialRefreshCycle key in this particular time.
