### ISSUE TITLE
Feature Request: hours:minutes remaining

### ISSUE THREAD

**Issue by dpertschi** [macadmins/nudge#318]
I'm thinking it would be super helpful if _Days Remaining To Update_ changed to _**Hours** Remaining To Update_ on the last day. 
Bonus joy if that text changed to red too.

Users-be-Users and many will wait until the last day and be wanting to know when exactly.
This will also help CYA with management to be able to say "we told them when right up to the minute".

**Comment by erikng** [comment]
I like the idea but it would take everyone to localize the new text (maybe easier than I think) for this behavior.

**Comment by securitygeneration** [comment]
That should be pretty easy. I've got French and German if you need.

**Comment by erikng** [comment]
Will be in the next version of Nudge
