### ISSUE TITLE
Feature Request: Include actionButtonPath Key in the osVersionRequirements Array

### ISSUE THREAD

**Issue by miawri** [macadmins/nudge#319]
We currently handle major OS upgrades using munki and the actionButtonPath key which is great.

What would be even better if this info could be provided in the osVersionRequirements key so that major upgrades can be directed to MSC (or Jamf) and minor OS updates go to the default Software Update System Preferences pane.  This would mean we could use the same profile to manage both major OS upgrades and minor OS updates.

Example xml: -

```
key>osVersionRequirements</key>
<array>
  <dict>
    <key>aboutUpdateURL</key>
    <string>https://www.apple.com/macos/monterey/</string>
    <key>requiredInstallationDate</key>
    <date>2022-03-15T00:00:00Z</date>
    <key>requiredMinimumOSVersion</key>
    <string>12.2.1</string>
    <key>targetedOSVersionsRule</key>
    <string>11</string>
    <key>actionButtonPath</key>
     <string>munki://updates</string>
  </dict>
  <dict>
    <key>aboutUpdateURL</key>
    <string>https://support.apple.com/en-us/HT212586</string>
    <key>requiredInstallationDate</key>
    <date>2022-02-27T00:00:00Z</date>
    <key>requiredMinimumOSVersion</key>
    <string>12.2.1</string>
    <key>targetedOSVersionsRule</key>
    <string>12.0.1</string>
  </dict>
</array>
```

**Comment by erikng** [comment]
This is a great enhancement.

**Comment by erikng** [comment]
The next version of Nudge will have this functionality.

**Comment by miawri** [comment]
Excellent news!

Thanks for sorting so quickly, Erik.
