### ISSUE TITLE
Question: Does Nudge check for free space?

### ISSUE THREAD

**Issue by shoopdawoop** [macadmins/nudge#324]
Sorry I did not just test this myself ... does Nudge check for free space on the boot volume to make sure that an update/upgrade can actually be installed before it goes into enforcer mode?

Ideally, imo, in case of insufficient free space users would be reminded to do some spring cleaning until the install can be performed.

**Comment by shoopdawoop** [comment]
Good point. Maybe a simple way to do this would be good enough, e.g. something like a

```
"minFreeSize": "15G",
"minFreeSizeSkipEnforce": "true"
```

in `com.github.macadmins.Nudge.json` that, if present, would prevent enforced mode (e.g. by setting `allowedDeferrals` to a high value)?

This way admins could set a general threshold for free space in order to prevent a major headache in exchange for a minor one, thus allowing the few messy users to keep working if they happen to run out of space.

The alternative, of course, would be to never enter enforced mode at all.

**Comment by bradtchapman** [comment]
@erikng : Issue #492 was closed as a dupe, and it sounds like you're unlikely to implement it.

**Comment by erikng** [comment]
I've decided against trying to do this. The gdmf and sofa feeds do not provide this type of data and given that apple has moved to "minor" release style updates for major upgrades, I'm more interested in account for those types of issues than space.

I'd encourage you to just add "spring cleaning" to your main text if/when a user hits this issue.
