### ISSUE TITLE
Feature Request: Allow for the Scenario where requiredInstallationDate for a Newly Issued Machine

### ISSUE THREAD

**Issue by miawri** [macadmins/nudge#328]
Scenario: Machine is built out of the box with 12.2.0 as the base OS from Apple.  12.2.1 has already been released and and the requiredInstallationDate is in two days time.  Nudge behaves as it does and will start getting more agressive even thought the (possibly new) end user has only just started to see the prompts.  This is a bad experience for this person.

Proposal: to alleviate this scenario, Nudge checks for either firstLoginDate or buildDate of a machine and its proximity to requiredInstallationDate and changes its behaviour from the norm.

Example scenario 1 - requiredInstallationDate has passed: 
if firstLoginDate (or buildDate) >= requiredInstallationDate then newRequiredInstallationDate = firstLoginDate + newBuildGracePeriod

Example Scenario 2 - firstLoginDate is within approachingWindowTime:
if firstLoginDate (or buildDate) is >= (requiredInstallationDate - approachingWindowTime) then newRequiredInstallationDate = RequiredInstallationDate + newBuildGracePeriod

The newBuildGrace Period would be the amount of days the admin allows for the new user to install the update specified in osVersionRequirements.

Getting the firstLoginDate would seem to be the best measure to use but may be difficult to get accurately?  buildDate may be easier to assume but might not be too useful if machines have been prebuilt and stored.

**Comment by erikng** [comment]
https://github.com/macadmins/nudge/commit/c7a9ccc4844d9d353f8d0506cd34257109c84922 some preliminary stuff on this.

It will likely be several new keys to get this to work in a flexible way.

**Comment by erikng** [comment]
- `intialGracePeriodLaunchHours` useful to not show Nudge during the provisioning process itself
- `intialGracePeriodPath` can be customized if you want to look for some custom path in your provisioning process
- `initialGracePeriodExtensionHours` for the extended requiredInstallationDate
- `allowInitialGracePeriod` for turning it off and on

I think it should be in `osVersionRequirements` so you can tailor this per OS update in the event that a vulnerability is too critical to not give the user a poor UX.

**Comment by erikng** [comment]
hey @miawri I've thought about this a lot and I no longer agree with changing the required install date for both scenarios. Only one real scenario exists. Please see https://github.com/macadmins/nudge/pull/330 for conversation of this topic.

**Comment by miawri** [comment]
Thanks Erik, you’re right.

That all makes sense to me.

**Comment by erikng** [comment]
Closing as it will be available in the next pre release of nudge for testing.
