### ISSUE TITLE
Upgrading from Big Sur to Monterey

### ISSUE THREAD

**Issue by rgbpi** [macadmins/nudge#329]
2 Macs on Big Sur 11.6.4
wanting to upgrade to Monterey 12.2.1
Nudge ver 1.1.5.81289
Both Macs download Monterey, seems to start installing but then fails and bring Macs back to the Big Sur login window.
Nudge Logger says "Nudge detected an attempt to close the application" at about the same time as the failure (but cant be certain it's linked to the same event)
Tried multiple times on 2 Macs, fails every time.

**Comment by erikng** [comment]
This sounds like an issue with the apple installer. Please ask on the macadmins slack #nudge channel
