### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by neotruthz** [macadmins/nudge#331]
This is is a bit of a silly one, but it would really help us out. 

Is there any way to make the "Update Now" button be below the instructions? Like a normal order of operations, top to bottom?

We have specific instructions, which is what the space below is for, that should be read **_before_** pressing that button, but our clients keep just pushing it because "Well it's right there at the top!". Hard to blame them... 

I know it seems like a silly thing from your perspective, but from a UX/usage angle, it would be really helpful to put the action **_after_** the instructions. 

Thank you!!!

**Comment by erikng** [comment]
I have no plans to do this. Sorry.
