### ISSUE TITLE
Jamf Configuration Profile Text Issue

### ISSUE THREAD

**Issue by a-punsal** [macadmins/nudge#333]
Hi,

We're deploying Nudge Preferences through a Jamf Configuration Profile(Application & Custom Settings>External Applications). From their we use the example JSON and Jamf lets us edit the attributes via forms. Everything seems to be pushing and working fine except whenever we try to update any of the text fields. For example, maincontenttext never updates when we edit in the Configuration Profile but if we update the minimumoperatingsystem or requiredinstalldate those show up fine in the Nudge Application. Anything we're doing wrong here?

**Comment by ljcacioppo** [comment]
I have seen this behavior if the language is not set. Do you know if you have the _language key set in the Update Elements section?

**Comment by a-punsal** [comment]
> I have seen this behavior if the language is not set. Do you know if you have the _language key set in the Update Elements section?

That was it! Thanks so much for letting me know! Maybe that should be updated in the Wiki somewhere? Although I do not think there was a Jamf specific section anywhere.

**Comment by erikng** [comment]
It's been documented for about 5 months

https://github.com/macadmins/nudge/wiki/Common-Issues#help-my-paragraph-and-text-changes-are-not-showing-up-in-the-ui

**Comment by a-punsal** [comment]
> It's been documented for about 5 months
> 
> https://github.com/macadmins/nudge/wiki/Common-Issues#help-my-paragraph-and-text-changes-are-not-showing-up-in-the-ui

My apologies. Thanks Erik!
