### ISSUE TITLE
Deferral Button and language 

### ISSUE THREAD

**Issue by Lou9MX3** [macadmins/nudge#336]
I’ve configured the deferral button on my configuration profile on JAMF. I saw the issue #204 and I tried to customized as it was mentioned, it didn’t work. 
 
I’ve configured the language to French but it rolls back to english all the time. Is there any thing that I can do ?

I will leave attached the screenshots of these parameters and my configuration profile. 
![Screen Shot 2022-03-15 at 2 52 01 PM](https://user-images.githubusercontent.com/99039427/158450549-7e343982-9d9b-4ea0-8e2a-2117957c69ca.png)
![Screen Shot 2022-03-15 at 2 51 48 PM](https://user-images.githubusercontent.com/99039427/158450553-b4813fa2-4187-447b-84bb-56d8d3b823c2.png)
![Screen Shot 2022-03-15 at 2 51 29 PM](https://user-images.githubusercontent.com/99039427/158450555-10156318-eafd-4f23-b217-a374134fb513.png)
![Screen Shot 2022-03-15 at 2 51 16 PM](https://user-images.githubusercontent.com/99039427/158450557-fb8ed91f-890e-467a-bebc-4001e68a2bfe.png)
![Screen Shot 2022-03-15 at 2 50 59 PM](https://user-images.githubusercontent.com/99039427/158450559-3ee468bb-34da-4dd1-9f60-a7cf654807fb.png)
<img width="887" alt="Screen Shot 2022-03-15 at 2 48 35 PM" src="https://user-images.githubusercontent.com/99039427/158450561-7839fd50-78ce-4a6b-91c3-78c64108ffa9.png">

**Comment by erikng** [comment]
That's because days remaining is zero. That is the expected behavior. Please read the wiki for more information on how Nudge operates.
