### ISSUE TITLE
"See the Wiki for information on adding line breaks."

### ISSUE THREAD

**Issue by AndersBNielsen** [macadmins/nudge#337]
The Jamf schema says "See the Wiki for information on adding line breaks." for mainContentText - but there's absolutely nothing in the wiki about line breaks(unless I can't find it?)

Edit: 1.1.6 fixes line breaks. \n works

**Comment by dan-snelson** [comment]
@AndersBNielsen Please see the following:
https://github.com/macadmins/nudge/wiki/updateElements#maincontenttext---type-string-default-value-
