### ISSUE TITLE
Nudge - Jamf

### ISSUE THREAD

**Issue by rossoneris** [macadmins/nudge#339]
I don´t know if this is a jamf or nudge mobile config issue. 
But I try to deploy the default mobileconfig file from the wiki - but jamf everytime is unable to push out the profile and only shows the following error

<Exception> -[__NSCFConstantString objectForKey:]: unrecognized selector sent to instance 0x1f8158608

**Comment by erikng** [comment]
Please do that and if you're still having trouble come to the nudge slack channel. I do not use JAMF and others help support.
