### ISSUE TITLE
add "UMAD" functionality

### ISSUE THREAD

**Issue by erikng** [macadmins/nudge#34]
Nudge and UMAD are the same but similar. Rather than make two tools, it would be nice if nudge could just be a universal tool.

**Comment by erikng** [comment]
After thinking about it, UMAD-swift, if ever built, will be a separate project.

**Comment by erikng** [comment]
Talked to @rorymurdock and we may in fact want to build this in.

**Comment by erikng** [comment]
@rorymurdock no excuses now. This is the second time you want to work on it.

**Comment by bradtchapman** [comment]
@erikng @rorymurdock knock knock... a dead issue is calling...
