### ISSUE TITLE
What is the best way to exclude a group of users / department from the deadline date?

### ISSUE THREAD

**Issue by romnation1** [macadmins/nudge#341]
Lets say we have a specific group of users that have software that is incompatible with X software. What is the best practice way to exclude this group of users from update deadline temporarily?

**Comment by erikng** [comment]
You can deploy different jsons to those employees or mdm profiles. 

Only you know your fleet and this would be a common problem for deploying specific versions of software to those machines as well. 

Given that this is more of a deployment strategy with nudge and not an actual issue (I won't be able to fix this strategy for you in code) I will be closing this. 

If you want to discuss with other peers, please join the macadmins slack.
