### ISSUE TITLE
Does the "Collect available software updates" option in Jamf under Settings -> Computer Mgmt > Inventory Collection need to be enabled for Nudge to function properly?

### ISSUE THREAD

**Issue by romnation1** [macadmins/nudge#342]
Jamf support recently had us disable this option due to it causing machines to stop updating their jamf inventory. (We had machines that hadnt updated inventory for months) Is this option necessary to have enabled for Nudge to function?

**Comment by colorenz** [comment]
No it is not necessary for nudge. Nudge works with every MDM and did not relay on the collected Softwareupdates from Jamf or any mdm.

**Comment by aysiu** [comment]
Nudge also works with **no** MDM, as long as the .json is in the right place.
