### ISSUE TITLE
QA: Looking for a Nudge equivalent for iOS 

### ISSUE THREAD

**Issue by rvtkruys-valtech** [macadmins/nudge#345]
Hi,

I know this is not related to this awesome tool. But I was wondering if there is a similar solution for iOS devices. We are managing iOS devices using Jamf Pro and was hoping that there is a similar tool like Nudge.

Again, awesome work on Nudge.

with regards,
Roland

**Comment by erikng** [comment]
Not that I know of. It would require a lot of work directly within the MDM (single all mode) to be aggressive with the user.
