### ISSUE TITLE
danish localization request

### ISSUE THREAD

**Issue by erikng** [macadmins/nudge#347]
[da.lproj.zip](https://github.com/macadmins/nudge/files/8543938/da.lproj.zip)

**Comment by ttv-kglakademi-dk** [comment]
I've reviewed the Danish translation and it looks ok to me. It's very close (approx. 90% identical) to my own Danish translation I made for a local build of Nudge. The differences are insignificant.

**Comment by erikng** [comment]
https://github.com/macadmins/nudge/commit/f6c69dba85d9814bde150621590d4ecf8f20a9c2

Now in development branch
