### ISSUE TITLE
Unable to display custom icon

### ISSUE THREAD

**Issue by rvtkruys-valtech** [macadmins/nudge#348]
Hi,

I've configured the iconlightPath and iconDarkPath with a custom .png file. But it does not appear and is displaying the Apple logo in stead.

Are there any requirements for using a custom icon?

**Comment by colorenz** [comment]
Is the custom item readable for the user? Where is the icon stored?

**Comment by rvtkruys-valtech** [comment]
> Is the custom item readable for the user? Where is the icon stored?

Yes, it is readable. it is located in /Users/Shared andhas the .png extension.

**Comment by macsimom** [comment]
@rvtkruys-valtech have you properly embedded the `iconlightPath` [sic] and `iconDarkPath` keys in the `userInterface` dictionary?

**Comment by rvtkruys-valtech** [comment]
I am using Jamf Pro to configure this. Please, where can I find info regarding the `userInterface` dictionary?

**Comment by erikng** [comment]
Please come to the macadmin slack channel and get help. The GitHub is for issues with the product itself and not with your deployment.
