### ISSUE TITLE
Duplicate "actionButtonPath" key

### ISSUE THREAD

**Issue by rx7FD** [macadmins/nudge#349]
Hello,
Pardon for my ignorance as I am just learning and applying the Nudge tool. This is not so much of a issue but more or so a question. In the Json file the key for "ActionButtonPath" is visible twice once under the "OSVersion Requirements" and second under UserExperience. I am wondering if both have a function because I am discovering that only one of them actually makes changes when typing in a different path other than the default one. Any input would be greatly appreciated. 

 "actionButtonPath": "munki://updates",    <--------------------------------------------(THIS)
      "majorUpgradeAppPath": "/Applications/Install macOS Big Sur.app",
      "requiredInstallationDate": "2021-08-28T00:00:00Z",
      "requiredMinimumOSVersion": "11.5.2",
      "targetedOSVersionsRule": "default"

  "userInterface": {
    "actionButtonPath": "munki://updates",  <-----------------------------------------(Here)
    "fallbackLanguage": "en",
    "forceFallbackLanguage": false,
    "forceScreenShotIcon": false,
    "iconDarkPath": "/somewhere/logoDark.png",
    "iconLightPath": "/somewhere/logoLight.png",
    "screenShotDarkPath": "/somewhere/screenShotDark.png",
    "screenShotLightPath": "/somewhere/screenShotLight.png",
    "showDeferralCount": true,
    "simpleMode": false,
    "singleQuitButton": false,
    "updateElements": [

**Comment by pro4tlzz** [comment]
This is intentional https://github.com/macadmins/nudge/pull/321 

For help on your issue you can come to the MacAdmins slack Channel
