### ISSUE TITLE
Nudge can be moved / hidden on another 'desktop' when Spaces is used.

### ISSUE THREAD

**Issue by WFHSam** [macadmins/nudge#350]
When testing our initial deployment of Nudge, we found that we were able to “move” the Nudge window to another Desktop in Spaces.  When Nudge is active again, it pulls focus to the Space where Nudge is visible (e.g. Desktop 2).   The Nudge logs don't indicate that the app is in another space or if the user moved it to try and hide it.

Steps to reproduce:

- Wait for Nudge to appear, or launch manually. 
- Use three fingers to invoke Mission Control / Expose.
- At the top of the screen, look for the desktop thumbnails.
- If there is only one desktop, click the (+) button (top right) to add a new one.
- Drag the Nudge window to the newly created Desktop Space.

A sanitized screenshot has been added.  A screen recording was captured, but I'm not able to sanitize it at this time.

![Screen Shot 2022-04-26 at 10 37 46 AM](https://user-images.githubusercontent.com/104452915/165359778-d2e17667-2ef2-420b-8a73-426782108bce.png)

**Comment by WFHSam** [comment]
Should be there now. Had to replace it. It was the unsanitized version.

**Comment by Nothing4You** [comment]
fyi your unsanitized screenshot is still in edit history.

see https://docs.github.com/en/communities/moderating-comments-and-conversations/tracking-changes-in-a-comment#deleting-sensitive-information-from-a-comments-history

**Comment by WFHSam** [comment]
Thank you @Nothing4You . The history can't be accessed for the issue, so I have opened a case for that.

**Comment by erikng** [comment]
Will be fixed with https://github.com/macadmins/nudge/commit/5487cd8271d9764f654ea5017ac5a86204850b78
