### ISSUE TITLE
aggressiveUserExperience

### ISSUE THREAD

**Issue by milhinojosa** [macadmins/nudge#354]
Hi, we are currently trying to enable the aggressiveUserExperience but it is not locking the Nudge app in Monterey. This are the settings we currently have, any suggestions? 

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>optionalFeatures</key>
    <dict>
      <key>acceptableApplicationBundleIDs</key>
      <array>
        <string>us.zoom.xos</string>
      </array>
      <key>aggressiveUserExperience</key>
      <true/>
      <key>asynchronousSoftwareUpdate</key>
      <false/>
      <key>attemptToFetchMajorUpgrade</key>
      <true/>
      <key>enforceMinorUpdates</key>
      <true/>
      <key>disableSoftwareUpdateWorkflow</key>
      <true/>
    </dict>
    <key>osVersionRequirements</key>
    <array>
      <dict>
        <key>majorUpgradeAppPath</key>
        <string>/Applications/Install macOS Monterey.app</string>
        <key>requiredInstallationDate</key>
        <string>2022-05-13T18:00:00Z</string>
        <key>requiredMinimumOSVersion</key>
        <string>12.3.1</string>
        <key>targetedOSVersionsRule</key>
        <string>default</string>
      </dict>
    </array>
    <key>userExperience</key>
    <dict>
      <key>allowGracePeriods</key>
      <false/>
      <key>allowUserQuitDeferrals</key>
      <true/>
      <key>allowedDeferrals</key>
      <integer>1</integer>
      <key>allowedDeferralsUntilForcedSecondaryQuitButton</key>
      <integer>14</integer>
      <key>approachingRefreshCycle</key>
      <integer>60</integer>
      <key>approachingWindowTime</key>
      <integer>72</integer>
      <key>elapsedRefreshCycle</key>
      <integer>15</integer>
      <key>gracePeriodInstallDelay</key>
      <integer>24</integer>
      <key>gracePeriodLaunchDelay</key>
      <integer>1</integer>
      <key>gracePeriodPath</key>
      <string>/private/var/bd/.AppleSetupDone</string>
      <key>imminentRefreshCycle</key>
      <integer>30</integer>
      <key>imminentWindowTime</key>
      <integer>24</integer>
      <key>initialRefreshCycle</key>
      <integer>600</integer>
      <key>maxRandomDelayInSeconds</key>
      <integer>1200</integer>
      <key>noTimers</key>
      <false/>
      <key>nudgeRefreshCycle</key>
      <integer>60</integer>
      <key>randomDelay</key>
      <false/>
    </dict>
    <key>userInterface</key>
    <dict>
      <key>fallbackLanguage</key>
      <string/>
      <key>forceFallbackLanguage</key>
      <false/>
      <key>forceScreenShotIcon</key>
      <false/>
      <key>iconDarkPath</key>
      <string>/System/Library/PreferencePanes/SoftwareUpdate.prefPane/Contents/Resources/SoftwareUpdate.icns</string>
      <key>iconLightPath</key>
      <string>/System/Library/PreferencePanes/SoftwareUpdate.prefPane/Contents/Resources/SoftwareUpdate.icns</string>
      <key>showDeferralCount</key>
      <true/>
      <key>simpleMode</key>
      <false/>
      <key>singleQuitButton</key>
      <false/>
    </dict>
  </dict>
</plist>

**Comment by erikng** [comment]
Please ask on the slack macadmins group #nudge 

I don't know what "lock" means in this case but it sounds like an issue with your settings and not with Nudge. The GitHub is for software issues, not user level support.
