### ISSUE TITLE
Broken remaining days logic when calendar is not Gregorian 

### ISSUE THREAD

**Issue by tonystonksbeta** [macadmins/nudge#358]
![Screen Shot 2022-05-19 at 14 02 53](https://user-images.githubusercontent.com/4642672/169252672-14d31a54-6ac4-4cc4-b645-2e58c0fdbc6c.png)

When I was testing with scenario I found out the if the user is using another calendar besides Gregorian the remaining days become incorrect. 

Is there another way to have fixed calendar type (gregorian) in configuration profile in json scheme ?

Note: the screenshot is showing the user using Buddhist calendar.
Thank you,

**Comment by erikng** [comment]
I believe I have fixed it with https://github.com/macadmins/nudge/commit/a34540f681728e7dfb8665dd79e945f0b933ca98.

It is an incredibly complex issue. If it is not resolved in the next 1.1.7 beta, it will not be fixed for the 1.1.7 release.

I have tested all calendars on my machine, but kept english as my localization. Based on your screenshots, the user is in the same configuration.

**Comment by erikng** [comment]
https://github.com/macadmins/nudge/releases/tag/v1.1.7.81373

**Comment by erikng** [comment]
I don't honestly know at this point. It's a difficult issue to solve and I don't currently have the intention to work on it.

Apple does not have a stable API for this and by knowing little about non Gregorian calendars and how those people setup their machines I don't really know where to start in addressing it.
