### ISSUE TITLE
Feature Request: Nudge Package with LA and Logger

### ISSUE THREAD

**Issue by colorenz** [macadmins/nudge#363]
Hey is it possible to create a .pkg to rule them all😁 and include the LA and the Logger in the nudge installation?

So it’s esaily for new macadmins to deploy nudge.

Best Regards

**Comment by erikng** [comment]
maybe.

**Comment by erikng** [comment]
don't think it will make it for the 1.1.7 release

**Comment by erikng** [comment]
https://github.com/macadmins/nudge/releases/tag/v1.1.7.81388

**Comment by dan-snelson** [comment]
Nudge _Ssssswwweeeettttt_
