### ISSUE TITLE
Dutch Localization issue

### ISSUE THREAD

**Issue by peterlbk** [macadmins/nudge#364]
The defer variable in Dutch is now "Verschuiven" is a too large word to fit on the menu. It also actually means to slide.

My suggestion is to call it "Stel uit", which is really the translation of defer.
![Screenshot 2022-05-25 at 14 56 02](https://user-images.githubusercontent.com/14951807/170267365-9dd573d2-2453-486a-b555-4b5bb295f8e3.png)
![Screenshot 2022-05-25 at 14 57 29](https://user-images.githubusercontent.com/14951807/170267369-9b3ae39c-5d6e-4fce-8130-198fe87cd74c.png)

**Comment by erikng** [comment]
done https://github.com/macadmins/nudge/commit/43da836f8434d7e26b4cd478dd6c16bcf815f968
