### ISSUE TITLE
`customDeferralDropdownText` string is truncated

### ISSUE THREAD

**Issue by dan-snelson** [macadmins/nudge#368]
In Nudge `1.1.7.81411`, the `customDeferralDropdownText` is truncated on longer strings; the menu options seem to accommodate longer strings.

```
"updateElements": [
        {
            "_language": "en",
            "actionButtonText": "actionButtonText",
            "customDeferralButtonText": "customDeferralButtonText",
            "customDeferralDropdownText": "customDeferralDropdownText",
            "informationButtonText": "informationButtonText",
            "mainContentHeader": "mainContentHeader",
            "mainContentNote": "mainContentNote",
            "mainContentSubHeader": "mainContentSubHeader",
            "mainContentText": "mainContentText \n\nTo perform the update now, click \"actionButtonText,\" review the on-screen instructions by clicking \"More Info…\" then click \"Update Now.\" (Click screenshot below.)\n\nIf you are unable to perform this update now, click \"primaryQuitButtonText\" (which will no longer be visible once the ${deadline} deadline has passed).",
            "mainHeader": "mainHeader",
            "oneDayDeferralButtonText": "oneDayDeferralButtonText",
            "oneHourDeferralButtonText": "oneHourDeferralButtonText",
            "primaryQuitButtonText": "primaryQuitButtonText",
            "secondaryQuitButtonText": "secondaryQuitButtonText",
            "subHeader": "subHeader"
        }
```
<img width="1012" alt="Screen Shot 2022-06-03 at 10 23 26 AM" src="https://user-images.githubusercontent.com/24623109/171907475-48f4c5c9-19f1-4532-a0b8-ed5b3346ee3d.png">

<img width="242" alt="Screen Shot 2022-06-03 at 10 23 34 AM" src="https://user-images.githubusercontent.com/24623109/171907526-b896edfe-d190-4ffa-8f95-d74345e9d32d.png">

**Comment by erikng** [comment]
I tried really hard to fix this when I made it a new optional key and after about 6 hours gave up.

If someone else wants to try to fix it, please do. I'm out of ideas.

**Comment by dan-snelson** [comment]
Thanks for all your efforts, @erikng.

**Comment by erikng** [comment]
fixed with https://github.com/macadmins/nudge/commit/4c34fcd268d7bc77ae43fcc732dfd07451daffd4
