### ISSUE TITLE
Add `Command-Option-M` as a banned key combination

### ISSUE THREAD

**Issue by dan-snelson** [macadmins/nudge#369]
Confirming that Nudge `1.1.7.81411` does block **Command-M** per #351.

However, **Command-Option-M** still works to minimize all windows of the front app.

**Comment by dan-snelson** [comment]
(And it's especially fun when `aggressiveUserFullScreenExperience` is enabled past the deadline and the user minimizes Nudge.)

**Comment by erikng** [comment]
What happens?

**Comment by erikng** [comment]
Guessing it's just a blur window?

**Comment by dan-snelson** [comment]
Correct; serves 'em right …

… Bbbbbuuuuwwwwahahahaha!!!

**Comment by erikng** [comment]
Fixed with https://github.com/macadmins/nudge/commit/6b36a7d2181feac8bc4e01af8673ecf78c2efbb0
