### ISSUE TITLE
acceptableScreenSharingUsage does not see MS Teams screen share

### ISSUE THREAD

**Issue by swy** [macadmins/nudge#371]
Steps to replicate:

-Nudge on a device running < desired OS version, before installation deadline
-Configured with `acceptableScreenSharingUsage` set to `True`
-Share device screen into MS Teams meeting
-run  `log show --style syslog  --predicate 'subsystem == "com.apple.donotdisturb" && eventMessage CONTAINS "isScreenShared"'`

Expected behavior: `isScreenShared=1` would be seen in the log output, and that a device would not be Nuged to update during a Teams screen share.
Observed behavior: `isScreenShared=0` is seen, and Nudges will be presented during a screen sharing session.

For comparison, the same test was done but sharing via Zoom.  In that situation, the log output is `isScreenShared=1`

While the failure to set the `isScreenShared` value seems to be a Teams shortcoming, this will lead to unexpected results for Nudge installations.  Perhaps an alternate way to ask "is Teams sharing the screen?" could be created.

**Comment by erikng** [comment]
I don't have any intentions of writing app specific code as it will continue to be a challenge. Can you try the acceptableAssertionUsage and see if teams works with that? That was written as a potential mitigation for badly behaving applications. 

I would also file a bug report with Microsoft.

**Comment by Nothing4You** [comment]
`PreventUserIdleDisplaySleep` assertion should work, although I haven't tested with nudge directly, via `pmset -g assertions` I can see this being set by teams when starting a screen share:

```
2022-06-10 11:35:54 +0200
Assertion status system-wide:
[...]
   PreventUserIdleDisplaySleep    1
[...]
Listed by owning process:
   pid 000(Teams): [0x0000] 00:00:08 NoDisplaySleepAssertion named: "Electron"
[...]
```

**Comment by gsprague** [comment]
@Nothing4You Yes, but PreventUserIdleDisplaySleep is set to 1 if you are just in a Teams meeting and not sharing your screen.

**Comment by gsprague** [comment]
With acceptableAssertionUsage true and acceptableAssertionApplicationNames set to "Electron" when Nudge is activated it will keep the Nudge window in the background. However, 1 minute later the Nudge window becomes the front most window. This is prior to the install date as well.

**Comment by bradtchapman** [comment]
@swy : is this still broken, or have newer versions of Nudge worked with your setup?  What about the behavior with the new version of Teams?
