### ISSUE TITLE
Background blur can be bypassed

### ISSUE THREAD

**Issue by sjurlohne** [macadmins/nudge#372]
The background blur can be temporarily bypassed by clicking Update Device. This will bring System Preferences (Software Update) to the front and background blur will go away until next time Nudge activates. Even if allowedDeferrals and requiredInstallationDate has passed.

**Comment by colorenz** [comment]
That is correct. Otherwise you can't do anything in the System Preferences. How else should it be? Should the blurred effect be all the time?

**Comment by erikng** [comment]
That is how it was designed.
