### ISSUE TITLE
Feature request: Persistant background blur

### ISSUE THREAD

**Issue by sjurlohne** [macadmins/nudge#373]
The background blur can be temporarily bypassed by clicking Update Device. This will bring System Preferences (Software Update) to the front and background blur will go away until next time Nudge activates.

I suggest that the blur should be persistant after allowedDeferrals and/or requiredInstallationDate has passed, only allowing for Software Update to be opened.

**Comment by bartreardon** [comment]
I don't know if this is technically possible. You're asking an application to both take up the full screen and blur the contents of everything else with the exception of system preferences. That's not really how it works. 

The temporary nature of the blurred background is how it's designed to work. You're not "bypassing" the blurred window, it's literally written to make the blur portion go away when you click the button. The point is to grab the full attention of the user with an increasing level of encouragements to perform updates, not lock them out of the system which is what you're asking for.

**Comment by securitygeneration** [comment]
One way to potentially solve this is to track the frontmost app. If it's not system preferences, bring nudge back to the forefront (with blur). The user can then click the button to be redirected back to System Preferences. If they try to 'escape' again, then rinse and repeat. But this is pretty aggressive. If for whatever reason SU doesn't show an update (which seems to be _du jour_ at the moment), then the user would have no way to get to email/Slack to contact support.

**Comment by sjurlohne** [comment]
@securitygeneration 
You make a valid point indeed :) In fact I think it invalidates my feature request as long as SU is as bad as it is.

**Comment by colorenz** [comment]
Maybe you can use one of the other methods to get the attention from the User. You can block and terminate applications with nudge😅.
