### ISSUE TITLE
Option to enforce Updates via MDM Commands

### ISSUE THREAD

**Issue by jshirle2** [macadmins/nudge#374]
I love the recently added feature to block certain applications from launching, etc. if users are past their deadline. Ultimately, though, this might create more friction between our staff and IT. I would rather just have the update force install via the MDM command. Any way this could be configured within Nudge? I had a lengthy script doing this pre-Big Sur and would love to get that level of control back. 

Thanks!

**Comment by dan-snelson** [comment]
If your MDM supports it, [actionButtonPath](https://github.com/macadmins/nudge/wiki/osVersionRequirements#actionbuttonpath---type-string-default-value-nil) may meet your needs.
