### ISSUE TITLE
"default" targetedOSVersionsRule is Ignored/Overwritten when there's multiple osVersionRequirements, unless it's the last in the osVersionRequirement array

### ISSUE THREAD

**Issue by samuelzamvil** [macadmins/nudge#377]
Issue
Computers ignore the "default" targetedOSVersionsRule when there's multiple indices in the requiredInstallationDate array, unless the default is the last indices.

The issue stems from a conditional statment in a for loop in the getOSVersionRequirementsProfile/getOSVersionRequirementsJSON functions which overwrite the default value after being set.

Solution
Add a boolean variable which indicates if the default value is present and do not allow it to be overwritten by the lack of a default value.

Steps to reproduce

Using the following osVersionRequirement xml array results in a Big Sur machine under 11.6 being Nudged to 12.4
```
        <key>osVersionRequirements</key>
          <array>
            <dict>
              <key>requiredInstallationDate</key>
              <date>2022-07-12T00:00:00Z</date>
              <key>requiredMinimumOSVersion</key>
              <string>11.6.6</string>
              <key>targetedOSVersionsRule</key>
              <string>default</string>
              <key>aboutUpdateURL</key>
              <string></string>
              <key>majorUpgradeAppPath</key>
              <string>/Applications/Install macOS Big Sur.app</string>
            </dict>
            <dict>
              <key>requiredInstallationDate</key>
              <date>2022-07-12T00:00:00Z</date>
              <key>requiredMinimumOSVersion</key>
              <string>12.4</string>
              <key>targetedOSVersionsRule</key>
              <string>12</string>
              <key>aboutUpdateURL</key>
              <string></string>
              <key>majorUpgradeAppPath</key>
              <string>/Applications/Install macOS Monterey.app</string>
            </dict>
          </array>
```

**Comment by erikng** [comment]
I see your PR, but why not just move it to the bottom? I'm not sure I like the var option as it now means there's no more `else` as a catchall.

**Comment by samuelzamvil** [comment]
I think moving things to the bottom is not very intuitive from an end users perspective and I think will cause more questions/issues when Big Sur is no longer supported. I didn't realize that was the behavior until I dug through the Nudge codebase and I spend quite a bit of time understanding Nudge before going forward with my own implementation.

As far as the removing the else as a catch all, it's actually still there since the additional variable is set to false on instantiation, so unless "default" is present, the last osVersionRequirements index will be set as default.

If you decide not to go with the additional variable, I the default behavior should be denoted somewhere in the documentation and if it already is there I didn't find it before I started my implementation.

**Comment by samuelzamvil** [comment]
I left a good reasoning behind why, I was expecting the behavior to work in a specific way, in the macadmins slack [here](https://macadmins.slack.com/archives/CDUU7DJQ2/p1655843808493749?thread_ts=1655830241.684429&cid=CDUU7DJQ2). This was before I had realized there was a workaround, which was to place the default config last.

> We'll be eventually be doing n-2 compliance and I was expecting to have 3 entries in osVersionRequirement. When Ventura drops the targeted versions being {default=n-2, n-1=12, n=13}, otherwise I'll be specifying a config for every new release of macOS indefinitely.
As an example of why this will be unwanted behavior; Let's say that macOS 16 drops and I am only supporting 14 and up. Every time there's an update to macOS 14 I am editing my minimum OS version for 11 12 13 and 14, instead I'd like to just have the default set to 14.X and any computer pre 14 will be Nudged to the default config.

**Comment by erikng** [comment]
Closing due to merge.
