### ISSUE TITLE
ActionButtonPath XML error

### ISSUE THREAD

**Issue by ericlouis** [macadmins/nudge#380]
Hi,
We are trying to use this option in Nudge <key>actionButtonPath</key  <string>[jamfselfservice://content?entity=<content_type>&id=<content_id>&action=execute</key>]
We followed exactly what was described in the wiki, but we keep getting an XML error when we try to save the configuration profile in Jamf.
Is it normal to have a string and a key in there, <string>[jamfselfservice://content?entity=<content_type>&id=<content_id>&action=execute</key>?] . We've tried to modify with string string, but no luck.
Need help with that please.

**Comment by ericlouis** [comment]
@dan-snelson  With a json, but mobile Configuration, which I should have mentioned. I'm suspecting, it may not work that way.

**Comment by dan-snelson** [comment]
Does the following apply to your use-case?

https://github.com/macadmins/nudge/wiki/Common-Issues#configuration-profile-set-for-nudge-to-use-a-json-file-but-the-json-configuration-isnt-being-applied

**Comment by ericlouis** [comment]
Dan, here you can see what's happening when we try to add  "<key>actionButtonPath</key>
<string>jamfselfservice://content?entity=<content_type>&id=<content_id>&action=execute</key>".
If we delete that entry, we can save without any problem.
 ![Capture d?eecran, le 20 22-07-14 aĚ 12 17 10](https://user-images.githubusercontent.com/53267310/178960922-2a77511a-8f30-4b26-8248-d90ee46c6db0.png)

**Comment by dan-snelson** [comment]
Try replacing `&` with `&amp;`

```
<key>actionButtonPath</key>
<string>jamfselfservice://content?entity=policy&amp;id=13&amp;action=view</string>
```

**Comment by ericlouis** [comment]
Dan, it seems to works now, I was able to save, with no XML error this time. 

Cheers.
