### ISSUE TITLE
Nudge not respecting requiredInstallationDate

### ISSUE THREAD

**Issue by rs1278** [macadmins/nudge#382]
My end-users were recently bombarded with an unintentionally aggressive Nudge recently. After rolling back the changes and doing some testing, I noticed that requiredInstallationDate wasn't being honored by Nudge, so it was behaving as aggressively as possible. The screenshots below illustrate this

<img width="1012" alt="Screen Shot 2022-07-27 at 9 14 59 AM" src="https://user-images.githubusercontent.com/92549755/181284709-57f84d02-7386-4fcb-b1a5-d461d9a70ade.png">
<img width="613" alt="Screen Shot 2022-07-27 at 9 16 24 AM" src="https://user-images.githubusercontent.com/92549755/181284749-269d9667-2bce-468b-91af-26d50a2acf8b.png">
<img width="436" alt="Screen Shot 2022-07-27 at 9 16 58 AM" src="https://user-images.githubusercontent.com/92549755/181284757-254e59e3-ac93-47f4-b387-728640a3a255.png">

**Comment by erikng** [comment]
This is a configuration issue and not a Nudge issue. Please go to the #nudge-jamf channel on the macadmins slack to figure out what is happening.

**Comment by erikng** [comment]
I'm pretty sure I know what your issue is. There should not be a `-` between the date and `T`

You have `2022-08-08-T00:00:00Z` which should be `2022-08-08T00:00:00Z`

See: https://github.com/macadmins/nudge/blob/main/Example%20Assets/com.github.macadmins.Nudge.mobileconfig#L88
