### ISSUE TITLE
MAC is Offline still getting that update your device 

### ISSUE THREAD

**Issue by mani2care** [macadmins/nudge#384]
MAC is Offline still getting that update your device 

when the mac is offline getting that UI to update the device 

for example mac having wifi or network issue for longer how this will work ? 
is there any validation to check this or block this UI ?

**Comment by erikng** [comment]
No there isn't.

**Comment by erikng** [comment]
I don't have plans on implementing this. There are machines and also states where the internet wouldn't be needed to install an update. It's too complicated to make a perfect state for this.
