### ISSUE TITLE
Feature Request: Allow 'branding' the Nudge window

### ISSUE THREAD

**Issue by jelockwood** [macadmins/nudge#387]
As this tool is most likely to be used in enterprise and education organisation it would be useful if it could be 'branded' to display a logo for that organisation.

I know from experience that otherwise - and even with branding still to some extent, users may initially be worried it is a hack rather than a genuine system.

Whilst different people may have different views about the amount of branding they would prefer, I would be happy at least as a starting point if the Apple logo could be (easily) replaced by a custom logo. It would seem the obvious way to do this would be to add an additional key to the mobileconfig/json allowing a file path to a logo file to be specified. If the key is configured and the file exists then Nudge would use this instead of the default Apple logo.

**Comment by Alitejawi** [comment]
This is already an existing feature, see `iconLightPath` and `iconDarkPath` from the the Jamf schema.

**Comment by colorenz** [comment]
Hi, check the  Userinterface customization https://github.com/macadmins/nudge/wiki/userInterface

**Comment by erikng** [comment]
Please read the wiki :)
