### ISSUE TITLE
Nudge preferences (OS version) "stuck" until restart

### ISSUE THREAD

**Issue by phlbnks** [macadmins/nudge#393]
I updated my Nudge preferences to 12.5.1 last week. Machines were still reading, from somewhere, 12.5 from previous version.

I tried various methods to fix including moving from plist to json, but the only thing that fixed it was a restart. 

Throughout the problem, `defaults read ~/Library/Preferences/com.github.macadmins.Nudge.plist` showed the old/incorrect 12.5 version, even after deleting it and changes in preferences file. Log always showed 12.5 in comparison output.

After a restart I can update the preferences and Nudge, including `defaults read ~/Library/Preferences/com.github.macadmins.Nudge.plist` accurately reflects the preferences file. 

Not sure if this is a Nudge of MacOS issue tbh.

**Comment by erikng** [comment]
why are you deploying the preferences to `~/Library/Preferences/com.github.macadmins.Nudge.plist` ? That is where nudge stores it's state values but the configuration should be `/Library/Preferences/com.github.macadmins.Nudge.plist` or `/Library/Managed Preferences/com.github.macadmins.Nudge.plist`

**Comment by phlbnks** [comment]
Perhaps that could have been more clear - my preferences _are_ stored in `/Library/` (`/Library/Preferences/com.github.macadmins.Nudge.json` In fact).
But even when “resetting” Nudge by deleting the state file in `~/Library`, it was being recreated with the same incorrect values somehow. Only after a machine restart did that state file get correct values, and Nudge obey the preferences file.

**Comment by erikng** [comment]
I'm not sure what was happening here, but if this was stuck, I would get a lot of feedback regarding this and would be a major bug. Nudge currently doesn't understand when changes are made via MDM without the relaunch of nudge https://github.com/macadmins/nudge/issues/370 but that is separate from this.

We extensively use the json and stop/start the agent and haven't seen this issue, so going to close for now.
