### ISSUE TITLE
Feature request: minimum notification period

### ISSUE THREAD

**Issue by aysiu** [macadmins/nudge#395]
It's possible employees may go on leave for an extended period of time, and then get hit with Nudge's aggressive mode when they get back (if that's after the deadline to install the macOS patch).

It'd be cool to have some kind of minimum notification... like you should have seen Nudge at least once before it gets all aggressive.

It would be in the spirit of [how Munki handles `force_install_after_date`](https://github.com/munki/munki/wiki/Pkginfo-Files#minimum-notification):
> If a machine is powered off or asleep while a force install is due to take place, it will start at 60 minutes worth of notifications. If the machine then is put asleep until that new 60-minute counter has been started, the machine will perform the force install within minutes of waking up.

**Comment by erikng** [comment]
Going to track this here https://github.com/macadmins/nudge/issues/438 since there is more communication about it.
