### ISSUE TITLE
Unable to replicate Nudge Suite pkg from primary JSS (LAN) to secondary FDP (DMZ)

### ISSUE THREAD

**Issue by dstranathan** [macadmins/nudge#399]
**Overview:**

I'm unable to replicate the Nudge Suite package (Nudge_Suite-1.1.8.81422.pkg) from my primary JSS (LAN) to my secondary FDP (DMZ). I’m on-prem running Jamf Pro 10.40.

**Details:**

I can upload the Nudge Suite package from my admin Mac to my primary JSS (LAN) fine, but when I attempt to replicate it to my File Distribution Point the process times out or crashes. 

I was able to reproduce this behavior from 3 different IT Macs (on 12.5.0 or 12.5.1) - all 3 had the same behavior. I tried it while on my LAN (Ethernet), over a Pulse Secure SSL VPN, and over a Meraki Z3 point-to-point WAN connection. Results were the same.

I tested other packages (such as O365, various utilities and apps), and they all upload and replicate fine. But Nudge Suite can't be replicated.

I downloaded Nudge Suite package again to make sure I didn’t get a corrupted pkg etc, but alas the downloaded package is fine.

I tore open the Nudge Suite package with Suspicious Package and I don’t see anything unusual about it (i.e. no nested meta-packages, etc)

**Workaround:**

My workaround is to simple: upload/replicate the Nudge app pkg, the Nudge LaunchAgent pkg and the Nudge Logger pkg as 3 discreet packages (and add all 3 pkgs to my Nudge install policy) rather than using a single monolithic pkg.

**Expected behavior:**

 I should be able to upload the Nudge Suite package to my primary JJS and then replicate it to my secondary JSS without any hangs or crashes

**Comment by erikng** [comment]
I have no idea how to replicate this or where to begin looking. Can you see if other JAMF admins have this issue in the JAMF nudge slack channel?

**Comment by dstranathan** [comment]
I just wanted to bring this to your attention in case others have experienced this. I haven't found anyone else to verify my experience (i.e. an on-prem Jamf org with multiple JSS DPs)
