### ISSUE TITLE
Allow user to choose time of next prompt.

### ISSUE THREAD

**Issue by groob** [macadmins/nudge#40]
In our environment we have users who care a lot about when they're expected to do something. I proposed the "update device" button changes to a dropdown with the following actions.

1. Update now (default).
2. Remind me in 1 hour. 
3. Remind me in a day.
4. Remind me at << pick date >>. 

In our internal implementation of nudge we already have the first three options and the fourth is the most highly requested. People don't like getting nagged during meetings and will also refuse to touch their system while they're oncall, which is understandable.

**Comment by abstertee** [comment]
Here is a solution we implemented for the deferral option:
![image](https://user-images.githubusercontent.com/35249045/107414221-8f966880-6ac6-11eb-89e1-f508636b86e9.png)
Once the user selects the time and clicks "Snooze", they are presented with a drop down to confirm their choice in deferring:
![image](https://user-images.githubusercontent.com/35249045/107414308-accb3700-6ac6-11eb-9c26-4b6d9917267a.png)

**Comment by erikng** [comment]
Closed with merge of https://github.com/macadmins/nudge/pull/204

**Comment by groob** [comment]
Curious why you went with a drop down vs a DatePicker? Just easier to implement, or did you have a different reason?

**Comment by erikng** [comment]
It's both. DatePicker is when you use custom.
