### ISSUE TITLE
Two very very minor observations/suggestions

### ISSUE THREAD

**Issue by donmontalvo** [macadmins/nudge#404]
The Launch Agent **com.github.macadmins.Nudge.plist** and Launch Daemon **com.github.macadmins.Nudge.logger.plist** appear to be set to **777**. Can they be changed to **644**?

EDIT: The black icons show the files are executable, however it might be they're set to 755, haven't confirmed.

Per [Semantic Versioning](https://semver.org), can the **CFBundleShortVersionString** be changed from **1.1.9.81436** to **1.1.9**? The **CFBundleVersion** is fine as **1.1.9.81436**.

Sweet tool, just starting to test it now.

**Comment by erikng** [comment]
huh, they should 100% not be 777.

**Comment by erikng** [comment]
`-rwxr-xr-x ` are the permissions for the launch agent
`-rwxr-xr-x ` are the permissions for the daemon 

Where are you seeing 777?

**Comment by donmontalvo** [comment]
Suspicious Package ratted Nudge out! :)
<img width="1171" alt="DonM_ 2022-09-16 at 9 13 25 AM" src="https://user-images.githubusercontent.com/20050282/190647130-22f05775-7961-4b7a-95ba-d66abf8bced3.png">

**Comment by donmontalvo** [comment]
> `-rwxr-xr-x ` are the permissions for the launch agent `-rwxr-xr-x ` are the permissions for the daemon
> 
> Where are you seeing 777?

Did you mean 644? Launch Agents|Daemons don't need to be executable.

**Comment by erikng** [comment]
You said in the issue that they are 777 permissions. I don't see that.

**Comment by donmontalvo** [comment]
> You said in the issue that they are 777 permissions. I don't see that.

My apologies, misspoke. I saw the black icons, meaning executable, assumed 777. If it's 755 that wouldn't follow Apple's guidelines which I believe is to make them 644?

**Comment by donmontalvo** [comment]
I updated my original post for clarity. Thanks.

**Comment by flammable** [comment]
Here's the output from my Mac, running the default LaunchAgent:

```
% ls -l /Library/LaunchAgents | grep -i nudge
-rwxr-xr-x  1 root  wheel  843 Aug 26  2021 com.github.macadmins.Nudge.plist
```

I'm not worried because write access is restricted. That said, Nudge is the only LaunchAgent on my system with executable permissions. I have no idea if that's an actual security issue or not, but it's somewhat of an oddity. Here's an example:

```
-rw-r--r--  1 root  wheel  704 May  4  2017 com.googlecode.munki.munki-notifier.plist
```

Revving the LaunchAgent might be problematic if it'd require a reboot. We're in the middle of a Nudge event for macOS 12.6, so I'd prefer not to roll that out immediately (especially if it's not an urgent concern).

**Comment by pro4tlzz** [comment]
I use a custom launch agent and set 644.

Absolutely no issues.

I think the permissions set for the launchagent would be done by the Github Actions workflow

**Comment by donmontalvo** [comment]
Any chance we can drop the build portion of the version in **CFBundleShortVersionString**? It's in **CFBundleVersion** which is fine.

**Comment by erikng** [comment]
At this time I don't plan on changing the plist versioning unless I can understand how it materially impacts your workflow.

**Comment by donmontalvo** [comment]
Thanks
