### ISSUE TITLE
Feature Request: Option to remove/hide the deferral timer for "Later"

### ISSUE THREAD

**Issue by dstranathan** [macadmins/nudge#406]
In our 3 week IT testing of Nudge, we had gotten pretty response thus far. Our #1 complaint (constructive criticism) has been this:

"When is Later? What does Later mean?"... to which the IT admins have to explain basic launch agent mechanics, and how/why/when  Nudge wakes up, evaluates it state and then takes action if required.

It was interesting to see this observation in the wild. many of the users dont see each other (they are isolated and don's share their Nudge experiences with each other (i.e.; this is not an "angry mob" situation).

We have considered renaming the "Later" string in the deferral drop-down menu to something like "~30 minutes" but thats a little squishy too.

Therefore, It would be nice (at least according to my test group) if we could just have deferral options of 1 Hour, 1 Day and Custom (Calendar). 

Just passing this feedback along in case others have inquired about this too...

**Comment by erikng** [comment]
A new key `allowLaterDeferralButton` will be in the next release of Nudge

https://github.com/macadmins/nudge/commit/e868c3491a37b3a079d76be891ae4f506d1b1341
