### ISSUE TITLE
Feature Request: Option to disable asynchronousSoftwareUpdate X seconds after requiredInstallationDate

### ISSUE THREAD

**Issue by cl2solutions** [macadmins/nudge#408]
Option to disable asynchronousSoftwareUpdate X seconds after requiredInstallationDate.

The target of this feature is users who have Macs, but only use them for 5-10 minutes sporadically.

By invoking an option like this, the Nudge window will open as quickly as possible, as opposed to Nudge not opening due to the update not being downloaded, courtesy of an enabled asynchronousSoftwareUpdate.

**Comment by erikng** [comment]
I've decided instead of another key, that I will just not honor that key after the requiredInstallationDate.

https://github.com/macadmins/nudge/commit/832771616e377c96fce9e3bee42eebd13ea59163
