### ISSUE TITLE
Support for Ventura

### ISSUE THREAD

**Issue by Cristal98** [macadmins/nudge#411]
Hello,

I implemented Nudge via JAMF Pro to bring all the computers in my organization to Monterey 12.6 in preparation for Ventura  13.0 which was released yesterday. It has been implemented successfully and I would like to do the same for Ventura. I have been attempting to test it on four computers and it seems Ventura may not be supported yet. Is this the case? 
I would like to use Nudge to upgrade all the computers in my organization to Ventura. 
Thank you!

**Comment by colorenz** [comment]
Nudge Works on Ventura. Whats your Problem? What is in the Logfile?

**Comment by Cristal98** [comment]
I have four different computers I updated for the Ventura (13), but neither of the four has received the prompt, but if I change requiredMinimumOSVersion to 12.6.1, it immediately prompts on the four computers.

**Comment by colorenz** [comment]
What is in the Logfile? open /var/log/Nudge.log

**Comment by jmahlman** [comment]
I have just confirmed it works on Ventura, I am guessing there is a misconfiguration.

**Comment by Cristal98** [comment]
<img width="859" alt="Screen Shot 2022-10-25 at 3 40 11 PM" src="https://user-images.githubusercontent.com/99671162/197866637-17848718-667b-4a7b-9ed9-781be8cc486f.png">


Hello,
There doesn't seem to be a Logfile for Nudge (please see file attached.)

**Comment by colorenz** [comment]
https://github.com/macadmins/nudge/wiki/Logging or install the Suite Installer to get logs automaticly under /var/log/Nudge.log.
https://github.com/macadmins/nudge/releases/download/v1.1.9.81436/Nudge_Suite-1.1.9.81436.pkg

**Comment by Cristal98** [comment]
<img width="386" alt="Screen Shot 2022-10-26 at 2 38 07 PM" src="https://user-images.githubusercontent.com/99671162/198108782-e58cd09a-a2a0-4155-bde2-ca6164bcc5a3.png">
<img width="857" alt="Screen Shot 2022-10-26 at 2 39 03 PM" src="https://user-images.githubusercontent.com/99671162/198108965-07b322cf-e1cc-4a90-b813-cc7f02c9fabc.png">

**Comment by colorenz** [comment]
There also now logs if you run Nudge? by your self?

**Comment by rougegoat** [comment]
I think you have to put "13.0" as the minimum version instead of just "13".  At least, that's what I had to do in my testing.

**Comment by dan-snelson** [comment]
Confirming that `13.0` works as expected:

https://macadmins.slack.com/archives/C02KPHZ7MDX/p1666831302262789?thread_ts=1666817887.774279&cid=C02KPHZ7MDX
