### ISSUE TITLE
Feature request - add macOS installers to default acceptableApplicationBundleIDs 

### ISSUE THREAD

**Issue by robertryansqub** [macadmins/nudge#414]
Adding this as requested on Slack.

The problem - a user had a new MacBook, which had clearly been sitting on a shelf for a while so was not running the latest macOS. Nudge was installed with a deadline about six weeks in the past, and allowGracePeriods set, so about 24 hours after deployment Nudge kicked into aggressive mode. The user opened System Preferences, and instead of opting to install the Monterey update opted to install Ventura. Once Ventura downloaded and the installer started, Nudge kept hiding it and taking focus, which was very annoying for the user who thought they were doing as asked.

I have worked around this by adding com.apple.InstallAssistant.macOSVentura (etc) to acceptableApplicationBundleIDs in my JSON file, but it may be best to make this a default behaviour.

**Comment by kevinmcox** [comment]
#412 is open on this as well.

**Comment by robertryansqub** [comment]
Will close as duplicated. Apologies - started to open issue, had to attend to cats, then submitted and clearly missed my window.
