### ISSUE TITLE
Ventura nudge detection issue 

### ISSUE THREAD

**Issue by mani2care** [macadmins/nudge#419]
Hi Team , i observed that having issue with nudge , unnecessarily users are getting error message as like below.

Issue observed it like - user is having 12.5.1 and nudge defined that 12.6.1 to update so that user in part of the rule like Nudge is active & running mode.

so when part of that group of users after upgraded to ventura those are getting below error. I think nudge is not identifying  that current OS either to run or not and ventura is already excluded from that ventura group.(suspect after upgraded to ventura that device is not connected to internet or taking some time to connect and still there that configuration profile so that device is getting triggered that nudge with error.)

Also i would like to hide that app from application folder and also from Launchpad ( it unnecessary to show it to users and they started questioning )

<img width="325" alt="image" src="https://user-images.githubusercontent.com/52978899/199459077-0230a6ed-a496-4f21-a893-6277235d2867.png">

<img width="335" alt="image" src="https://user-images.githubusercontent.com/52978899/199459536-1aff3473-e282-49bc-8875-165fff011eae.png">

**Comment by dan-snelson** [comment]
@mani2care:

Please confirm you've removed the quarantine flag before uploading:
`ls -lah@ /path/to/Nudge.pkg`

(We've added a [`rq`](https://snelson.us/2022/05/bz-please/#rq) to our `~/.zshrc`.)

You're welcome to adapt the following to hide Nudge:
https://github.com/dan-snelson/Nudge-Post-install/blob/main/Nudge-Post-install.bash#L151-L164

**Comment by mani2care** [comment]
If I use this instruction com.apple.quarantine  issue will be resolved? So the ventura users will not get this error who are from Monterey to ventura? 

Is this not added /validated via nudge? Or is there any fixes or solution or suggestions 

https://derflounder.wordpress.com/2012/11/20/clearing-the-quarantine-extended-attribute-from-downloaded-applications/

**Comment by donmontalvo** [comment]
For some reason I thought removing the quarantine flag shouldn't be needed if the app is recognized by Apple? If the flag has to be removed, thought also record of it is stored locally? I could be wrong.
