### ISSUE TITLE
Uninstallation steps

### ISSUE THREAD

**Issue by PandoJ** [macadmins/nudge#420]
Hello,

Could you please provide steps how to properly remove installed Nudge and Nudge LaunchAgent packages? I checked your wiki pages, but could not find any details.

Thank you,
Jan

**Comment by jmahlman** [comment]
Nudge should be removed like any other app bundle, you drag it to the trash or use an `rm -Rf` and the launchagent gets removed like any other launchagent: `launchctl unload /path/to/agent` then remove the file. 

Perhaps instructions can be written…but if you’re asking for your own information, there is your answer 🙂
