### ISSUE TITLE
Nudge UI does not disappear after clicking the Device Update button

### ISSUE THREAD

**Issue by tanng1999** [macadmins/nudge#422]
I have configured the **actionButtonPath** value (**Device Update** button) to call the Jamf’s Self-Service policy URL.

After I clicked the **Device Update** button to trigger the Jamf’s Self-Service policy (Install macOS Update using erase-install.sh ), the Nudge UI (inactive window) reappears again after a while.  This cause confusion to the users (e.g. they may click the Device Update button again to re-trigger the self-service policy).

Expecting the Nudge UI to be closed after clicking the **Device Update** button.

**Comment by flammable** [comment]
Nudge stays open by design - that way, users can't click on the "update" button and go back to whatever they were doing.

That said, #412 and the associated pull requests should address the issue you're seeing with the macOS upgrade installer.
