### ISSUE TITLE
Specify install-location in the macOS .pkg file's PackageInfo

### ISSUE THREAD

**Issue by debenedictis** [macadmins/nudge#428]
Microsoft Endpoint Manager was not installing Nudge-1.1.9.81436.pkg. When I googled I found this explanation from Microsoft: [macOS LOB apps aren't deployed in Microsoft Intune](https://learn.microsoft.com/en-us/troubleshoot/mem/intune/app-management/macos-lob-apps-not-deployed).

I believe the fix is to specify install-location in the macOS .pkg file's PackageInfo as "/Applications".

**Comment by erikng** [comment]
I'll explore this with the main pkg and report back.

**Comment by erikng** [comment]
It is in the v1.1.10 pre-release package now.
