### ISSUE TITLE
Switch LaunchAgent to StartInterval

### ISSUE THREAD

**Issue by flammable** [macadmins/nudge#429]
Hey Erik -

We inherited a custom LaunchAgent for Nudge, and are discussing how we'd want to modify it - whether we want to switch back to the default one, or further customize it to use `StartInterval` instead of `StartCalendarInterval`. We're already randomizing Nudge with the `randomDelay` key, but `StartInterval` would launch Nudge based on when the computer boots, not specifically on the hour and half-hour.

I couldn't find any discussion here or on Slack about the choice to use `StartCalendarInterval` instead of `StartInterval`. Do you think `StartInterval` would be an improvement? If so, I can submit a pull request that launches Nudge every 30 minutes, and update the wiki to describe the new behavior.

Thanks!

Mike

**Comment by erikng** [comment]
Not a bad idea. That might lead to more randomization though I can imagine some people wouldn't want that. 

I would point to this on macadmin slack and ask people to chime in.

**Comment by sjha967** [comment]
I have similar issues,  startinveral works after reboot. 

Testing now startcalenderinterval

**Comment by flammable** [comment]
It's been tricky to build a consensus, but [here's the discussion thus far on the MacAdmins Slack](https://macadmins.slack.com/archives/CDUU7DJQ2/p1671209634900049).

I think `StartInterval` makes more sense as a default LaunchAgent. As mentioned in the thread, if users prefer the current behavior, they can always ship a custom LaunchAgent. I think James Kane's explanation is the easiest for new users to grasp:

> Nudge will check if you’re up-to-date every 30 minutes after the initial pop up.

Confusion around the current :00 and :30 behavior comes up occasionally in the channel, so hopefully this would reduce some of the support questions that arise.

@sjha967 If you need help, please join the #nudge or #nudge-jamf channels on the [MacAdmins Slack](https://www.macadmins.org/).

**Comment by bradtchapman** [comment]
I'll add my vote for **StartInterval**.  I've never seen a LaunchAgent or Daemon fire exactly on the top or bottom of the hour.  There's already enough entropy introduced by the user's startup time.  And Nudge can add additional randomness with the random delay setting.  That should be enough to scatter the notifications across the fleet at different times.

**Comment by erikng** [comment]
After reading the conversation on Slack, I'm thinking for now to keep it as is. I already merged something for the next release of Nudge that will update the LaunchAgent and I don't think there is consensus.

I think having consistency as the default is a good thing and if someone doesn't like that consistency they can just use `randomDelay` or ship their own launch agent.

Changing the LaunchAgent now will lead to wider confusion as the behavior is somewhat of a breaking change. Since more admins are less technical, I'd rather not do this - at least not for now.

**Comment by flammable** [comment]
Sounds good. Thanks for considering this! We'll resume the discussion around modifying our own LaunchAgent, then.
