### ISSUE TITLE
Feature Request: Option to have X Days from nudge install for Due Date

### ISSUE THREAD

**Issue by atillathec** [macadmins/nudge#432]
I would love a feature where instead of putting in a date we can set it 7,8,9,10,etc days from profile load. This way new enrollments don't auto hit a due date after enrollment if they happen to be on an older OS.

**Comment by colorenz** [comment]
There is also a keys for that:

`allowGracePeriods - Type: Boolean, Default Value: false
v1.1.6 and higher only

Allows a device to modify the requiredInstallationDate logic and launch behavior. Useful for new device provisioning.

When using this feature, Nudge will reminded the user after the grace period.

gracePeriodInstallDelay - Type: Integer, Default Value: 23
v1.1.6 and higher only

The amount of time in hours Nudge will extend the requiredInstallationDate for newly provisioned devices.

gracePeriodLaunchDelay - Type: Integer, Default Value: 1
v1.1.6 and higher only

The amount of time in hours Nudge will bypass launching for newly provided devices.

gracePeriodPath - Type: String, Default Value: /private/var/db/.AppleSetupDone
v1.1.6 and higher only

The path of the file Nudge will read and assess for allowGracePeriods. The file /private/var/db/.AppleSetupDone is created automatically after finishing the Apple Setup Assistant.

`

https://github.com/macadmins/nudge/wiki/userExperience#allowGracePeriods---type-boolean-default-value-false

**Comment by atillathec** [comment]
yes but from my understanding if the Due Date is in the past then after your grace period it does not give a deferral option. What I'm saying is have a deferral option based on instal date rather then a hard coded due date.

**Comment by erikng** [comment]
People have asked for this before and I've opted not to build this at this time. It's a small bit of effort for you to enforce this and long term I think having hard dates vs dynamic windows is better for your own internal support, documentation and controls.
