### ISSUE TITLE
Using newest version of Nudge and unable to get updateElement to work

### ISSUE THREAD

**Issue by ryanasik** [macadmins/nudge#436]
I modified the updateElement section for including my own text, but it is not updating on my endpoints. I am still seeing the default text on the Nudge window. Is there a specific setting I need to change to make that work? I didn't have this issue previously in older versions of Nudge v1-1-5-81284, but started experiencing it in Nudge_Suite-1.1.9.81436.

**Comment by colorenz** [comment]
Post you config Profile.

Have you set the _language key? 

https://github.com/macadmins/nudge/wiki/updateElements#_language---type-string-default-value-

**Comment by ryanasik** [comment]
That was totally it! I overlooked the fast that en was already in the box, but I didn't actually type it in. Thanks you and my apologies. All good now.
