### ISSUE TITLE
Installing the LaunchAgent 1.0.1 and the Logger 1.0.1 pkgs give the following errors

### ISSUE THREAD

**Issue by colorenz** [macadmins/nudge#442]
Hi,

both packages seem to be corrupt. The Suite and the Nudge Installer work with out a problem.

[Nudge_LaunchAgent-1.0.1.pkg](https://github.com/macadmins/nudge/releases/download/v1.1.10.81462/Nudge_LaunchAgent-1.0.1.pkg)
[Nudge_Logger-1.0.1.pkg](https://github.com/macadmins/nudge/releases/download/v1.1.10.81462/Nudge_Logger-1.0.1.pkg)

![image](https://user-images.githubusercontent.com/16665557/213800592-46076332-a9e2-44a0-901e-7e9ec1fb083b.png)
![image](https://user-images.githubusercontent.com/16665557/213800656-c362a082-1058-40b4-ae75-699b912c1d84.png)

Best Regards

**Comment by pro4tlzz** [comment]
@colorenz These aren't notarised or signed as far to my knowledge. If you right click each PKG and press open then you can bypass this warning. This has always been the case with these packages

Also running the installer on the cli via an mdm or root should also bypass this.

**Comment by colorenz** [comment]
Oh I only use the Suite Installer, i have helped someone to troubleshoot. 

Good to know.
