### ISSUE TITLE
Enhancement idea

### ISSUE THREAD

**Issue by ryanasik** [macadmins/nudge#446]
Would it be possible to have the Nudge interface updated to show the requiredInstallationDate show? This would be helpful in letting end users know when they have to run the update by.

**Comment by dan-snelson** [comment]
@ryanasik: This one of the reasons we're using a scripted approach:
https://github.com/dan-snelson/Nudge-Post-install/wiki/10.-General-Resources#reference-images

**Comment by ryanasik** [comment]
Thank you!
