### ISSUE TITLE
Provide a signed PKG that includes the LaunchAgent and not the Logger

### ISSUE THREAD

**Issue by BigMacAdmin** [macadmins/nudge#449]
This is a convenience request that will prevent myself and other admins using Installomator or similar methods to deploy Nudge from having to create custom solutions.

Currently NudgeSuite is the only *signed* PKG that includes the default LaunchAgent. It also includes a LaunchDaemon that calls the `log` binary.  This is undesirable for a few reasons: 
1. Once Nudge is configured as expected the logger isn't necessarily useful to run on an entire fleet 
2. The `log` binary can apparently be a resource hog (see comment from Apple employee Groob in the Mac Admins Slack: https://macadmins.slack.com/archives/CDUU7DJQ2/p1675889649911569
3. It adds the dubious `log: item from unidentified developer` entry to the Login Items pane in Ventura, which can confuse users/admins

I could package and sign this myself, but it might be helpful to other Installomator users (or people that require a signed package for their management system) to have something signed that deploys Nudge+LaunchAgent or even just the LaunchAgent by itself.

Thanks for your time reading.

**Comment by aysiu** [comment]
The Nudge Launch Agent package looks signed to me:
https://github.com/macadmins/nudge/releases/download/v1.1.11.81465/Nudge_LaunchAgent-1.0.1.pkg
<img width="914" alt="Screenshot 2023-02-09 at 10 24 41" src="https://user-images.githubusercontent.com/13055957/217903956-df885f9c-5d5f-4610-a5b8-4c16b215c787.png">

**Comment by BigMacAdmin** [comment]
I must be losing my mind, sorry to waste your time.
