### ISSUE TITLE
Feature Request: Support for Separate Deadlines for Major and Minor Updates

### ISSUE THREAD

**Issue by rougegoat** [macadmins/nudge#450]
Currently, it is possible to use Nudge to push uses to a Major Upgrade or a Minor Update.  If configurations for both are present, the higher version tends to get Nudge'd.  This would mean if you set deadlines for macOS 13.2 and 12.6.3 on machines running macOS 12, they'll get prompted for macOS 13.2's deadline rather than 12.6.3's deadline.

There are some environments that would like to be able to set a longer Nudge deadline for a Major Upgrade while still using Nudge to push users to install Minor Updates that come out before the Major Upgrade's deadline.  For example, a school may not want to force a big OS upgrade mid semester, but still want to require it in a reasonable time frame.  Additionally, they would still want users to install whatever security updates come out in the mean time.

Would it be possible to add support for separate deadlines for Major and Minor updates?

**Comment by erikng** [comment]
There is already support for this and documented on the wiki. Please take a look.

**Comment by rougegoat** [comment]
I have looked through the Wiki and after not being able to find this made this feature request.

Can you clarify where in the Wiki it is located?

**Comment by onecheapgeek** [comment]
https://github.com/macadmins/nudge/wiki/targetedOSVersionsRule#real-world-example-1
