### ISSUE TITLE
Increase size of CompanyLogo block to 220 x 220

### ISSUE THREAD

**Issue by bradtchapman** [macadmins/nudge#452]
This is an enhancement request for the `LeftSide.swift` module.

https://github.com/macadmins/nudge/blob/b75e9d82bf544dda547b17f3f1b6726352a8b9f8/Nudge/UI/StandardMode/LeftSide.swift#L18-L34

Many institutions have square logos, or they would like them to appear larger in this space.  The wiki currently has no **documented** size for the logo, but the source code shows 200 x 150 units.  The actual pixel count depends on display density (@1x or @2x).  Currently, logos exceeding these dimensions are **scaled to fit.**

Please expand the the `CompanyLogo` to a width and height of **220 x 220** .

For reference, the thin gray horizontal line below the logo is a rectangle of 250 x 1 pixels.  

See attached screenshot for reference.

![nudge-companylogo-220px](https://user-images.githubusercontent.com/32527656/220776593-d1ca726d-5400-4520-9604-a8d389f54227.png)

**Comment by erikng** [comment]
I'm really not a fan of this change

current: 
<img width="1012" alt="Screenshot 2023-06-16 at 9 11 55 AM" src="https://github.com/macadmins/nudge/assets/5685016/3aa4dccb-557e-4630-bb98-14c864bad2f6">

requested change:
<img width="1012" alt="Screenshot 2023-06-16 at 9 33 37 AM" src="https://github.com/macadmins/nudge/assets/5685016/da67538f-f13d-4767-884f-f07647cce208">

**Comment by bradtchapman** [comment]
Holy backlog, Batman!

**Comment by bradtchapman** [comment]
@erikng : if you don't want to do this and haven't commented in 6 months, I'm just going to close it.

**Comment by erikng** [comment]
Sounds good.
