### ISSUE TITLE
Move identifier from com.github.macadmins.Nudge to io.macadmins.nudge

### ISSUE THREAD

**Issue by erikng** [macadmins/nudge#453]
Thinks to think through

- Migration path
  - Should we support both `com.github.macadmins.Nudge` namespace for a period of time (JSON and MDM Profile)?
  - Should admins just be required to deploy two profiles/JSONs for a bit instead while they upgrade?
  - Documentation/Blogs/etc will be inaccurate
  - macOS Ventura mdm profile and Notifications profile will also need to be updated.

**Comment by flammable** [comment]
Replacing the LaunchAgent would be an interesting problem, too. I guess we'd need to handle unloading the old one, then loading the new one?

**Comment by bradtchapman** [comment]
@erikng ; why is this needed?  Is there a change on the horizon?

**Comment by erikng** [comment]
Macadmins.io is the domain for MacAdmins open source, where these signing certs come from. 

MacAdmins.org is the domain for the MacAdmins foundation. 

Both are non profits but serve different purposes. These concepts post date this GitHub group, which is why I made the "mistake".

**Comment by erikng** [comment]
I've decided not to do this. It is not worth the pain for admins + my own sanity from a support perspective.
