### ISSUE TITLE
Feature Request Hide requiredInstallationDate

### ISSUE THREAD

**Issue by mrmte** [macadmins/nudge#454]
I would like to hide the required installation date from the users UI. 

When the user has defered the maximum times, i have noticed the deferal drop downs have gone but the required days to update is still visible to the end user in the UI. This is confusing for the user. The workaround would be just to be able to hide the days to update in the user ui so that is still applies but doesn't cause confusion.

**Comment by colorenz** [comment]
Mh it is then displayed in red and with minus. So that the user knows how long he is already over it.

Or I mixing something up?

**Comment by erikng** [comment]
I think in this case the admin is opting for a lower count of deferrals and those are met before the cut off date. 

I see the reason for this, but I may not have time to implement this anytime soon.

**Comment by tkimpton** [comment]
ok thanks, if this could be considered in the future, that would be great.

**Comment by erikng** [comment]
No longer wanted?

**Comment by tkimpton** [comment]
Would be good yes but i didn’t think it needed to be open as an issue. Np at all

**Comment by erikng** [comment]
I think this particular issue can be re-opened as it makes sense from a user perspective. I can see how it may be confusing.

**Comment by martas4444** [comment]
Hi!

It would be great to have such option to hide this, many thanks!

**Comment by erikng** [comment]
`hideDaysRemaining` coming soon
