### ISSUE TITLE
Is it possible to sync extension in private window?

### ISSUE THREAD

**Issue by cubical8569** [macadmins/nudge#458]
I use nudge with hardening slider and it's great. But in private window the extension doesn't remember how much time before I spent on the site in default mode. So if I open sugary site in private mode it's just an easy obstacle. It would be cool if extension had "global" counter which worked across private and classic browsing modes. 

I understand that this might not be possible due to browser API limitations. I'm not sure if it is or not. If it's possible I want devs to know that somebody wants such functionality. Thank you for your project.

**Comment by colorenz** [comment]
Which extension do you mean? A Browser extension for nudge??
