### ISSUE TITLE
After running Nudge with -debug-ui-mode, window height stays doubled

### ISSUE THREAD

**Issue by ggeerraalldd** [macadmins/nudge#459]
M1 Max MacBook Pro, macOS 13.2.1, Nudge 1.1.11.81465
While working on updating my config JSON for upcoming macOS releases, I ran Nudge from Terminal in debug-ui-mode to check normal and simple window layouts.
After I did that, every time the Nudge window was opened (with -demo-mode, or manually launching the app, or via the launchd), the window height remained at x2, with the content centered vertically.

An M1 Mac mini on 13.2.1 had the same issue, but an M1 Mac mini on 12.6.3 did not.
Deleting the com.github.macadmins.Nudge.plist corrects the issue, but the deferral information is also lost.

After downgrading Nudge to 1.1.9 or earlier, the issue did not occur. Running Nudge 1.1.10 or later will have the doubled window height after -debug-ui-mode.

<img width="900" alt="image" src="https://user-images.githubusercontent.com/24395097/225187648-cd685ce0-c4cc-475e-9f6b-3c81b35bcb7d.png">

Prefs after normal run:
`~ % defaults read com.github.macadmins.Nudge`
`{`
`    "NSWindow  Frame SwiftUI._ConditionalContent<SwiftUI.ModifiedContent<SwiftUI.VSplitView<SwiftUI.TupleView<(SwiftUI.ModifiedContent<Nudge.ContentView, SwiftUI._FrameLayout>, SwiftUI.ModifiedContent<Nudge.ContentView, SwiftUI._FrameLayout>)>>, SwiftUI._FrameLayout>, SwiftUI.ModifiedContent<Nudge.ContentView, SwiftUI._FrameLayout>>-1-AppWindow-1" = "510 454 900 478 0 0 1920 1055 ";`
`    deferRunUntil = "2023-03-14 21:00:03 +0000";`
`    requiredMinimumOSVersion = "13.3.1";`
`    userDeferrals = 1;`
`    userQuitDeferrals = 1;`
`    userSessionDeferrals = 0;`
`}`

Prefs after debug-ui-mode run: 
`~ % /Applications/Utilities/Nudge.app/Contents/MacOS/Nudge -debug-ui-mode`
`~ % defaults read com.github.macadmins.Nudge`       
`{`
`    "NSWindow Frame SwiftUI._ConditionalContent<SwiftUI.ModifiedContent<SwiftUI.VSplitView<SwiftUI.TupleView<(SwiftUI.ModifiedContent<Nudge.ContentView, SwiftUI._FrameLayout>, SwiftUI.ModifiedContent<Nudge.ContentView, SwiftUI._FrameLayout>)>>, SwiftUI._FrameLayout>, SwiftUI.ModifiedContent<Nudge.ContentView, SwiftUI._FrameLayout>>-1-AppWindow-1" = "510 116 900 928 0 0 1920 1055 ";`
`    deferRunUntil = "2023-03-14 21:03:27 +0000";`
`    requiredMinimumOSVersion = "13.3.1";`
`    userDeferrals = 2;`
`    userQuitDeferrals = 2;`
`    userSessionDeferrals = 0;`
`}`

Prefs on next normal run:
`~ % /Applications/Utilities/Nudge.app/Contents/MacOS/Nudge`
`~ % defaults read com.github.macadmins.Nudge`
`{`
`    "NSWindow Frame SwiftUI._ConditionalContent<SwiftUI.ModifiedContent<SwiftUI.VSplitView<SwiftUI.TupleView<(SwiftUI.ModifiedContent<Nudge.ContentView, SwiftUI._FrameLayout>, SwiftUI.ModifiedContent<Nudge.ContentView, SwiftUI._FrameLayout>)>>, SwiftUI._FrameLayout>, SwiftUI.ModifiedContent<Nudge.ContentView, SwiftUI._FrameLayout>>-1-AppWindow-1" = "510 116 900 928 0 0 1920 1055 ";`
`    deferRunUntil = "2023-03-14 21:04:41 +0000";`
`    requiredMinimumOSVersion = "13.3.1";`
`    userDeferrals = 3;`
`    userQuitDeferrals = 3;`
`    userSessionDeferrals = 0;`
`}`

As this is unlikely to happen outside of a development computer using the debug-ui-mode, it won't prevent me from using Nudge.

**Comment by erikng** [comment]
https://github.com/bartreardon/swiftDialog/commit/64bbe07cd5877550364d143da94207fd92f65b43

**Comment by erikng** [comment]
I just experienced this issue and got really upset with how ugly nudge looks. I will try and figure this out soon.

**Comment by erikng** [comment]
I believe this is fixed now. I cannot recreate it anymore with current xcode builds.
