### ISSUE TITLE
nudge logic isn't correct with targetOSVersionRule

### ISSUE THREAD

**Issue by tkimpton** [macadmins/nudge#461]
receiving really strange log entries where the client is on macOS 12.3, nudge is configured for requiredMinimumOSVersion 13.2.1 with targetOSVersionRule 12.

This log is say the conditions have been met when they have not.

2023-03-15 13:33:32.483326+0000 localhost Nudge[10991]: [com.github.macadmins.Nudge:softwareupdate-list] softwareupdate did not find 0.0 available for download - skipping download attempt
2023-03-15 13:33:32.577217+0000 localhost Nudge[10991]: [com.github.macadmins.Nudge:utilities] Current operating system (12.3) is greater than or equal to required operating system (0.0)
2023-03-15 13:33:32.577281+0000 localhost Nudge[10991]: [com.github.macadmins.Nudge:user-interface] Device is fully updated
2023-03-15 13:33:32.577297+0000 localhost Nudge[10991]: [com.github.macadmins.Nudge:user-interface] Nudge is terminating due to condition met

attaching config as zip

**Comment by colorenz** [comment]
formatting is terrible....

change your to "targetedOSVersionsRule": "default"

**Comment by tkimpton** [comment]
[config.plist.zip](https://github.com/macadmins/nudge/files/10984050/config.plist.zip)

**Comment by tkimpton** [comment]
I believe this may be a bug because it was all working as expected until I changed allowedDeferals to 0 and allowedDeferralsUntilForcedSecondaryQuitButton to 0 to test. When I change this fields back to what I had then it works fine.

**Comment by aysiu** [comment]
This isn't a bug. Look closely at your log entry:
```
2023-03-15 13:33:32.577217+0000 localhost Nudge[10991]: [com.github.macadmins.Nudge:utilities] Current operating system (12.3) is greater than or equal to required operating system (0.0)
```
Something is wrong with your configuration profile or .json, as Nudge thinks the required operating system is `0.0` and not `13.2.1`.

**Comment by kevinmcox** [comment]
@tkimpton per discussion in the other ticket you opened this morning (https://github.com/macadmins/nudge/issues/460) please join us in Slack for general troubleshooting.

**Comment by erikng** [comment]
The problem is it's not a bug. Please join the macadmins slack for people to help you.

**Comment by tkimpton** [comment]
in my 20+ years any my analysis of this a disagree. closing as this doesnt seem to be getting anywhere regardless!

**Comment by erikng** [comment]
Tim,

I mean this nicely but you have struggled to even properly post your configuration on this GitHub issue. You were told by multiple people a theory on why you are experiencing an issue and rather than try it, you continued to say it is a bug.

If you can properly post your configuration people can likely help you, but when you say things like "in my 20 years" it shows your unwillingness to take your past experience out of the picture. It's biasing you.

You were asked multiple times to come to the support side where there are literally THOUSANDS of admins that use nudge willing to help you but you have also refused to do that.

We are here to help, but it doesn't seem that you are willing to step aside your own ego. This might enrage you more, but you need to hear it.

**Comment by kevinmcox** [comment]
> i believe the bug is related to requiredMinimumOSVersion "Note: When passing versions such as 11.2.0 it will be normalized to 11.2. It is recommended to remove the trailing zero from the version number."
> 
> in my config as you can see i am specifically setting this value and 13.2.1. There is a business and i will reflect that in my config and verify. We have a business need to point users already on 13.2 to 13.2.1 full installer automation with this config. With this bug this isn't going to work as Nudge will recognise the OS already on 13.2 and not 13.2.1. In the short term this is a temporary fix go get 12.x systems up to 13.2.X but this is still a bug when we need a full reinstall of systems on 13.2 to 13.2.1 this isn't going to work. With all due respect @ aysiu thanks for the reply but this IS a bug. to be clear im not asking for support or help on config. Im reporting a bug.

@tkimpton we use `13.2.1` in our config and it works fine.

**Comment by aysiu** [comment]
> i believe the bug is related to requiredMinimumOSVersion "Note: When passing versions such as 11.2.0 it will be normalized to 11.2. It is recommended to remove the trailing zero from the version number."

From your log:
`Current operating system (12.3) is greater than or equal to required operating system (0.0)`

So this is not Nudge seeing that 12.3.0 is 12.3. It's not seeing your Nudge config at al, which is why it thinks the required operating system is 0.0.

**Comment by tkimpton** [comment]
All I understand what you are all saying. To be clear I have configured everything correctly and I’m not a noob. I was trying to report a bug where upon modifying a profile can in a strange circumstance which I have seen twice already, have this unexpected result. This is extremely disappointing I am receiving such harsh critic from the members of the Mac admin community.

**Comment by tkimpton** [comment]
@aysiu thanks very much for your recommendations.

**Comment by tkimpton** [comment]
@erikng not at all it’s not about ego. I’m trying to report a bug I have seen twice to instantly get the issue closed. This is not a good thing to do. I tried to post my config but yet again received harsh critic and retaliation on anything I report. I like the product have joined the Mac admins slack. But from not being a Mac admin noob but new to nudge I don’t and didn’t expect such a hostile response tbh.

**Comment by erikng** [comment]
Hm I missed the last part of your message as I typed this. Can you link me into that known issue in Slack?
