### ISSUE TITLE
Add known issues to wiki 

### ISSUE THREAD

**Issue by tkimpton** [macadmins/nudge#464]
There is a common issues section which is great but there are known issues in macadmins slack not identified here on GitHub. Im it would be great to have a known issues section in the wiki which is updated so  that admins can check that out first before raising issues or having to scroll through chats to find out the issue is already known.

**Comment by colorenz** [comment]
Everyone can edit the Wiki. Feel free to add that by your self and also may add a workaround for that know issue if it exist.

**Comment by tkimpton** [comment]
Ok np thanks

**Comment by erikng** [comment]
I'm wondering if we should delineate between "common issues" that can be caused by an admin vs "known issues" which would imply a bug admins have to work around.

**Comment by kevinmcox** [comment]
@erikng I think that makes sense.
