### ISSUE TITLE
If an app from the blockedApplicationBundleIDs list is terminated by Nudge, bring Nudge immediately back to the top.

### ISSUE THREAD

**Issue by bradtchapman** [macadmins/nudge#466]
While Nudge is running, it may get buried by other windows.  If this happens while the deadline passes and the user tries to launch an app on the blocked list, it will close without any message on screen.  Since Nudge killed it, Nudge should bring itself back to the foreground.

**Comment by erikng** [comment]
I'm going to bring nudge back, but not going to count this as a deferral.

**Comment by bradtchapman** [comment]
@erikng : thanks!
