### ISSUE TITLE
updateElements subHeader not updating

### ISSUE THREAD

**Issue by tomc-huma** [macadmins/nudge#469]
We're trialling Nudge and importing the JSON file to Jamf but when we update the updateElements subHeader field this does not reflect when the client opens. When it client opens, we get the default "A friendly reminder from your local IT Team". When we update the JSON config in Jamf, we can see the updates refelected in Library/Managed Preferences/com.github.macadmins.Nudge.plist

**Config in Jamf JSON**
<img width="716" alt="Screenshot 2023-03-29 at 14 44 53" src="https://user-images.githubusercontent.com/109522471/228558002-2622f93d-0d99-4880-af36-031ae1e7673b.png">

**Wording in client**
<img width="510" alt="Screenshot 2023-03-29 at 14 45 19" src="https://user-images.githubusercontent.com/109522471/228558132-f4343efd-5f23-4732-85b8-80e5210f27a1.png">

**PLIST file in Library/Managed Preferences:**
<img width="678" alt="Screenshot 2023-03-29 at 14 46 22" src="https://user-images.githubusercontent.com/109522471/228558456-a7c64603-0612-4fc4-85ac-5f5ff6c1d8fa.png">

**Comment by erikng** [comment]
https://github.com/macadmins/nudge/wiki/Common-Issues#help-my-paragraph-and-text-changes-are-not-showing-up-in-the-ui

Please see this.
