### ISSUE TITLE
Nudge custom deferrals not working

### ISSUE THREAD

**Issue by marcusburst** [macadmins/nudge#471]
Whenever a user uses a custom deferral option, Nudge doesn't re-prompt at that time.

Screenshot attached showing deferral set for 2023-04-09 05:27:48 and then terminal timestamp showing 2023-04-09 05:28:09 with no Nudge popup.

Logs attached in pdf format.

Able to reproduce this behaviour with Nudge versions 1.1.11.81465 and 1.1.6.81329. Using MacOS Ventura 13.2.1.

![nudge](https://user-images.githubusercontent.com/18186363/229023777-921ee798-798f-4212-b162-8dcb3e48bf64.png)
[nudgelogs.pdf](https://github.com/macadmins/nudge/files/11118191/nudgelogs.pdf)

**Comment by erikng** [comment]
That's not exactly how it works. Please read the documentation. Nudge is launched via the launch agent and what you have deployed there. It will almost never be launched at the exact time they deferred to but after the time has been reached, the next launch agent run will allow it to launch.
