### ISSUE TITLE
Disabling "Update Later" presents UI issue when the requiredInstallationDate is within the hour

### ISSUE THREAD

**Issue by wegotoeleven** [macadmins/nudge#475]
An issue has been observed when disabling the Update Later button; the dropdown list is not visible when there is less than an hour before the installDate.

The below screenshot looks like nothing is wrong, but upon clicking the dropdown, nothing appears. Which makes sense; we’ve:
- Disabled “Update Later”
- It's within 72 hours, so the "Custom" option isn't available
- Both “One hour” and “One Day” have passed

![Untitled](https://user-images.githubusercontent.com/7345765/231234010-4ee0737b-1b93-4ab1-99cb-f4ac861d8e29.png)

To reproduce:
1. Install Nudge (at leasy 1.1.11) and apply basic configuration 
2. Set `allowLaterDeferralButton` to `false` within the configuration
3. An hour before the `requiredInstallationDate`, attempt to click the `Defer` dropdown

**Comment by erikng** [comment]
Sounds like the only option is to not allow any deferral UI in this state then since you disabled that key. Do you disagree?

**Comment by wegotoeleven** [comment]
I agree with that sentiment. Removing the deferral drop-down menu altogether when Nudge is within the final hour should suffice.

**Comment by erikng** [comment]
Fixed here https://github.com/macadmins/nudge/commit/d904dff5540ec21307340d8e22bb77e44a91b0d0
