### ISSUE TITLE
Show the Required Install Date in the Nudge window

### ISSUE THREAD

**Issue by bp88** [macadmins/nudge#476]
Nudge currently shows the "Days Remaining To Update" on the left side of the window. This is of course very handy. Some people however also find it handy to simply see the actual date. To that end, this feature request is to **additionally** display the "Required Install Date". Currently, the only way to really show the date is to include the date in the the title or content area of the Nudge window. That is obviously info that needs to be consistently updated every time the Nudge config needs to be updated.

If you were to implement this, I could see this getting tricky with determining the format to display this in. Ideally, there would be a way to specify the format you wish to display the Required Install Date. But if you have to default to something that's perfectly fine and understandable. I imagine displaying value in the format of: YYYY Month Day HH:MM TimeZone (e.g. 2023 April 14 17:00 UTC). Others might have a better idea or recommendation.

At the very least I wanted to create the request to start a discussion. Hopefully others can see the potential value in this.

**Comment by erikng** [comment]
it looks pretty terrible
<img width="1012" alt="Screenshot 2024-05-31 at 1 29 12 PM" src="https://github.com/macadmins/nudge/assets/5685016/87861930-2816-45ac-b562-8eefb1d9e3e9">

**Comment by erikng** [comment]
It looks even worse if I attempt to slim the text to fit

<img width="1012" alt="Screenshot 2024-05-31 at 1 40 23 PM" src="https://github.com/macadmins/nudge/assets/5685016/30685d64-7dfa-48f6-82a8-8096b330b2db">
<img width="1012" alt="Screenshot 2024-05-31 at 1 43 08 PM" src="https://github.com/macadmins/nudge/assets/5685016/72374290-e94a-4b81-b1fd-88db91fee308">

**Comment by Tribruin** [comment]
Maybe do the time as two lines

Required                 06/01/2024
Installation Date:    20:00 UTC

I think one of the concerns is the format of the date and time. If I was a user, I would prefer to see my time in local time versus UTC (or another time zone). Are you just passing the required date from the configuration without any translation?

**Comment by erikng** [comment]
I'm not sure if you missed it, but CST is not UTC, that is my local timezone (central standard time).

**Comment by erikng** [comment]
For historical context, I have made the decision that out of the box, it will just have `MM/dd/yyyy`
<img width="1012" alt="Screenshot 2024-05-31 at 4 06 52 PM" src="https://github.com/macadmins/nudge/assets/5685016/80906b26-e414-4e8e-b52a-7a8a13870cc3">

The original request wanted a format of `MM/dd/yyyy hh:mm a zz` and that is well within their right to display it this way. If they choose for it to look strange, that is ultimately on them.

<img width="1012" alt="Screenshot 2024-05-31 at 4 07 07 PM" src="https://github.com/macadmins/nudge/assets/5685016/95fc74bc-ff5e-4d67-9322-ec2b0c4fedde">
