### ISSUE TITLE
Add process blocker, similar to acceptableAssertionApplicationNames

### ISSUE THREAD

**Issue by charliwest** [macadmins/nudge#480]
For some circumstances it would be nice to block Nudge from running if certain processes are also running.

Similar to how acceptableAssertionApplicationNames blocks apps, maybe a script is running and we want Nudge not to run, a simple way I can think is to check for processes and not run if it is found.

**Comment by kevinmcox** [comment]
Can you check the features here and make sure they don't already do what you want:
https://github.com/macadmins/nudge/wiki/optionalFeatures

**Comment by bradtchapman** [comment]
It sounds like @charliwest is asking whether Nudge can monitor the activity of **any** arbitrary process on the computer.  I don't know whether Swift can run `pgrep` with a process name?  And this is made more complicated by the fact that "scripts" are often called by `bash` or `zsh` or `perl` or `python`, making your known management scripts completely indistinguishable from other non-management processes using those same runtimes.

**Comment by charliwest** [comment]
Sorry I totally missed this question.

Basically my idea was not to run the reminder while a script was downloading the installer in the background, or maybe doing a FileVault key rotation. 

Now though we have other ways of doing these things so it has become a mute point for me at least so can be closed :)
