### ISSUE TITLE
Bug / Feature Request - Calendar Deferrals limited by imminentWindowTime instead of approachingWindowTime

### ISSUE THREAD

**Issue by samuelzamvil** [macadmins/nudge#481]
It's not apparent if the behavior of the calendar deferrals is a bug or not. The following code has a comment suggesting that we are using approachingWindowTime but on the following line imminentWindowTime is used in the calculation.

https://github.com/macadmins/nudge/blob/911e43328aff874574cce402f2ea526d555b1e74/Nudge/UI/Common/DeferView.swift#L80-L81

Possible solution:
To prevent conflicts with existing configurations and additional key "calendarDeferUntilApproaching" could be added and set to false by default. This key would be used in order to determine if approachingWindowTime will be used instead of imminentWindowTime.
In order to make this change the following files would need to be updated as well as the example assets.

Nudge/Preferences/DefaultPreferencesNudge.swift
Nudge/Preferences/PreferencesStructure.swift
Nudge/UI/Common/DeferView.swift

Example Assets/com.github.macadmins.Nudge.json
Example Assets/com.github.macadmins.Nudge.mobileconfig

---
`Update to wiki`
#### `calendarDeferUntilApproaching` - Type: Boolean, Default Value: false
v1.1.X and higher only

Utilize the `approachingWindowTime` instead of `imminentWindowTime` for calendar deferrals during the Regular Window Time period.

**Comment by erikng** [comment]
see the PR comments and update the wiki please.
