### ISSUE TITLE
targetedOSVersionsRule Not Applying

### ISSUE THREAD

**Issue by ebbymac** [macadmins/nudge#484]
I'm having issues with the targetedOSVersionsRule not applying in the latest release. I have targetedOSVersionsRule set to 13 but Nudge still prompts on Monterey and Big Sur machines. This is happening with JSON and Config Profile in Jamf.  We have 200+ Macs across 40 companies. 75 of them aren't on Ventura yet and I have to disable Carbon Black before any UPGRADE can take place. That is why this rule is so important. I know I can scope but I would rather have one global config profile.

Any help would be appreciated. I am using the suite to deploy.

Here are the logs:
enforceMinorUpdates: true
Device requires major upgrade - attempting download
softwareupdate successfully downloaded available update application - updating application paths
New Nudge event detected - resetting all deferral values
Device pastRequiredInstallationDate: false
Nudge is currrently the frontmostApplication
Nudge is currrently the frontmostApplication
 Nudge is currrently the frontmostApplication
User clicked deviceInfo

I have confirmed the config on the machine with print-profile-config and it matches.
<img width="886" alt="Screen Shot 2023-05-04 at 11 33 58 AM" src="https://user-images.githubusercontent.com/132597278/236268618-2adb7c9f-4210-4375-a1c1-7e7b0807cd8e.png">

![Capture](https://user-images.githubusercontent.com/132597278/236269086-4c2aa165-d8d6-46b1-9d57-0cdad7f202c3.JPG)

**Comment by mrmte** [comment]
try changing it to default and only scoping your profile to the required systems.

**Comment by erikng** [comment]
Github is primarily for the development of nudge. Please come to the macadmin slack for support in the nudge channel if you haven't already.
