### ISSUE TITLE
Grey out dates on Custom deferral

### ISSUE THREAD

**Issue by staze** [macadmins/nudge#486]
Right now, if you try to pick a date after the deadline, it just auto-selects the deadline date. From a UI perspective, this is a little bit of "false hope".

All dates past the deadline should just be greyed out as not selectable.

**Comment by kevinmcox** [comment]
I can't find an open GitHub Issue about this, but I'm pretty sure this is a known limitation of Swift UI that has been discussed before.

**Comment by erikng** [comment]
Yes. This is a known issue with SwiftUI framework. Nothing I can do on macOS to fix this.
