### ISSUE TITLE
MacOS version 13.3.1 (a)

### ISSUE THREAD

**Issue by XAGSolutions** [macadmins/nudge#487]
Apple has started releasing versions with alphanumerics, and the response I get from my mobile deployments is this:

Nudge/DefaultPreferencesNudge.swift:56: Fatal error: 'try!' expression unexpectedly raised an error: Nudge.OSVersion.ParseError.badFormat("Converting string parts to Int")

Is there a different format I should be using?

"requiredInstallationDate": "2023-05-25T00:00:00Z",
      "requiredMinimumOSVersion": "13.3.1 (a)",
      "targetedOSVersionsRule": "default"

**Comment by drtaru** [comment]
Nudge does not current support RSRs, you cannot set a RSR version as a `requiredMinimumVersion`

**Comment by Nothing4You** [comment]
see also #389

**Comment by XAGSolutions** [comment]
Thanks for the info guys.
