### ISSUE TITLE
Nudge time

### ISSUE THREAD

**Issue by Argosgate** [macadmins/nudge#505]
I was curious if it was possible within Nudge settings or via Jamf to schedule a time at which the Nudge notification would first appear. In short to prevent staff from getting a Nudge notification say right during a Zoom meeting etc if Apple releases an update in the middle of the afternoon/business hours. Ideally, we would like the Nudge notice to appear after business hours and staff would see it first after hours or at first login and then make their choice at that time, to defer or update. 
Thanks for any inputs while I continue to research and test.

**Comment by Tribruin** [comment]
Nudge will only start prompting when you update your settings with a new RequiredMinimumOSVersion. So, if you are currently nudging for 13.4.1 and Apple release 13.5 none of your users will get a Nudge until someone updates the requirements (either a Config profile or JSON). So you could do that after hours, so users start getting nudged the next day. 

To prevent a user from getting Nudge during a Zoom meeting, take a look at the Optional Features in the Wiki. You can define certain criteria (apps running, camera active, etc.) that will prevent Nudge from taking focus. 

https://github.com/macadmins/nudge/wiki/optionalFeatures

**Comment by bradtchapman** [comment]
@erikng : this one should be closed as solution found in documentation.
