### ISSUE TITLE
Manually Updating mobileconfig file

### ISSUE THREAD

**Issue by shakey-zak** [macadmins/nudge#506]
Hello,

Everytime a new Mac OS version is released, I'm having to go into the .mobileconfig file and update the two fields

`<key>requiredInstallationDate</key>`
`<date>**2023-07-11T17:00:00**Z</date>`
`<key>requiredMinimumOSVersion</key>`
`<string>**13.4.1**</string>`

Is there a way to automate this? How are other mac admin managing this.

Thank you very much

**Comment by WFHSam** [comment]
Welcome to the party pal! 
This is what every Mac Admin has to do.

**Comment by erikng** [comment]
There are open tickets for something like this. At the moment you have to update it and that is very likely going to be the design for the foreseeable future.
