### ISSUE TITLE
Feature Request: Variable icons depending on deferral count

### ISSUE THREAD

**Issue by rajohnson124** [macadmins/nudge#508]
Would like to see the possibility of changing icons based on the number of deferrals + if the aggressive mode is enabled. From a branding perspective, it would helpful / interesting, to change the icon to catch the attention of the user the more they defer, changing the icon to a more persuasive icon.

**Comment by erikng** [comment]
I'm inclined to not do this. Once I offer two sets of icons, someone will ask for three.

**Comment by bradtchapman** [comment]
I understand why you'd be disinclined, because now you'd be giving the admin not two icons, but potentially SIX icons to juggle (3 for light and dark mode, respectively).  

The swiftDialog project handles this with different icons laid over the image.  

Would it be possible to do that instead?

**Comment by erikng** [comment]
I would put my Greg hat on and say you could script the JSON to do whatever your happy self wants but in the grand scheme of things, this is such a low priority and I genuinely don't see what real benefit this does.

**Comment by bradtchapman** [comment]
¯\\\_(ツ)_/¯  - can't argue with that.  If someone really wants this, they can write some code and make a pull request in GitHub.

This can probably be closed, @erikng .
