### ISSUE TITLE
Nudge shows wrong deadline when non-Gregorian calendar is configured

### ISSUE THREAD

**Issue by loke-ss** [macadmins/nudge#509]
We had a user surprise us with days remaining in negative 6 digits range. As it turns out he has his locale set as en_TH with default calendar being Buddhist. As we have a sizable number of Thai users, how can we properly grant them a deadline instead of throwing them into aggressive mode each time we push out a new config.

<img width="513" alt="Screenshot 2566-09-05 at 16 44 39" src="https://github.com/macadmins/nudge/assets/107158652/949f8482-01d6-47a9-9a40-b8ea0ba13443">

**Comment by loke-ss** [comment]
hope this is helpful.

`In Swift, you can convert dates from one calendar to another using `DateComponents`. Let's say you have a date in the Buddhist calendar and you want to convert it to the Gregorian calendar. 

Below is an example of how to perform this conversion:

```swift
// 1. Setup the Buddhist date formatter
let buddhistFormatter = DateFormatter()
buddhistFormatter.calendar = Calendar(identifier: .buddhist)
buddhistFormatter.dateFormat = "yyyy-MM-dd"

// 2. Convert the Buddhist date string to a Date object
let buddhistDateString = "2566-09-12"
guard let buddhistDate = buddhistFormatter.date(from: buddhistDateString) else { 
    fatalError("The provided date is invalid") 
}

// 3. Get date components from the Buddhist date using the Buddhist calendar
let buddhistComponents = Calendar(identifier: .buddhist).dateComponents([.year, .month, .day], from: buddhistDate)

// 4. Convert these components to a Gregorian Date
let gregorianDate = Calendar(identifier: .gregorian).date(from: buddhistComponents)

// 5. Print the Gregorian date
let gregorianFormatter = DateFormatter()
gregorianFormatter.dateFormat = "yyyy-MM-dd"
print("Gregorian Date: \(gregorianFormatter.string(from: gregorianDate!))")`

**Comment by erikng** [comment]
At some point I tested buddhist calendar and must have done this incorrectly.

https://github.com/macadmins/nudge/commit/840e781df6806e1516a75f80096b32b1fe5f002c

It should be fixed in the next pre-release.
