### ISSUE TITLE
This is evil

### ISSUE THREAD

**Issue by eskornd** [macadmins/nudge#510]
Well, the software is great (may be for IT).

But as an end user I personally feel the Nudge is evil as it blocks my screen and stopping me from doing my daily jobs unless I run a mac updates.

What about giving end user a choice to dismiss the dialog?

**Comment by SMillerDev** [comment]
> What about giving end user a choice to dismiss the dialog?

There is by default, if there isn't... talk to your IT team that configured it that way. Or just update your mac directly so you never get the popup.
