### ISSUE TITLE
Want to install minor updates - but installing major releases

### ISSUE THREAD

**Issue by LeMoerk** [macadmins/nudge#512]
Hi, need some help.
I try to enforce the minor update with "enforceMinorUpdates": true. The major updates should not be loaded with "attemptToFetchMajorUpgrade": false.
Now I start Nudge, it jumps to the software update as desired, but still loads the upgrade to the latest version. How can this be prevented? 
I currently need the latest minor updates for Big Sur, Monterey and Ventura.

**Comment by LcTrKiD** [comment]
Hi @LeMoerk,
Please use the [#nudge](https://macadmins.slack.com/archives/CDUU7DJQ2) channel in Slack if you need some help. "Issues" is for requesting new features, provide feedback, report bugs... 
Thanks

**Comment by LeMoerk** [comment]
@LcTrKiD Thanks, i will...
