### ISSUE TITLE
Nudge Segmentation Fault

### ISSUE THREAD

**Issue by laurentdelosieresfact** [macadmins/nudge#513]
Good afternoon,

When the `requiredMinimumOSVersion` parameter is set to the major version only (e.g. 14), intead of `major.minor` (e.g. 14.0), Nudge is causing a segmentation fault.

This has been tested with the latest version of Nudge.

Best,
L.

**Comment by eviscares** [comment]
Ran into this one as well.

**Comment by erikng** [comment]
I don't plan on fixing this.
