### ISSUE TITLE
any actions?

### ISSUE THREAD

**Issue by avincent98144** [macadmins/nudge#517]
Are there any actions when starting the app? I see nothing in the dock and no splash screen or anything at all.

**Comment by kevinmcox** [comment]
@avincent98144 please join us in the #nudge channel of the MacAdmins Slack (www.macadmins.org) for assistance with using Nudge.

**Comment by avincent98144** [comment]
I’m retired now and use NUDGE only on my personal family network and I no longer use or have a need for SLACK.

Is there another avenue for light support here?

Cheers
Anthony Vincent

**Comment by erikng** [comment]
The wiki is quite fleshed out. But no the GitHub is not being used as support. Please read that and if you need more help I'd ask that you temporarily install slack.
