### ISSUE TITLE
Feature request - "Update Now" button configuration key to run bash command

### ISSUE THREAD

**Issue by xirianlight** [macadmins/nudge#52]
I've had some client feedback about wanting a one-button solution instead of having the update trigger opening System Preferences - would it be possible to consider an alternative to "path_to_app" and "local_url_for_upgrade" that could run a supplied bash command?

**Comment by erikng** [comment]
From a technical perspective it would be easy but there's some caveats.

1. it would run as the user
2. Apple doesn't test scripted Apple updates and it would likely reduce the success of installations across devices. 

I originally built nudge to avoid scripted events like Munki after seeing upwards of 3% failure rate which doesn't sound like a lot until you are managing 25,000 machines.

**Comment by abstertee** [comment]
the use of a privileged helper tool would help when running commands that need root level permissions.  You could always run this command, but it will launch the app as if the user clicked on it
`try NSWorkspace.shared.launchApplication(at: putyourvriablehere as URL, options: .andHideOthers, configuration: [:])`

**Comment by xirianlight** [comment]
Valid caveats - even with the disclaimer of not wanting to run the actual softwareupdate command, it would be helpful to launch other apps in the userspace with arguments in response to clicking the button.

**Comment by jby** [comment]
We've seen some strange and unpredictable behaviour in other tools (mainly munki) trying to use the `/usr/sbin/softwareupdate` tool, so this might not be as easily implemented as you'd wish @xirianlight.
Greg had to rebuild Munki to use the Software Update panel in System Preferences to get around the problem (mainly system hanging when issuing command for system upgrade to newer version, forcibly reboot would get you back to previous state i.e. not upgraded). I don't remember exactly right now, but I think this was one of the major changes to Munki 4.

**Comment by xirianlight** [comment]
> We've seen some strange and unpredictable behaviour in other tools (mainly munki) trying to use the `/usr/sbin/softwareupdate` tool, so this might not be as easily implemented as you'd wish @xirianlight.
> Greg had to rebuild Munki to use the Software Update panel in System Preferences to get around the problem (mainly system hanging when issuing command for system upgrade to newer version, forcibly reboot would get you back to previous state i.e. not upgraded). I don't remember exactly right now, but I think this was one of the major changes to Munki 4.

Oh, totally - I'm working in Addigy, and their Self Service app doesn't currently support opening the app to a specific policy, but I'm hoping that one day it will. The workflow I'm hoping to be able to achieve one day is having users be able to click on the Nudge button and have it open Addigy's Self Service app with certain text already in the search field (or a certain category selected) so that users just have to click on my "Upgrade to Big Sur" button, instead of launching the Big Sur installer app, which we currently have blocked. The command will likely end up being something like `/Addigy/Library/MacManage/MacManage.app --category "OS Upgrade"` - my goal is NOT to trigger the `softwareupdate` binary, just to be able to pass something with arguments

**Comment by grahampugh** [comment]
This would also be helpful to us, Jamf Pro customers.  Jamf Pro allows the use of `selfservice://` style URLs to trigger a Self Service item directly. We already have a working Self Service upgrade solution (using `erase-install.sh`) and it would be a pretty cool tool to integrate the two tools.

**Comment by diwanicki** [comment]
@grahamgilbert said, I'd like to be able to call a Jamf Self-Service item which has a command line call to softwareupdate which runs as root.

**Comment by hb3b** [comment]
This would be immensely helpful in bridging the SW update gaps in Jamf. The "Update Device" button could call a script that reaches out to the Jamf API to trigger a `ScheduleOSUpdate`.

**Comment by dan-snelson** [comment]
@hb3b See: https://github.com/macadmins/nudge/wiki/userInterface#actionbuttonpath---type-string-default-value-

**Comment by erikng** [comment]
https://github.com/macadmins/nudge/commit/35d9009880d94fe28ad8f1180a1751ff490f6f88 will now support bash/sh/zsh scripts within the `actionButtonPath`

`/bin/bash /path/to/script`
`/bin/sh /path/to/script`
`/bin/zsh /path/to/script`

they will run as the user. I do not plan on supporting root scripts at this time.
