### ISSUE TITLE
Nudge trigger a policy in Jamf

### ISSUE THREAD

**Issue by EdBascom** [macadmins/nudge#522]
How can I use Nudge to trigger a policy in Jamf Pro vs update OS through Apple. Can I use the actionButtonPath value to run a command line? Currently the value is <string>/System/Library/PreferencePanes/Softwareupdate.prefpane</string>

**Comment by el2493** [comment]
Check the wiki before asking, a lot of useful information there:
https://github.com/macadmins/nudge/wiki/osVersionRequirements#actionbuttonpath---type-string-default-value-nil
