### ISSUE TITLE
Allow disabling the "One hour" or "One day" deferral buttons

### ISSUE THREAD

**Issue by Tuttu** [macadmins/nudge#523]
Hello, 

At the moment, you can change the text of these buttons but there's no way to remove/disable the oneHourDeferralButton oneDayDeferralButton from the UI like they would be automatically hidden when reaching the good "[milestones](https://github.com/macadmins/nudge/wiki/User-Deferrals#behavior-of-defer-buttons)".

Is forcing the disabling of these two buttons something that has been / can be considered? 
Our scenario, for example, would be to hide the "One hour" deferral button so users get one deferral per day and the maximum allowed deferral becomes some kind of way to control how long you can defer an update.

**Comment by bradtchapman** [comment]
@Tuttu : 

You might want to try "single quit button" mode, and also turn off the User Quit deferrals, which is what's driving the other deferral choices and the calendar selection.  

Here are the settings I use:

`allowUserQuitDeferrals` = false
`allowLaterDeferralButton` = false
`singleQuitButton` = true

Users only get to click one of two buttons: "Open Software Update," or "Remind me Later."  It will Nudge them at the next interval for their current window (approaching, imminent, or expired).

@erikng : I think this can be closed as the administrator needs to consult the wiki, experiment with some settings, and consult with their peers in the Nudge channel if that's not working.

**Comment by Tuttu** [comment]
Hello @bradtchapman ,

Thanks for your answer. In fact, I thought I had already closed that issue. I'm sorry I forgot to to that. We have decided to go an entirely different way and we give users X days with an infinite number of deferrals to update their Macs. 🙂
