### ISSUE TITLE
Ignore randomDelay when calling `-version`

### ISSUE THREAD

**Issue by mikedowler** [macadmins/nudge#524]
If you have `randomDelay` configured (e.g. in a profile), then that gets applied even when using flags such as `-version`, where it doesn't really make much sense.  (However, I note that `-print-profile-config` and `-print-json-config` don't have the same issue.)

It would be great if `-version` ignored the `randomDelay`, or even if we could have a `-noRandomDelay` flag that we could pass for those situations where it is not needed.

**Comment by erikng** [comment]
I believe with the pre release version of v1.1.14 this is fixed. Can you please test?

**Comment by HowardGMac** [comment]
In my testing with `randomDelay` configured in a profile, version 1.1.14.81536 does not delay in properly giving you version information when the command `/Applications/Utilities/Nudge.app/Contents/MacOS/Nudge -version` is given.

**Comment by erikng** [comment]
Thanks for confirming.
