### ISSUE TITLE
Background Items name for Nudge application

### ISSUE THREAD

**Issue by CorporateAbdul** [macadmins/nudge#526]
Would it be possible to rename this from Mac Admins Open Source to Nudge? The reason is because some end users might raise questions around what it is taking into consideration that Nudge communications are shared with macOS end users.

<img width="514" alt="Screenshot 2023-11-24 at 09 45 57" src="https://github.com/macadmins/nudge/assets/151910919/830e3c07-ced6-4900-9f79-dffacb843032">

Else, please let me know if it is possible to item this already and how to do so.

**Comment by bradtchapman** [comment]
No, this is not possible.   It is based on the developer certificate.  

If you want to suppress these, you need to use an MDM and deploy a configuration profile with "Managed Login Items" or "Background Items" and supply the bundle ID of the Nudge app.

@erikng - I recommend this be closed.
