### ISSUE TITLE
"There is no application set to open the URL munki://updates" error

### ISSUE THREAD

**Issue by g33kphr33k** [macadmins/nudge#531]
Hello

I'm doing a test deploy to an end machine. Target is Big Sur (don't ask). I'm using the installation script and a very slightly adjusted .json file.

Upon launch, everything looks fine. When you click on Update Device, I get an error pop up stating "There is no application set to open the URL munki://updates".

Can anyone give me a solution please?

**Comment by erikng** [comment]
Do you have Munki installed? If not then don't use that.

**Comment by g33kphr33k** [comment]
So now I'm confused. How do I set up the updates?!

**Comment by erikng** [comment]
Read the wiki please. It's all documented there.
