### ISSUE TITLE
[Feature Request] Demo Mode + Custom UI Settings

### ISSUE THREAD

**Issue by rougegoat** [macadmins/nudge#534]
Currently, when you run `/Applications/Utilities/Nudge.app/Contents/MacOS/Nudge -demo-mode`, it shows the default language, image, and other UI settings.  With how customizable Nudge's UI is, it would be helpful to add an extra flag to the `demo-mode` that would also display any settings being applied by configuration profiles or other such deployed settings.

**Comment by erikng** [comment]
Sorry, but the effort to do this is just not worth the effort for me. If you are wanting to try out your configs, you should just run Nudge as is.

There is a `-bundle-mode` option I use for testing within Xcode and it has a bundled JSON to test things, but it is technically no different than just deploying a local json and using that for your config and just makes it easier on me for development purposes.

Demo mode was one of the first flags I created to just showcase the UI and take screenshots, but it serves no real purpose.
