### ISSUE TITLE
Feature Requests: UI Close Button, Streamlined Version Info, and Direct Software Update Process

### ISSUE THREAD

**Issue by ce603** [macadmins/nudge#535]
As a systems administrator, I'd like to provide feedback on some user experience issues observed with the Nudge dialog prompt, which has been causing confusion and frustration among users.

![707370271b3b3910b66a968f034bcb1f](https://github.com/macadmins/nudge/assets/32117687/d4246c81-c559-414d-a061-a0c5fdfbd14b)

**1. Issues with Dismissing the Dialog:**
Users often find the Nudge dialog appearing unexpectedly, interrupting their workflow. A major point of confusion lies in the use of a drop-down menu to dismiss the window, which is not a standard element for dismissing a window.

**Suggested Enhancement:**
Introducing a red close button in the top-left corner of the Nudge window would align with standard application interfaces and could significantly improve user interaction, as it would make it immediately obvious how to close the window. Upon clicking this button, an alert could inform users of their remaining time to update, with an optional drop-down menu for setting a custom deferral length. The system should use a default deferral value already selected for the user, so they can simply click "ok".

**2. OS Version Information:**
Currently, the display of detailed OS version information can be overwhelming for users not familiar with technical specifics, leading to increased anxiety.

**Suggested Enhancement:**
Moving this information to a secondary screen, accessible via an "OS Info" button positioned next to the "Nudge Info" button, would help declutter the main interface. This would allow users to focus on the primary message without being distracted or intimidated by technical details, while still retaining all the necessary technical information for those who need it.

**3. Streamlining the Update Process:**
The current method, which directs users to the software update screen in the control panel, can be cumbersome.

**Suggested Enhancement:**
A more user-friendly approach could involve redesigning the button functionality to directly initiate the update process, potentially by executing a command like `sudo softwareupdate -ia`. This method would simplify the process significantly, making it more accessible for all users. However, there may be security restrictions with automated administrative actions, and I'm interested in opening up a discussion on whether or not there might be a better way to initiate the system update.

I hope these suggestions contribute positively to the ongoing development of Nudge. I believe that by addressing these user experience issues, we can make the tool more intuitive and efficient for all users. I'm open to further discussions and would be happy to provide more input or clarification on these points if needed. Looking forward to the community's thoughts and feedback.

**Comment by erikng** [comment]
Hello @ce603 . I appreciate the thoughtful ticket you have created here, but I unfortunately disagree with each suggestion and will be closing this ticket.

> Issues with Dismissing the Dialog

This was a _deliberate_ design decision on my part to make this dialog harder to dismiss. The point of Nudge is to push the users into updating as soon as possible. If you would like something that follows Apple's User Interface Guide, I would suggest you just open up the Software Updates preference pane where those user elements are all clickable and follow that guide.

> OS Version Information

I don't understand your position on this given that the entire point of Nudge is to align macOS update versions on your fleet. Without this information, the user may install the wrong update(s). By burying that information, it will lead to more confusion

> Streamlining the Update Process

I agree in principle to your comments around cumbersome, however the suggested enhancement is something that I again deliberately designed against, based on my decade plus of experience managing macOS devices at scale. While Nudge does try and utilize some `softwareupdate` commands, it deliberately chooses commands that do not require administrative rights. Beyond this, Apple does not test installing updates at scale through the `--install` flag and over the years this has caused significant installation failures in larger organizations.

By using this more "cumbersome" workflow, we follow all of the "happy paths" Apple expects a non enterprise user to interact with, and we reduce the potential for update failures.
