### ISSUE TITLE
1.14 logs Failed to load data from URL: file:///Library/Preferences/com.github.macadmins.Nudge.json

### ISSUE THREAD

**Issue by kevinmcox** [macadmins/nudge#536]
As reported on Slack by `SBOD`, Nudge 1.14 is logging a line related to on-disk JSON even when managed via Configuration Profile.

Nudge appears to be working fine otherwise.

Nudge[96530]: [com.github.macadmins.Nudge:preferences-json] Failed to load data from URL: file:///Library/Preferences/com.github.macadmins.Nudge.json
Nudge[96530]: [com.github.macadmins.Nudge:user-interface] Delaying initial run (in seconds) by: 417
Nudge[96530]: [com.github.macadmins.Nudge:softwareupdate-download] enforceMinorUpdates: true
Nudge[96530]: [com.github.macadmins.Nudge:utilities] Current operating system (14.3) is greater than or equal to required operating system (14.3)
Nudge[96530]: [com.github.macadmins.Nudge:user-interface] Device is fully updated
Nudge[96530]: [com.github.macadmins.Nudge:user-interface] Nudge is terminating due to condition met

**Comment by erikng** [comment]
potentially fixed with https://github.com/macadmins/nudge/releases/tag/v1.1.14.81534

**Comment by erikng** [comment]
I have confirmed on my end it's fixed on https://github.com/macadmins/nudge/releases/tag/v1.1.14.81535 but I need confirmation from one other person.

**Comment by erikng** [comment]
confirmed fixed with @kevinmcox
