### ISSUE TITLE
Feature Request: CLI switch to ignore randomDelay preference

### ISSUE THREAD

**Issue by kevinmcox** [macadmins/nudge#537]
It would be helpful during testing and troubleshooting to have a CLI switch that would ignore the `randomDelay` preference key but apply all others in a configuration profile.

e.g. `/Applications/Utilities/Nudge.app/Contents/MacOS/Nudge --dontDelay`

This would allow for rapid repeat triggering of Nudge without needing to deploy a different configuration profile only to omit the `randomDelay` key.

**Comment by erikng** [comment]
`-disable-randomDelay` incoming

**Comment by kevinmcox** [comment]
Awesome!
