### ISSUE TITLE
Bug / Regression: shell script in actionButtonPath not working in v1.1.14 branch

### ISSUE THREAD

**Issue by hcbraun** [macadmins/nudge#539]
Hi,

previous version of Nudge did support shell scripts for `actionButtonPath` in the style:
`/bin/bash /path/to/script`

Starting with the 1.1.14 branch shell scripts stopped working. Last working version for me:
[Nudge 1.1.13.81510](https://github.com/macadmins/nudge/releases/tag/v1.1.13.81510)

`return nil` in `isShellCommand()` looks not good:
https://github.com/macadmins/nudge/blob/main/Nudge/Utilities/Utils.swift#L783

The original feature request: 
https://github.com/macadmins/nudge/issues/52

Would be great if shell script support could be added back in. 

Thanks for looking at this! 

Thanks for awesome Nudge!!!

**Comment by erikng** [comment]
please try https://github.com/macadmins/nudge/releases/tag/v1.1.14.81537

**Comment by hcbraun** [comment]
Thanks a lot Erik! Works again for me.
