### ISSUE TITLE
1.1.14.81536 seems to ignore some settings

### ISSUE THREAD

**Issue by phillymjs** [macadmins/nudge#540]
When testing Nudge 1.1.14.81536, the config profile that worked perfectly with the 1.1.13.81503 seems to be ignoring some settings when using the newer version-- specifically the ones that blur the screen and prevent certain app launches. I also removed the config profile and tested using a known-good-with-older-version local JSON pref file with the same settings, and the blurring and app blocking stuff was ignored again. The deadline that was set on the profile and the local preference file was in the past, so all the more aggressive features should have been in effect. I can provide the JSON pref file privately if needed.

**Comment by erikng** [comment]
Yes please. I tested the blur and know it worked but perhaps another portion of the code broke.

**Comment by erikng** [comment]
Confirmed by a user this fixed their issue.
