### ISSUE TITLE
Nudge no longer reacts to changes in the MDM profile.

### ISSUE THREAD

**Issue by bradtchapman** [macadmins/nudge#541]
Per issue #370 , Nudge was given the ability to react to changes in the MDM profile.  I remember that Nudge used to do this.  I could get the app to reload and display new values based on changes I was making to the configuration profile.  Or, if I made a change that would stop Nudge, such as removing it from scope or changing one of the two required parameters (install date and minimum version), then Nudge would disappear immediately.

When did this break?  Can we get it working again?  

Thanks.

**Comment by erikng** [comment]
I'm not sure what you are referring to. Issue 370 has been open for years now and It's never supported reloading preferences.

I'm closing this as a dupe. One day I will support that, but it would take a significant amount of work to fix it, which is why I've never done it.
