### ISSUE TITLE
"Application terminated" notifications not appearing

### ISSUE THREAD

**Issue by phillymjs** [macadmins/nudge#543]
Testing 1.1.14.81542, with application blocking enabled the notification does not appear when an attempt is made to launch one of the blocked applications. When I reverted to 1.1.13.81503, the notifications were displayed again.

**Comment by erikng** [comment]
please try https://github.com/macadmins/nudge/releases/tag/v1.1.14.81544

**Comment by phillymjs** [comment]
App blocking is working, notifications are working, but blurring stopped working. I tested .81544 and .81545.

**Comment by erikng** [comment]
I didn't touch the blur code, so that doesn't make much sense to me, but we discussed on slack that I need more info for the blur. Closing this one since it's fixed.
