### ISSUE TITLE
gracePeriodInstallDelay is no longer working in Nudge 1.1.14.81542

### ISSUE THREAD

**Issue by macseIva** [macadmins/nudge#545]
Hi,

It seems like _**gracePeriodInstallDelay**_ is no longer working since upgrading to Nudge 1.1.14.x.

The below is what we use for extending the requiredInstallationDate for newly enrolled Macs, and it was perfectly working with Nudge 1.1.13.81503, but seems to get skipped with Nudge 1.1.14.x.
After enrollment, Nudge immediately shows an expired deadline and blurs the screen, entering "aggressive user experience" straight away instead of extending the requiredInstallationDate by 120 hours (5 days).

```
<dict>
      <key>allowGracePeriods</key>
           <true/>
      <key>gracePeriodInstallDelay</key>
           <integer>120</integer>
      <key>gracePeriodLaunchDelay</key>
           <integer>1</integer>
 </dict>
```
 
I tested the same exact configuration with 1.1.13.81503 after re-enrolling and everything worked fine. Once I upgraded to 1.1.14.81542,  _**gracePeriodInstallDelay**_ got bypassed and Nudge immediately popped up again with an "aggressive user experience".
_**gracePeriodLaunchDelay**_ seems to be working fine.

Please let me know in case further details are needed to troubleshoot.

**Comment by erikng** [comment]
please try https://github.com/macadmins/nudge/releases/tag/v1.1.14.81545
