### ISSUE TITLE
Enhancement Request: Custom icon/wording for "app is blocked" notifications

### ISSUE THREAD

**Issue by phillymjs** [macadmins/nudge#546]
Would it be possible to customize the icon and wording that appears in the notification when an application is blocked/terminated?

I like the way swiftDialog does it-- an image file can be placed in a specific location with a specific filename before the package is installed, and whatever image file is there is adopted as the app and notification icon, otherwise the standard Dialog.app icon is used.

Being able to customize the wording is more of a nice-to-have, I've always felt it should say "update your operating system" instead of "update your device."

**Comment by erikng** [comment]
This will be available in the next pre-release.
