### ISSUE TITLE
Request: allow administrators to always hide the Deferral button during any refresh window.

### ISSUE THREAD

**Issue by bradtchapman** [macadmins/nudge#549]
In issue #548 , I have asked for deferRunUntil to reflect a time that includes the duration of the various refreshCycle timers, depending on what window Nudge is in (initial, approaching, imminent).  As an alternate behavior, please consider an option that would allow administrators to **always** hide the Deferral button under any circumstance.  That way the users can be given a promised interval before Nudge pops up, but they can still pile their windows on top, since Nudge cannot be currently moved.

Edit: I would like to do this without lowering the deferral threshold to zero, which would trigger aggressive behavior.  I'd like to reserve aggressive mode for the `expired` refresh cycle ONLY.

**Comment by erikng** [comment]
`allowUserQuitDeferrals` already exists.
