### ISSUE TITLE
Request: for calendar-based deferrals, a custom property to specify a maximum deferral time of X number hours before the requiredInstallationDate.

### ISSUE THREAD

**Issue by bradtchapman** [macadmins/nudge#552]
Please consider adding a custom property in Nudge that will allow administrators to set a maximum number of hours ahead of the deadline for calendar deferrals.  The intent is to prevent users from deferring Nudge too close to the deadline (e.g.: 1 hour) and instead limit their ability to defer past a certain point.  For example: with a `requiredInstallationDate` of 2024-03-15T17:00:00 (3/15 @ 5PM) and a `calendarDeferralLimit` of 72 hours, a user could only use the calendar deferral up to 3/12 @ 5PM, and no later.

**Comment by drtaru** [comment]
This is what `approachingwindowtime` does.
https://github.com/macadmins/nudge/wiki/userExperience

**Comment by bradtchapman** [comment]
This was apparently a bug and was fixed in the latest release. 

FR no longer required.  OK to close.
