### ISSUE TITLE
Issue: No calendar popup when selecting 'Defer Until..."

### ISSUE THREAD

**Issue by bekkahc20** [macadmins/nudge#557]
Hi, 

When I select the 'defer until...' option in the Nudge UI, the calendar does not pop up for users to choose a custom date/time. Nudge is closing and will reopen at the hour's 0- or 30-minute mark.  It feels as if the app is crashing. 

The video below is a screen recording of the issue, and the steps to reproduce it are to deploy Nudge and then click 'Defer until..."

https://github.com/macadmins/nudge/assets/83666991/6958386f-8547-4a68-9f13-a53eaf66aabd

I have the following set:

- Required install date set as 3/28/24
- Approaching Refresh Cycle is 6 hours
- Approaching Window Time is 4 days
- Imminent Refresh Cycle is 4 hours
- Imminent Window Time  is 2 days
- All User Quit Deferrals is set to True

I am using Post-Install Script 0.0.22 and Nudge 1.1.14.81549 pkg. 

Thanks!

**Comment by bekkahc20** [comment]
I also have crash reports in Console logs for Nudge.

**Comment by erikng** [comment]
Please send me the crash reports and your entire preferences set. I cannot recreate the calendar issue.

**Comment by erikng** [comment]
please try https://github.com/macadmins/nudge/releases/tag/v1.1.14.81554
