### ISSUE TITLE
v1.1.15.81559 - Although Required Installation Date is Future, it terminates Application Bundle ID on every launch.

### ISSUE THREAD

**Issue by anikishore** [macadmins/nudge#562]
Version Nudge-1.1.15.81559. 

Although the required installation date is in future date, it quits blocked application bundleID on every launching of the Nudge banner. But same values being respected and working correctly with version 1.1.1381510

terminateApplicationsOnLaunch: true
blockedApplicationBundleIDs:
com.apple.Safari, com.google.chrome
requiredInstallationDate: 2024-04-04T22:00:00Z

**Comment by erikng** [comment]
Please provide your entire config and the logs showing it terminating applications. I did not experience this behavior.

**Comment by anikishore** [comment]
[com.github.Nudge.json](https://github.com/macadmins/nudge/files/14563790/com.github.Nudge.json)
[nudge 2.log](https://github.com/macadmins/nudge/files/14563791/nudge.2.log)

**Comment by erikng** [comment]
I have recreated the issue. This will be addressed in v1.1.16. Coming soon.
