### ISSUE TITLE
Create an autopkg download/munki recipe for Nudge

### ISSUE THREAD

**Issue by erikng** [macadmins/nudge#57]

**Comment by rorymurdock** [comment]
https://github.com/autopkg/autopkg/wiki/Using-CodeSignatureVerification
https://github.com/autopkg/autopkg/wiki/Autopkg-and-recipe-parent-trust-info

**Comment by rorymurdock** [comment]
Will do a PR once we hit release

https://github.com/autopkg/recipes/compare/master...rorymurdock:add-nudge

**Comment by erikng** [comment]
It's unlikely Greg will accept it there. Worth a shot. If he doesn't, we should just make an autopkg recipes in the macadmins space.

**Comment by erikng** [comment]
@rorymurdock after thinking about this, the way autopkg is structured, we can't make a macadmins-autopkg-recipe if we want it to be in the search results.

I had planned on putting this in https://github.com/autopkg/erikng-recipes anyway.

**Comment by rorymurdock** [comment]
Ah sure, can put it wherever, doesn't matter too much

**Comment by erikng** [comment]
I'm making some changes to it now to fit what I wanted from it.

**Comment by erikng** [comment]
https://github.com/autopkg/erikng-recipes/pull/6 now here and merged. Check it out @rorymurdock
