### ISSUE TITLE
one-time setup and automatically update the Mac OS version 

### ISSUE THREAD

**Issue by mani2care** [macadmins/nudge#570]
Is it possible to automate using this JSON file? to add the new functionality and update the macOS version on the scheme?
obtain the most recent version of the miner, compatible with the device. 
obtain the latest major version that is compatible with the device.
Permit the release date exception to last for seven days in order to apply the patch for a while, and then modify the value to reflect the most recent version to trigger Windows in this manner. 

if this is possible, then we no longer need to modify the Nudge configuration profile and reapply the settings. 

https://sofa.macadmins.io/v1/macos_data_feed.json

sample script.

[All-macOS-Release-Dates.sh.zip](https://github.com/macadmins/nudge/files/15202615/All-macOS-Release-Dates.sh.zip)

**Comment by erikng** [comment]
Anything is possible. Are you asking that I build all of this functionality for you?

If so, I can't commit to anything. But you are welcome to write a script that configures the nudge json on disk appropriately based on your unique needs and desires. 

I haven't publicly said if I will implement sofa. I may, I may not. If I do, it will be opinionated in what serves me the best. This may or may not serve you the way you want it to.

**Comment by bradtchapman** [comment]
Check out this new project: SOFA.  A feed for macOS updates.  @mani2care , you would still need to write your own automation for Nudge settings based on this feed. 

https://sofa.macadmins.io/

**Comment by erikng** [comment]
I'm closing because I'm tracking this here already https://github.com/macadmins/nudge/issues/264
