### ISSUE TITLE
Improving User Experience for App Upgrade Process

### ISSUE THREAD

**Issue by mani2care** [macadmins/nudge#571]
The app upgrade process is currently causing frustration among users due to longer loading times, leading to multiple attempts to open the installer service and unnecessary complaints about macOS not loading. To mitigate this issue and enhance user experience, consider implementing the following measures:

Disable Upgrade Button During Loading: Temporarily disable the upgrade button until the installer service finishes loading to prevent users from initiating multiple upgrade attempts.
Delay Nudge Window Popup: Delay the popup of the nudge window until the installer service has fully loaded and the app upgrade process is ready to proceed, minimizing interruptions and confusion for users.
By implementing these strategies, we can reduce user complaints and ensure a smoother app upgrade experience on macOS devices.

Uploading Untitled11.mov…

**Comment by colorenz** [comment]
I think asynchronousSoftwareUpdate should adress that.

https://github.com/macadmins/nudge/wiki/optionalFeatures#asynchronoussoftwareupdate---type-boolean-default-value-true-required-no

asynchronousSoftwareUpdate - Type: Boolean, Default Value: True, Required: No
v1.1.4 and later

When disabled, Nudge will wait for Software Update to finish downloading (if any) updates before showing its UI.

**Comment by mani2care** [comment]
Yes after download it may not have any validation

Thanks & Regards,

Manikandan R
Contact: +91-9902103878
E-mail: ***@***.***

**Comment by erikng** [comment]
This isn't possible as Apple doesn't expose anything for me to understand when an update is "in progress" post download.

If you can figure out some magic I can understand, I'm happy to implement because it's something that bothers me as well.

**Comment by erikng** [comment]
I just found https://github.com/macadmins/nudge/issues/555#issuecomment-1984353455

**Comment by erikng** [comment]
see https://github.com/macadmins/nudge/issues/555#issuecomment-2203519982 for information on what I did.
