### ISSUE TITLE
SOFA Functionality: Option to skip macOS versions with no CVEs

### ISSUE THREAD

**Issue by kevinmcox** [macadmins/nudge#578]
In addition to having different SLAs for CVE vs. no-CVE macOS updates, it would be good to have a feature that allows skipping no-CVE updates completely.

Effectively this means Nudge will only start a "Nudge cycle" for releases with CVEs in them.

One thing to consider might be: What if there are no published CVEs when the release first comes out, but Apple updates documentation later to add them?

**Comment by erikng** [comment]
I've added both in the most recent `development`.

>One thing to consider might be: What if there are no published CVEs when the release first comes out, but Apple updates documentation later to add them?

This is going to be a hard one to tackle and one I don't have any ideas on yet other than wait and see once this feature set launches. I don't even know what happens with SOFA feed bug we should ping @headmin to see his thoughts.
