### ISSUE TITLE
Vendor assessment

### ISSUE THREAD

**Issue by Selvam-Periyasami** [macadmins/nudge#581]
Our organisation security team wants to fill vendor assessment form to use this tool in the environment. Can I get some advice here . Contact name and support email id etc

**Comment by kevinmcox** [comment]
Nudge is free and open source, provided under the Apache License 2.0: https://github.com/macadmins/nudge/blob/main/LICENSE

There are no contacts for support.

**Comment by erikng** [comment]
This is a training opportunity for both you and your security team. Unlike paid for tools, there is no "vendor". Should you consume this tool and deploy it out, it is ultimately up to you and your security team to read the code, understand it and approve its use for your company.

The license is made in a way that support is not guaranteed, though I am very active in the development of the tool. This is your "cost" for using free, open source tooling.

**Comment by Selvam-Periyasami** [comment]
Thanks for your information Eric. Will update them .
