### ISSUE TITLE
Unable to fetch major upgrade and application missing, exiting Nudge

### ISSUE THREAD

**Issue by RiversideKid** [macadmins/nudge#586]
I have a new install of Nudge with Erase-Install.sh configured.  The Erase-Install.sh script works when executed alone.  The nudge configuration is below.  When I scope a test workstation to these configuration profiles and policies I find that the nudge.log file ends with "Unable to fetch major upgrade and application missing."  On a fresh test computer the log file for the erase-install.sh log never shows up as it is not executed.

requiredInstallationDate = 2024-06-27T06:00:00Z (tomorrow)
requiredMinimumOSVersion = 14.5 (current)
enforceMinorUpdates = false (I have tried true as well)
allowGracePeriods = true
allowLaterDeferralButton = true
actionButtonPath = jamfselfservice://content?entity=policy&id=2909&action=execute (The Erase-Install policy that works)

What have I done wrong to see the error "Unable to fetch major upgrade and application missing, exiting Nudge" in the /var/log/Nudge.log file?

**Comment by randomName0815** [comment]
Hi, I see the same message in the log, we have already updated many clients, but for many 13.6.x clients Nudge just won't start.
Also with a self service policy for upgrade via EraseInstall, but it has been running for almost two months now, so the requiredInstallationDate has long passed.

relevant config parts:
    <key>osVersionRequirements</key>
    <array>
      <dict>
        <key>actionButtonPath</key>
        <string>jamfselfservice://content?entity=policy&amp;id=598&amp;action=view</string>
        <key>requiredInstallationDate</key>
        <string>2024-06-05T12:00:00Z</string>
        <key>requiredMinimumOSVersion</key>
        <string>14.4.1</string>
      </dict>
    </array>
    <key>userExperience</key>
    <dict>
      <key>allowedDeferrals</key>
      <integer>30</integer>
      <key>gracePeriodInstallDelay</key>
      <integer>24</integer>
      <key>gracePeriodLaunchDelay</key>
      <integer>2</integer>
      <key>gracePeriodPath</key>
      <string>/private/var/db/.AppleSetupDone</string>
      <key>nudgeRefreshCycle</key>
      <integer>1800</integer>
    </dict>

**Comment by RiversideKid** [comment]
I found a solution:  With these set, Nudge does not download and the Erase-Install script does the downloading.
attemptToFetchMajorUpgrade = false
asynchronousSoftwareUpdate = false

**Comment by randomName0815** [comment]
yeah, i'm testing the same thing... 


offtopic:
but in the meantime we realize that we also have another bug since the weekend, thanks to jamf 
'PI119354 - Self Service macOS Crashes when using URL schemes to open content: open “jamfselfservice://content?entity=policy&id=1000&action=view” '
test your button if you´re on jamf 11.6+ 😵‍💫

**Comment by RiversideKid** [comment]
Yes, I have already run into that bug.  (I didn't realize it was a bug at first since I have never used an installation URL before, but I know now.)  Now I need to wait for an upgrade or patch to continue.

**Comment by randomName0815** [comment]
if you´re using jamf connect, you can open self service with jamfconnect://getsoftware and set the policy self service settings to "Include the policy in the Featured category"... my best workaround so far, if there are not to many other featured policies 😬

**Comment by RiversideKid** [comment]
This has solved the issue.
I found a solution: With these set, Nudge does not download and the Erase-Install script does the downloading.
attemptToFetchMajorUpgrade = false
asynchronousSoftwareUpdate = false
