### ISSUE TITLE
Nudge cannot open Self Service?

### ISSUE THREAD

**Issue by RiversideKid** [macadmins/nudge#587]
The Nudge dialog box opens and eventually the only option is to "Update Device" but when we click "Update Device" the screen flickers and we are presented with an error "Self Service quit unexpectedly" with a long string of codes.

Nudge is configured with an actionButtonPath of "jamfselfservice://content?entity=policy&id=2909&action=execute" which points to the policy for our Erase-Install script.

If we instead launch the Self Service application BEFORE clicking "Update Device" on the nudge dialog box the nudge dialog box is able to launch the Erase-Install policy and upgrade the computer.

How can I configure Nudge so that the nudge dialog can execute the Jamf policy to Erase-Install the computer?  Can nudge launch self service app as well as the upgrade dialog box?

I have been working with the 'latest' version 1.1.16.81564 and then attempted the latest pre-release, 2.0.0.81657 with the same result.

(I need to run this on Big Sur, Monterey and Ventura to get these upgraded to Sonoma.)

**Comment by raydemay** [comment]
Is your Jamf server on 11.6.1? There is a PI for this. 

PI119354 - Self Service macOS Crashes when using URL schemes to open content.

**Comment by raydemay** [comment]
Jamf doesn't always add PIs to the Known Issues list, so people report them in the jamf-product-issues channel in Macadmins Slack.

**Comment by erikng** [comment]
Closing this as it is a JAMF issue. Good luck patching your server.
