### ISSUE TITLE
Nudge 2.0 - Escape hatch for 'unsupported device UI' when screen is blurred

### ISSUE THREAD

**Issue by robban247** [macadmins/nudge#589]
![UnsupportedDeviceUI](https://github.com/macadmins/nudge/assets/60750297/f0f90c98-d56b-47ee-a843-4c3232ed42a2)

When **requiredMinimumOSVersion** is set to `latest` and the required date has passed the new unsupported device UI blurs the screen while leaving the end user with no obvious way to stil save their data and so on to take further action. (Example image of this provided)  

An escape hatch should be provided for this scenario.

**Comment by erikng** [comment]
https://github.com/macadmins/nudge/commit/03a32406380cfb87ddf5aa55ce786781a6273e37 added here

`informationButtonTextUnsupported` was changed to `actionButtonTextUnsupported` and there is new logic to handle the button state.
