### ISSUE TITLE
Document breaking change on bold text with markdown support

### ISSUE THREAD

**Issue by erikng** [macadmins/nudge#595]
Admins may need to update their configs to ensure bold text is kept through the use of `**` since the text is now rendered in markdown

**Comment by bradtchapman** [comment]
Does it work if they write \*\* ?

**Comment by erikng** [comment]
Yes

**Comment by erikng** [comment]
Documented here. https://github.com/macadmins/nudge/commit/43e62e043ad0d17ff1245fe09f4424b9f0628340
