### ISSUE TITLE
Inaccurate log related to `requiredMinimumOSVersion`

### ISSUE THREAD

**Issue by jholt13** [macadmins/nudge#597]
I get an inaccurate log line related to `requiredMinimumOSVersion`.  The feature works as expected, just the logging appears to be having a hiccup.  On version 2.0.0.81702 of Nudge, setting `requiredMinimumOSVersion` to `latest`, `latest-minor`, or `latest-supported` results in the log following log line

```
2024-07-16 13:45:54.914003-0700  localhost Nudge[984]: [com.github.macadmins.Nudge:utilities] Invalid format for requiredMinimumOSVersion - value is latest
``` 
However, later in the log, it appears that Nudge is parsing the SOFA feed and correctly interpreting which OS Version should be required.
```
2024-07-16 13:45:54.914458-0700  localhost Nudge[984]: [com.github.macadmins.Nudge:sofa] SOFA Matched OS Version: 14.5
```

The Nudge UI accurately displays 14.5 as the required OS version.  I've observed this on macOS 13.6 as well using the `latest-minor` key.  Nudge determines 13.6.7 is the required macOS version and reflects that in the logs and UI.  

On macOS 15.0 Beta 3, Nudge understands that our current OS version satisfies the requirements based on the SOFA feed
```
2024-07-16 13:34:08.200126-0700  localhost Nudge[39504]: [com.github.macadmins.Nudge:utilities] Current operating system (15.0) is greater than or equal to required operating system (14.5)
```

## Reproduction Steps
* Install Nudge 2.0.0.81702 on macOS 13.6, 14.4, or 15.0
* Use the [Example Assets/com.github.macadmins.Nudge.json](https://github.com/macadmins/nudge/blob/main/Example%20Assets/com.github.macadmins.Nudge.json) provided config and update `requiredMinimumOSVersion` to `latest`, `latest-minor`, or `latest-supported`
* Kick off Nudge `/Applications/Utilities/Nudge.app/Contents/MacOS/Nudge -json-url file:///path/to/config.json`

Logs attached from different macOS versions show behavior with different `requiredMinimumOSVersion` keys.
[Nudge-13.6.log](https://github.com/user-attachments/files/16256565/Nudge-13.6.log)
[Nudge-14.4.log](https://github.com/user-attachments/files/16256567/Nudge-14.4.log)
[Nudge-15.0.log](https://github.com/user-attachments/files/16256577/Nudge-15.0.log)

**Comment by erikng** [comment]
https://github.com/macadmins/nudge/commit/bb0fa25acf25e5b24bf77e1af051d3e8a26ef74b

Addressed
