### ISSUE TITLE
Drop down menu in lower right hand corner is displaying in the upper left.

### ISSUE THREAD

**Issue by tyler-seabridge** [macadmins/nudge#598]
We have users reporting that when they click on the 'defer' drop down menu in the lower right hand corner it displays in the upper left.

**Comment by erikng** [comment]
I need more info and proof. What version of Nudge?

**Comment by tyler-seabridge** [comment]
We are on Nudge version: 1.1.16.81564

***@***.***


[signature_227801348]
Tyler Seabridge
IT Support Analyst
WB Games
***@***.******@***.***>




From: Erik Gomez ***@***.***>
Date: Wednesday, July 17, 2024 at 12:31 PM
To: macadmins/nudge ***@***.***>
Cc: Seabridge, Tyler ***@***.***>, Author ***@***.***>
Subject: Re: [macadmins/nudge] Drop down menu in lower right hand corner is displaying in the upper left. (Issue #598)
[CAUTION]
This email originated outside Warner Bros.


I need more info and proof. What version of Nudge?

**Comment by erikng** [comment]
Please try 2.0. I still need proof and logs on what's happening though. 

What models, how many screens user is using etc.

**Comment by erikng** [comment]
I don't want to just close tickets without investigating, but the compiler, swift version and a tremendous amount of code is different now, so I will not be testing this on v1.1.6 code base. Please retest and then re-open if it's still happening.
