### ISSUE TITLE
When a profile update is installed, Nudge may not update the UI and logic

### ISSUE THREAD

**Issue by erikng** [macadmins/nudge#602]
After solving for https://github.com/macadmins/nudge/issues/370, it now appears that the entire UI may need to be torn down and re-assessed from scratch. I don't know what to do here yet, besides possibly just exiting out of nudge and relying on the launch agent.

I will think through this.

**Comment by erikng** [comment]
This may not be the bug, but currently my working theory.

**Comment by securitygeneration** [comment]
Is it not possible for Nudge to exit and relaunch itself on the fly?

**Comment by securitygeneration** [comment]
Otherwise, just exiting and letting the LaunchAgent handle it seems like a fair solution to me.

**Comment by erikng** [comment]
Nudge will now quit if the MDM profile is re-installed _**and**_ the content of the MDM profile has changed.

https://github.com/macadmins/nudge/commit/f13a697dd61400f7f0d73dc38226f7769ed8e4f4
