### ISSUE TITLE
Command-line arguments to emulate a specific macOS version and hardware model for testing purposes

### ISSUE THREAD

**Issue by securitygeneration** [macadmins/nudge#606]
Previously admins tested Nudge changes by artificially setting various attributes in `osVersionRequirements`. Now with a Nudge 2.0 install using SOFA, this is not quite as feasible, requiring an admin to spin up an actual system (physical or virtual) on a given version.

The feature request is to add a command-line attribute which allows the admin to spoof the current device's macOS version and/or hardware model to facilitate testing of various Nudge configuration changes.

**Comment by rougegoat** [comment]
This would also help with testing out the Unsupported mode.  I'd love to use that, but with it having minimal documentation and no apparent simulation options I'm gonna have to disable it for a while.

**Comment by erikng** [comment]
added here https://github.com/macadmins/nudge/commit/d1015cf2023d335f25d2bdc7fa4f686914c57918
