### ISSUE TITLE
Use  Local Date Format for Required Date in v2.0 unless specified in JSON/Profile

### ISSUE THREAD

**Issue by Tribruin** [macadmins/nudge#615]
Currently the required date is displayed in MM/DD/YYYY format unless overridden in a profile/json file. Most EMEA and APAC countries use different formats such as DD/MM/YYYY or YYYY-MM-DD. While we can set a different format, that would mean having different settings by region and country. 

Feature request is to use the Locale date format unless overridden in the profile/json.

**Comment by erikng** [comment]
Have no intention of doing this. You can use a different format that works for all regions vs just MM/DD. For example MMM

I already didn't want to support this feature, but I did so to be nice. Next request will be to support military vs non military (12 vs 24 hour formats).

if you really want this, please create two configs and maintain them.

**Comment by erikng** [comment]
I re read this. 

Perhaps https://www.swiftyplace.com/blog/swift-date-formatting-10-steps-guide would work. But I don't know. Do you know if there is a built in method for this in swift?

**Comment by Tribruin** [comment]
Here is some pseduo code I pulled from ChatGPT and ran through xCode Playgrounds.  

`
let currentDate = Date()

let dateFormat = DateFormatter.dateFormat(fromTemplate: "MMddyyyy", options: 0, locale: Locale.current)
let dateFormatter = DateFormatter()
dateFormatter.dateFormat = dateFormat


print("Required Date: \(dateFormatter.string(from: currentDate))")
`

**Comment by erikng** [comment]
This should be fixed with https://github.com/macadmins/nudge/commit/84fb1653d68649ea1556367bb866c0b732ed71f7

https://github.com/macadmins/nudge/actions/runs/10079098388
go to Packages (you must be signed in) and then unzip it and run manually

**Comment by Tribruin** [comment]
I can confirm that is the date format is now set based on the format selected in System Settings. I also confirmed that setting the `requiredInstallationDisplayFormat` key still overrides the system format. 

Thanks, as always, for your quick response.

**Comment by erikng** [comment]
Great. I will release v2.0.5 with this fix once the other person who requested a feature tests and confirms if it solves their issue.
