### ISSUE TITLE
Feature Request : Option to iuse Security Info URL from SOFA for More Info 

### ISSUE THREAD

**Issue by Tribruin** [macadmins/nudge#629]
Ok, this totally falls into the niceity category. 

Since we can now create a simple config that covers multiple major OS versions and not have to update it each time there is a new O/S release, it would not make sense to have a URL that points to a specific O/S page. We currently point to Apple's Support page for macOS Sonoma.

It would be nice to set an option for the `aboutUpdateURL` setting to use the `SecurityInfo` URL key from SOFA. Maybe allow the `aboutUpdateURL` to have a special option like `use-sofa` similar to the `latest-minor` option.

**Comment by erikng** [comment]
What about cases like

https://github.com/macadmins/sofa/blob/main/v1/macos_data_feed.json#L69

**Comment by erikng** [comment]
Addressed here

https://github.com/macadmins/nudge/commit/01728354ec5ba416a790d60336910c89ca55527b
