### ISSUE TITLE
*UpdateEventLaunchDelay not factored into slaExtension calculation

### ISSUE THREAD

**Issue by securitygeneration** [macadmins/nudge#630]
If one of the `*UpdateEventLaunchDelay` keys are set, they don't appear to be factored in to the `slaExtension`. So if `*UpdateEventLaunchDelay=10 days` and `SLA=15 days` are set, 10 days after the release Nudge will activate, but the users will only have an effective SLA of 5 days.

The proposal is to include `*UpdateEventLaunchDelay` in the `slaExtension` calculation such that:

`releaseDate + slaExtension + (optional)LaunchDelay = enforcementDate`

**Comment by kevinmcox** [comment]
Original discussion was in #573.

**Comment by erikng** [comment]
Closing per convo on slack. 

Security teams commonly create internal standard SLAs for meeting patch health and those are always computed against the release date of the patch, not the internal date. 

So Kevin is correct, this is to merely not antagonize users for x amount of time before hitting them. But the SLA is the SLA

 External security audits would also expect the same thing. So let's close this issue and just document it better.
