### ISSUE TITLE
Custom Delay Notifications

### ISSUE THREAD

**Issue by jarvis5674** [macadmins/nudge#636]
Hello!

I am wondering if there is a way to add more customizable options when it comes to deferring the update? I know we can set the delays within one hour and one day, but if a user wanted to delay lets say choose "X" hours or "days" within the timeframe an organization sets the requiredInstallationDate key, is that possible?

**Comment by erikng** [comment]
If the user wants a custom delay, they should use the custom date. But apart from that, no there is not besides the three out of box options.
