### ISSUE TITLE
"Required OS Version" and "Days Remaining To Update" is cut off in german

### ISSUE THREAD

**Issue by AirBookMac** [macadmins/nudge#640]
Hello Erik! 
Is it possible, as in Nudge 1.16, to display the texts on the left side in "Required OS Version" and "Days Remaining To Update" in two lines again so that they are not cut off at the end?

thx

<img width="358" alt="Screenshot 2024-08-16 at 08 33 45" src="https://github.com/user-attachments/assets/8b982fed-cd4a-435a-ae4f-d6ce06f35366">

**Comment by erikng** [comment]
thanks for reporting, fixed here

https://github.com/macadmins/nudge/commit/2c509a70163027c6d6e9b795df2ba29106676596
