### ISSUE TITLE
mainContentText is not compatible with lists.

### ISSUE THREAD

**Issue by enpipi** [macadmins/nudge#652]
I entered sample text for the Markdown-style list notation provided by Apple, but it is not being reflected.

https://developer.apple.com/documentation/apple_news/apple_news_format/components/using_markdown_with_apple_news_format#2975748

mainContentText
`1. First list item\n1. Second list item\n\n1\\. Not a list item`

result
![CleanShot 2024-09-02 at 12 32 51](https://github.com/user-attachments/assets/bb4845b1-6485-450b-bb1e-872243a5d276)

**Comment by erikng** [comment]
That isn't supported by SwiftUI markdown. You're reading the wrong documentation. 

https://www.avanderlee.com/swiftui/markdown-text/

Only a few properties are officially supported.

**Comment by enpipi** [comment]
> Due to implementing markdown support, many of the elements within Nudge may no longer be in bold if you customize them.
> To work around this please add ** elements to these customizations
> For example: The mainContentNote value of Important Notes would become **Important Notes**
> [More Markup Options](https://developer.apple.com/documentation/apple_news/apple_news_format/components/using_markdown_with_apple_news_format#2975763)
https://github.com/macadmins/nudge/wiki/v2.0-features#breaking-changes

I checked from this wki. So it supports Text-Level Markdown Syntax and does not support Block-Level Markdown.
Thank you.

**Comment by erikng** [comment]
ah I'll fix the wiki! Thanks for telling me that.

**Comment by enpipi** [comment]
You have always helped me. Thank you too for always getting back to me so quickly.
