### ISSUE TITLE
SOFA feed being blocked?

### ISSUE THREAD

**Issue by Train100** [macadmins/nudge#654]
I tried to use the following command after installing Nudge and the attached configuration profile, but I am finding that while I am in the office the notification does not launch.  I suspect that a network port might be blocked, but I am only seeing a localbridge issue in the log stream, which I have attached along with the configuration file.  

`/Applications/Utilities/Nudge.app/Contents/MacOS/Nudge -simulate-os-version "14.2" -disable-random-delay`

Also interesting to note, when I run Nudge in demo-mode in the office, the log stream states that it can't find the required MinimumOSVersion 0.0 in the SOFA feed. 

[logstream.txt](https://github.com/user-attachments/files/17033557/logstream.txt)

[mobileconfig.txt](https://github.com/user-attachments/files/17033629/mobileconfig.txt)

**Comment by erikng** [comment]
If your company is blocking nudge, youll have to work through that. There is an issue with the sofa feed though that has been fixed now.

**Comment by Train100** [comment]
I am not in charge of the networking at the company.  Do you know what port they need to make open for Nudge?

**Comment by erikng** [comment]
443 - It's just standard internet calls.

**Comment by Train100** [comment]
It looks like I am not allowed to open up any ports on our network.  Is there a way to turn off the SOFA feed?

**Comment by erikng** [comment]
Yes. Please read the wiki.

**Comment by Train100** [comment]
I have disabled the SOFA feed under optionalFeatures in the configuration file, but the following command still does not prompt the Nudge notification and results in the same message in the log.

`/Applications/Utilities/Nudge.app/Contents/MacOS/Nudge -simulate-os-version "14.2" -disable-random-delay`

[log2.txt](https://github.com/user-attachments/files/17050992/log2.txt)
[mobileconfig2.txt](https://github.com/user-attachments/files/17050996/mobileconfig2.txt)
