### ISSUE TITLE
install script missing from wiki?

### ISSUE THREAD

**Issue by RedCSol** [macadmins/nudge#657]
Looks like an install script referenced in the wiki has vanished. 

[https://github.com/macadmins/nudge/wiki/Getting-Started#install-nudge](https://github.com/macadmins/nudge/wiki/Getting-Started#install-nudge
)
=====
### Install Nudge
The first step is to install Nudge.app itself. Nudge is extremely safe to install without configuration as it doesn't do anything unless it is configured and has a LaunchAgent configured to open it on a cadence. Install the latest version from the releases page. You will want the package that has a name similar to Nudge-2.x.x.x.x.x.pkg.

Alternatively, use the following .sh script to install the latest version published.

**[nothing follows]**

thanks!

**Comment by erikng** [comment]
I've never supported a script so whomever put that there.
