### ISSUE TITLE
Nudge is using releaseDate for oldest update instead of most recent from SOFA feed

### ISSUE THREAD

**Issue by swissarmygeek** [macadmins/nudge#661]
Doing some testing with a VM running macOS 13.6, it appears Nudge 2 uses the releaseDate from the oldest update - 13.6.1 - instead of what I expected - 13.7.  Shouldn't it always use the most recent minor update's releaseDate, since that will be the only one that can be installed?

If that is by design, please consider adding an option to always use the most recent minor update available when selecting releaseDate.

From Nudge.log:
2024-10-19 14:55:38.608009-0500  localhost Nudge[30166]: [com.github.macadmins.Nudge:sofa] minorVersionRecalculationThreshold is set to 99 - Current Version: 13.6 - Targeting version 13.6.1 requiredInstallationDate via SOFA

2024-10-19 14:55:38.608245-0500  localhost Nudge[30166]: [com.github.macadmins.Nudge:sofa] Found target macOS version 13.6.1 - releaseDate is 2023-10-25 00:00:00 +0000, slaExtension is 365 days, 0 hours, 0 minutes, 0 seconds

2024-10-19 14:55:38.608281-0500  localhost Nudge[30166]: [com.github.macadmins.Nudge:sofa] Setting requiredInstallationDate via SOFA to 2024-10-24 00:00:00 +0000

(I set the SLA to 365 just so Nudge would show a positive value for Days Remaining)
 
From sofa feed:
          "UpdateName": "macOS Ventura 13.7",
          "ProductName": "macOS",
          "ProductVersion": "13.7",
          "ReleaseDate": "2024-09-16T00:00:00Z",
          "ReleaseType": "OS",

          "UpdateName": "macOS Ventura 13.6.1",
          "ProductName": "macOS",
          "ProductVersion": "13.6.1",
          "ReleaseDate": "2023-10-25T00:00:00Z",
          "ReleaseType": "OS",

**Comment by swissarmygeek** [comment]
Ok found the discussion of minorVersionRecalculationThreshold.  I started with a profile someone else had set up, and they had set it to '99' (you can see it in my log snippet above).

However when I set that to 1, the targeted version is 13.6.9.  I tried '0' and even '-1' but it still targets 13.6.9.

I understand many want aggressive behavior for out of date Macs - but we don't necessarily.  Maybe just a shorter deadline.

So what I'm looking for is a way to use say, a 9 day SLA from releaseDate for current Macs, but a 1 or 2 day SLA for Macs that are very out of date.  Is that possible?

**Comment by erikng** [comment]
No. If you want granularity, manage it yourself. If you want automation, use sofa. It's impossible to do full automation and make everyone happy in every possible way they can want.
