### ISSUE TITLE
Feature Request: Support Latest macOS in targetedOSVersionsRule

### ISSUE THREAD

**Issue by marcelpogorzelski** [macadmins/nudge#665]
I have separate ***osVersionRequirement*** for Sequoia and Sonoma. In reality I need it to be separate for ***latest*** and ***previous***.

With SOFA feed it should be possible to add ***newest*** option for ***targetedOSVersionsRule*** which would target all Sequoia Macs. When macOS 16 comes around then it automatically switch to that version.
A ***previous*** option would also be great.

That coupled with the ***default*** option would pretty much solve the upgrade scenario I use where we force Macs to ***latest-minor*** in 5 days and  ***latest*** in 30 days.

***newest*** would of course need to adhere to ***nudgeMajorUpgradeEventLaunchDelay***

**Comment by erikng** [comment]
That's a very specific use case with a tremendous amount of complexity that I have no intention of doing. I appreciate you writing this, but for complex scenarios my encouragement is for you to not use sofa.
