### ISSUE TITLE
add logic for M1 macs

### ISSUE THREAD

**Issue by erikng** [macadmins/nudge#7]
- On m1 macs you cannot run `softwareupdate` and download updates without user interaction. We need to skip this unless apple changes the behavior in a future OS.

**Comment by rorymurdock** [comment]
<img width="682" alt="Screen Shot 2021-02-11 at 9 10 06 pm" src="https://user-images.githubusercontent.com/9400108/107732553-85828e80-6cad-11eb-909e-db31132e824f.png">
Captured the behaviour you were talking about

**Comment by erikng** [comment]
Yep. We already have detection logic for Architecture so whatever function you write just guard it to Intel only.

**Comment by erikng** [comment]
https://github.com/macadmins/nudge/pull/96 fixed here
