### ISSUE TITLE
Feature request - Key to enable/disable major upgrades

### ISSUE THREAD

**Issue by xirianlight** [macadmins/nudge#70]
Right now, I've got my MDM set up to detect the OS of a computer, and then deploy a customized json depending on what OS it finds. We do this to set the minimum-required OS to the newest version of whatever OS is on the Mac in question, and not nudge the user if they're fully-patched in 10.14 to upgrade to 10.15.

Would it be possible to simplify this logic? Perhaps if there was a key to say "If you see no updates other than a jump to a new, named OS version, consider the Mac updated and do not show nudge"? I'm hoping to get to the point where I can host a .json file online and point my devices at it so I don't have to update it across all our different fleets, but rather in one spot... the complex part comes in managing the minimum versions across macOS 10.14, 10.15, and 11.

Example json:

    "minimum_os_sub_build_versions":  ["18G6020", "19G2021", "20A5343i"],
    "update_major": false,
    "update_minor": true,

**Comment by erikng** [comment]
Good news! The new design handles this. Once the read me is written I think you'll be pleasantly surprised. I do not think you will need to host multiple JSON files with this version. 

I'm going to close this ticket.
