### ISSUE TITLE
Document how to extract logs from Nudge

### ISSUE THREAD

**Issue by erikng** [macadmins/nudge#97]
- Document LaunchDaemon
- Document debug/warn/etc via `log stream` for manual stuff
- document `log collect`

**Comment by erikng** [comment]
`log stream --predicate 'subsystem == "com.github.macadmins.Nudge"' --info --style syslog --color none` for local development testing

`log show --predicate 'subsystem == "com.github.macadmins.Nudge"' --info --style json`

`log show --predicate 'subsystem == "com.github.macadmins.Nudge"' --info --style json --debug`

If they want to capture debug logs in /var/log, they will need to make their own LD.

**Comment by rorymurdock** [comment]
https://github.com/macadmins/nudge/wiki/Logging

**Comment by erikng** [comment]
something was rendering incorrectly on the wiki breaking everything. Oddly enough it didn't show up in the code preview page. I've fixed it.
